Repository Alluxio/alluxio, pull requests merged in 2020-01, with the labels that each got.

#10679 Refactor FileSystem Interface
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemCache.java
  core/client/fs/src/main/java/alluxio/client/file/LocalCacheFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
  core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
  core/client/fs/src/test/java/alluxio/client/file/FileSystemCacheTest.java
  core/client/fs/src/test/java/alluxio/client/file/FileSystemFactoryTest.java
  core/client/fs/src/test/java/alluxio/client/file/MetadataCachingBaseFileSystemTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#10692 Parallelize load definition within a worker
  core/common/src/main/java/alluxio/util/CommonUtils.java
  job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
  job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
  job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Labels: API Change

#10451 [DOCFIX] Improve Hive doc
  docs/en/compute/Hive.md
Labels: Doc Fix

#10680 [DOCFIX] Use Spark built-in example for Spark on K8s example job
  docs/en/compute/Spark-On-Kubernetes.md
Labels: Doc Fix

#10695 Make FileInStream an abstract class
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
  core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/MockFileInStream.java
  job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionRunTaskTest.java
Labels: API Change

#10701 [DOCFIX] Remove file.load.ttl reference in doc
  docs/en/core-services/Caching.md
Labels: Doc Fix

#10704 Fix Distributed Load Retry Logic
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Labels: API Change

#10717 Use DynamicResourcePool for FS and Block clients
  core/client/fs/src/main/java/alluxio/client/block/BlockMasterClientPool.java
  core/client/fs/src/main/java/alluxio/client/file/CachingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
  core/client/fs/src/test/java/alluxio/client/file/FileSystemContextTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentDeleteIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterLoadMetadataTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentRenameIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/FileInStreamConcurrencyIntegrationTest.java
Labels: API Change, target-2.1.2

#10722 Use DynamicResourcePool for FS and Block clients
  core/client/fs/src/main/java/alluxio/client/block/BlockMasterClientPool.java
  core/client/fs/src/main/java/alluxio/client/file/CachingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
  core/client/fs/src/test/java/alluxio/client/file/FileSystemContextTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentDeleteIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java
  tests/src/test/java/alluxio/client/fs/ConcurrentRenameIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/FileInStreamConcurrencyIntegrationTest.java
Labels: API Change

#10719 Release clients back into pools during even during context reinit
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataReaderTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/NoopClosableResource.java
  core/client/fs/src/test/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriterTest.java
  job/server/src/main/java/alluxio/job/plan/replicate/EvictDefinition.java
  job/server/src/main/java/alluxio/job/plan/replicate/MoveDefinition.java
  shell/src/main/java/alluxio/cli/fsadmin/metrics/ClearCommand.java
  tests/src/test/java/alluxio/client/fs/BlockWorkerClientCloseIntegrationTest.java
Labels: target-2.1.2

#10727 Release clients back into pools during even during context reinit
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
  core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataReaderTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/NoopClosableResource.java
  core/client/fs/src/test/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriterTest.java
  job/server/src/main/java/alluxio/job/replicate/EvictDefinition.java
  job/server/src/main/java/alluxio/job/replicate/MoveDefinition.java
  tests/src/test/java/alluxio/client/fs/BlockWorkerClientCloseIntegrationTest.java
Labels: API Change

#10706 Add listening address for embedded journal
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingProxy.java
  core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingServer.java
  core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingTransport.java
Labels: API Change

#10665 Make DistributedCp/Mv not retry
  shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
Labels: API Change

#10739 Specify the Alluxio file system type with a class instead of a boolean
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/common-configuration.yml
  docs/_data/table/en/master-configuration.yml
  docs/_data/table/en/user-configuration.yml
  docs/_data/table/en/worker-configuration.yml
  docs/_data/table/master-configuration.csv
  docs/_data/table/user-configuration.csv
  docs/_data/table/worker-configuration.csv
Labels: API Change

#10747 Upgrade powermock from 1.6.1 to 1.6.2
  pom.xml
Labels: POM Change

#10698 Reduce client heartbeat frequency and heartbeat on context close
  core/client/fs/src/main/java/alluxio/client/metrics/MetricsHeartbeatContext.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#10749 Fix some bugs and add new properties for client-side cache
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreOptions.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#10762 Update spring maven repository to use HTTPS
  pom.xml
Labels: POM Change

#10770 Make FileOutStream an abstract class similar to FileInStream
  core/client/fs/src/main/java/alluxio/client/AbstractOutStream.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java
  core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
  core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/MockFileOutStream.java
Labels: API Change

#10757 Add integration tests for client side cache
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  tests/src/test/java/alluxio/client/fs/LocalCacheFileInStreamIntegrationTest.java
Labels: API Change

#10773 Add listening address for embedded journal
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcProxy.java
  core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServer.java
  core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcTransport.java
Labels: API Change

#10775 Fix client leaks of copyFromLocal command
  core/common/src/main/java/alluxio/cli/AbstractShell.java
  core/common/src/main/java/alluxio/cli/Command.java
  shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
Labels: API Change

#10784 [DOCFIX] Add alluxio presto sandbox AMI docs
  docs/en/cloud/AWS-EMR.md
  docs/en/cloud/Alluxio-Presto-AMI.md
  docs/en/compute/Hive.md
  docs/img/presto_sandbox_ec2_choose_ami.png
  docs/img/presto_sandbox_ec2_instance_type.png
  docs/img/presto_sandbox_ec2_instances.png
  docs/img/presto_sandbox_ec2_key_pair.png
  docs/img/presto_sandbox_ec2_launched_instance.png
  docs/img/presto_sandbox_ec2_limit_error.png
  docs/img/presto_sandbox_ec2_limits.png
  docs/img/presto_sandbox_ec2_region.png
  docs/img/presto_sandbox_ec2_review.png
  docs/img/presto_sandbox_ec2_security_groups.png
Labels: Doc Fix

#10764 [DOCFIX] Add performance tuning doc for ufs instream
  docs/en/operation/Performance-Tuning.md
Labels: Doc Fix

#10798 Enable tests after release
  tests/pom.xml
Labels: POM Change

#10805 Port changes of [#10704] to branch-2.1
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Labels: API Change

#10782 Add metricsMaster.getMetrics() and fix fsadmin report metrics
  core/client/fs/src/main/java/alluxio/client/meta/MetaMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterClient.java
  core/client/fs/src/main/java/alluxio/client/metrics/MetricsMasterClient.java
  core/client/fs/src/main/java/alluxio/client/metrics/RetryHandlingMetricsMasterClient.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
  core/server/master/src/main/java/alluxio/master/metrics/MetricsMaster.java
  core/server/master/src/main/java/alluxio/master/metrics/MetricsMasterClientServiceHandler.java
  core/transport/src/grpc/meta_master.proto
  core/transport/src/grpc/metric_master.proto
  core/transport/src/main/java/alluxio/grpc/GetMetricsPOptions.java
  core/transport/src/main/java/alluxio/grpc/GetMetricsPOptionsOrBuilder.java
  core/transport/src/main/java/alluxio/grpc/GetMetricsPResponse.java
  core/transport/src/main/java/alluxio/grpc/GetMetricsPResponseOrBuilder.java
  core/transport/src/main/java/alluxio/grpc/MetaMasterClientServiceGrpc.java
  core/transport/src/main/java/alluxio/grpc/MetaMasterProto.java
  core/transport/src/main/java/alluxio/grpc/MetricMasterProto.java
  core/transport/src/main/java/alluxio/grpc/MetricValue.java
  core/transport/src/main/java/alluxio/grpc/MetricValueOrBuilder.java
  core/transport/src/main/java/alluxio/grpc/MetricsMasterClientServiceGrpc.java
  docs/en/operation/Admin-CLI.md
  minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
  shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/report/MetricsCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/MetricsCommandTest.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java
  tests/src/test/java/alluxio/client/cli/fsadmin/metrics/MetricsCommandIntegrationTest.java
  tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
  tests/src/test/java/alluxio/server/ft/journal/TriggeredCheckpointTest.java
Labels: API Change

#10817 Remove advice on hive.force-local-scheduling in doc
  docs/cn/compute/Presto.md
  docs/en/compute/Presto.md
Labels: Doc Fix
