Repository Alluxio/alluxio, pull requests merged in 2022-09, with the labels that each got.

#16128 Add a configurable temp ufs dir
  core/common/src/main/java/alluxio/Constants.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/util/io/PathUtils.java
  core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Labels: API Change

#15855 Support ignore delete mount point directory by ttl action
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterFsOptsTest.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
  tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
  tests/src/test/java/alluxio/server/ft/journal/JournalReplayIntegrationTest.java
  tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
Labels: API Change

#15475 Add support to ofs schema name
  core/common/src/main/java/alluxio/Constants.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  docs/cn/ufs/Ozone.md
  docs/en/ufs/Ozone.md
  underfs/ozone/src/main/java/alluxio/underfs/ozone/OzoneUnderFileSystemFactory.java
Labels: API Change

#16169 Add extra monitoring indicators part1
  core/common/src/main/java/alluxio/Constants.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/exception/BusyException.java
  core/common/src/main/java/alluxio/exception/status/AlluxioStatusException.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
Labels: API Change

#16161 Update PropertyKey.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#16218 [DOCFIX] Remove invalid example from Contributor-Tools
  docs/en/contributor/Contributor-Tools.md
Labels: Doc Fix

#16221 [DOCFIX] Add missing newline in User-CLI doc
  docs/en/operation/User-CLI.md
Labels: Doc Fix

#15444 Support Long type config values
  core/common/src/main/java/alluxio/conf/AlluxioConfiguration.java
  core/common/src/main/java/alluxio/conf/Configuration.java
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/conf/path/SpecificPathConfiguration.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelPool.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystemConfiguration.java
  core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
  job/server/src/main/java/alluxio/master/job/JobMaster.java
Labels: API Change

#16232 Allow dot in chown username or group
  shell/src/main/java/alluxio/cli/fs/command/ChownCommand.java
  shell/src/test/java/alluxio/cli/fs/command/ChownCommandTest.java
Labels: API Change

#15923 Cache BlockLocationPolicy for the current client
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java
  core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java
  core/client/fs/src/test/java/alluxio/client/block/BlockStoreClientTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriterTest.java
  core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
  core/server/worker/src/test/java/alluxio/worker/block/CacheRequestManagerTest.java
  core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java
  job/server/src/main/java/alluxio/job/util/JobUtils.java
  shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  tests/src/test/java/alluxio/client/fs/LocalFirstPolicyIntegrationTest.java
  tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java
Labels: priority-high, API Change

#16246 [DOCFIX] Clean up Eng Doc - remove HBase
  docs/cn/Overview.md
  docs/cn/compute/HBase.md
  docs/cn/deploy/Running-Alluxio-On-a-HA-Cluster.md
  docs/cn/overview/FAQ.md
  docs/cn/overview/Getting-Started.md
  docs/en/Overview.md
  docs/en/compute/HBase.md
  docs/en/deploy/Running-Alluxio-On-a-HA-Cluster.md
  docs/en/operation/Basic-Logging.md
Labels: Doc Fix

#16204 Refine add mPendingPaths in InodeSyncStream new type
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/master/file/MetadataSyncTraversalOrder.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
Labels: API Change

#16241 Avoid and dedup concurrent metadata sync
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/main/java/alluxio/master/file/MetadataSyncLockManager.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataConcurrentTest.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataMetricsTest.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTestBase.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
  core/server/master/src/test/java/alluxio/master/file/MetadataSyncLockManagerTest.java
  tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
Labels: API Change
