Repository Alluxio/alluxio, pull requests merged in 2022-05, with the labels that each got.

#15479 [DOCFIX] Update S3 API documentation
  docs/_data/table/s3-api-supported-actions.csv
  docs/_data/table/s3-api-supported-operations.csv
  docs/en/api/S3-API.md
Labels: Doc Fix

#15195 Add a reading buffer to local cache for tiny read
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: API Change

#14186 Support shadow cache with clock cuckoo filter
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
  core/client/fs/src/main/java/alluxio/client/file/cache/ClockCuckooShadowCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/MultipleBloomShadowCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/ShadowCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/ClockCuckooFilter.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/ConcurrentClockCuckooFilter.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/CuckooStatus.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/CuckooTable.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/CuckooUtils.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/ScopeEncoder.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/SegmentedLock.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/SimpleCuckooTable.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/SlidingWindowType.java
  core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/TagPosition.java
  core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/ClockCuckooShadowCacheManagerTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/MultipleBloomShadowCacheManagerTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/cuckoofilter/ConcurrentClockCuckooFilterTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/cuckoofilter/CuckooUtilsTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/cuckoofilter/ScopeEncoderTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/cuckoofilter/SegmentedLockTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/cuckoofilter/SimpleCuckooTableTest.java
  core/common/src/main/java/alluxio/client/file/cache/ShadowCacheType.java
  core/common/src/main/java/alluxio/collections/BitSet.java
  core/common/src/main/java/alluxio/collections/BuiltinBitSet.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/test/java/alluxio/collections/BuiltinBitSetTest.java
Labels: API Change

#15481 [DOCFIX] Update operation/troubleshooting chinese doc
  docs/cn/operation/Troubleshooting.md
Labels: Doc Fix

#15474 [DOCFIX] Update contributor/Building-Alluxio-From-Source Doc
  docs/cn/contributor/Building-Alluxio-From-Source.md
Labels: Doc Fix

#15462 [DOCFIX] Improve UFS ozone doc
  docs/cn/ufs/Ozone.md
  docs/en/ufs/Ozone.md
Labels: Doc Fix

#15516 [DOCFIX] Add newlines at the end of file
  docs/cn/contributor/Building-Alluxio-From-Source.md
  docs/cn/operation/Troubleshooting.md
Labels: Doc Fix

#15484 Expose RockDB metrics as Alluxio metrics
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  docs/en/operation/Metastore.md
Labels: API Change

#15521 Cleanup release branch
  docs/_config.yml
  integration/dataproc/alluxio-dataproc.sh
  integration/docker/Dockerfile
  integration/docker/Dockerfile-dev
  integration/emr/alluxio-emr.sh
  integration/kubernetes/helm-chart/alluxio/values.yaml
  integration/tools/pom.xml
  libexec/alluxio-config.sh
  pom.xml
  shaded/hadoop/pom.xml
  underfs/hdfs/pom.xml
Labels: POM Change

#15515 Add InstrumentedExecutorService for monitoring executor services
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/InstrumentedExecutorService.java
  core/common/src/main/java/alluxio/metrics/MaxReservoir.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/transport/src/main/proto/grpc/common.proto
  core/transport/src/main/proto/proto.lock
Labels: API Change

#15525 Expose RockDB metrics as Alluxio metrics
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  docs/en/operation/Metastore.md
Labels: API Change

#15527 Port changes of [#15515] to branch-2.7
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/InstrumentedExecutorService.java
  core/common/src/main/java/alluxio/metrics/MaxReservoir.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/transport/src/main/proto/grpc/common.proto
  core/transport/src/main/proto/proto.lock
Labels: API Change

#15530 Port changes of [#15204] to branch-2.7
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
  core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
Labels: API Change

#15523 Use unpooled wrapped buffer in remote block read
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Labels: API Change

#15518 Add microbench module skeleton
  assembly/client/pom.xml
  assembly/server/pom.xml
  microbench/build/checkstyle/suppressions.xml
  microbench/build/findbugs/findbugs-exclude.xml
  microbench/pom.xml
  microbench/readme.md
  microbench/src/main/java/alluxio/RpcUtilsBench.java
  pom.xml
  shaded/client/pom.xml
Labels: POM Change

#15574 [DOCFIX] Fix link in cn/operation/Troubleshooting.md
  docs/cn/operation/Troubleshooting.md
Labels: Doc Fix

#15572 Consolidate static analysis checks from microbench
  build/checkstyle/suppressions.xml
  build/findbugs/findbugs-exclude.xml
  microbench/build/checkstyle/suppressions.xml
  microbench/build/findbugs/findbugs-exclude.xml
  microbench/pom.xml
Labels: POM Change

#15541 Print worker for loadCommand while cache failed
  shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Labels: API Change

#15164 Support parse authorization headers for s3 proxy
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/pom.xml
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Exception.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/auth/Authenticator.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/auth/AwsAuthInfo.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/auth/PassAllAuthenticator.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/AuthorizationV4Validator.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/AwsCredential.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/AwsSignatureProcessor.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/SignatureInfo.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/StringToSignProducer.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/utils/AwsAuthV2HeaderParserUtils.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/utils/AwsAuthV4HeaderParserUtils.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/utils/AwsAuthV4QueryParserUtils.java
  core/server/proxy/src/test/java/alluxio/proxy/s3/signature/TestAWSV4Authenticator.java
  core/server/proxy/src/test/java/alluxio/proxy/s3/signature/TestAuthorizationV2HeaderParser.java
  core/server/proxy/src/test/java/alluxio/proxy/s3/signature/TestAuthorizationV4HeaderParser.java
  pom.xml
Labels: POM Change, API Change

#15598 Enable both file and table semantics to share distLoad code
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
  stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
  table/shell/src/main/java/alluxio/cli/table/command/LoadTableCommand.java
Labels: API Change

#15497 Clean Alluxio shell warnings
  shell/src/main/java/alluxio/cli/GetConf.java
  shell/src/main/java/alluxio/cli/LogLevel.java
  shell/src/main/java/alluxio/cli/RunOperation.java
  shell/src/main/java/alluxio/cli/TestRunner.java
  shell/src/main/java/alluxio/cli/Version.java
Labels: API Change
