Repository Alluxio/alluxio, pull requests merged in 2022-12, with the labels that each got.

#16601 Add property key to enable dora client read location policy
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#16602 Eliminate race condition in completempupload and support overwrite
  core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: API Change

#16610 Add unsafe flush option to embedded journal
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  docs/en/administration/Performance-Tuning.md
Labels: API Change

#16593 [DOCFIX]Modify some inappropriate descriptions in FAQ.md
  docs/cn/overview/FAQ.md
Labels: Doc Fix

#16609 Update raft group only on config change
  core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Labels: area-master, area-ha

#15856 Support TTL for synced inode
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
Labels: API Change

#16613 [DOCFIX] Fix some typos in doc
  docs/cn/operation/Journal.md
  docs/cn/operation/User-CLI.md
  docs/en/operation/User-CLI.md
Labels: Doc Fix

#16634 Support fuse test to test against S3
  integration/fuse/pom.xml
  integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractTest.java
  integration/fuse/src/test/java/alluxio/fuse/ufs/FuseFileSystemDataTest.java
  integration/fuse/src/test/java/alluxio/fuse/ufs/FuseFileSystemMetadataTest.java
Labels: POM Change

#16588 Improve the PollingMasterInquireClient logic
  core/common/src/main/java/alluxio/master/MasterInquireClient.java
  core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
  core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java
  minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
  shell/src/main/java/alluxio/cli/fs/command/LeaderCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
Labels: API Change

#16629 Fix fuse small doc
  docs/en/contributor/Contributor-Tools.md
Labels: Doc Fix

#16625 Remove unused Name#MASTER_EMBEDDED_JOURNAL_PROXY_HOST
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#14562 Add more cors config and make cors handle all http request
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/RestUtils.java
  core/server/common/src/main/java/alluxio/web/CORSFilter.java
  core/server/common/src/main/java/alluxio/web/HttpFilter.java
  core/server/common/src/main/java/alluxio/web/WebServer.java
  docs/_data/table/cn/common-configuration.yml
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/common-configuration.yml
Labels: API Change

#16577 Bump ratis version to 2.4.1
  core/server/common/pom.xml
Labels: POM Change

#16645 Upgrade protobuf to 3.19.6
  pom.xml
Labels: POM Change

#16542 Add a command to set DirectChildrenLoaded on dir
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java
  shell/src/main/java/alluxio/cli/fs/command/SyncDirNextTimeCommand.java
Labels: API Change

#16620 Add compression level option for RocksDB checkpoint
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/util/ParallelZipUtils.java
  core/server/common/src/main/java/alluxio/util/TarUtils.java
  core/server/common/src/test/java/alluxio/util/ParallelZipUtilsTest.java
  core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
  tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
Labels: API Change

#16653 Remove unused DefaultBlockWorker#UFS_BLOCK_OPEN_TIMEOUT_MS
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  docs/_data/table/cn/worker-configuration.yml
  docs/_data/table/en/worker-configuration.yml
  docs/_data/table/worker-configuration.csv
Labels: API Change

#16662 Enable default metadata cache for FUSE SDK
  core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java
  core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java
  core/client/fs/src/main/java/alluxio/client/file/MetadataCachingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
  core/client/fs/src/test/java/alluxio/client/file/MetadataCachingFileSystemTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  integration/fuse/bin/alluxio-fuse-sdk
  integration/fuse/src/main/java/alluxio/cli/command/metadatacache/AbstractMetadataCacheSubCommand.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
  integration/fuse/src/test/java/alluxio/fuse/AlluxioJnrFuseFileSystemTest.java
  integration/fuse/src/test/java/alluxio/fuse/cli/FuseShellTest.java
  integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractTest.java
  tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
  tests/src/test/java/alluxio/client/fuse/file/AbstractFuseFileStreamIntegrationTest.java
Labels: API Change
