Repository Alluxio/alluxio, pull requests merged in 2022-06, with the labels that each got.

#15640 Cleanup fs cli warnings
  core/common/src/main/java/alluxio/cli/AbstractShell.java
  shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java
  shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
  shell/src/main/java/alluxio/cli/fs/command/CopyToLocalCommand.java
  shell/src/main/java/alluxio/cli/fs/command/CpCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
  shell/src/main/java/alluxio/cli/fs/command/MasterInfoCommand.java
  shell/src/main/java/alluxio/cli/fs/command/PinCommand.java
  shell/src/main/java/alluxio/cli/fs/command/StatCommand.java
Labels: API Change

#15623 Clean up worker code
  core/server/worker/src/main/java/alluxio/underfs/WorkerUfsManager.java
  core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMapIterator.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java
  core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
  core/server/worker/src/main/java/alluxio/worker/block/ClientRWLock.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/FuseManager.java
  core/server/worker/src/main/java/alluxio/worker/block/PinListSync.java
  core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamCache.java
  core/server/worker/src/main/java/alluxio/worker/block/allocator/Allocator.java
  core/server/worker/src/main/java/alluxio/worker/block/allocator/GreedyAllocator.java
  core/server/worker/src/main/java/alluxio/worker/block/allocator/MaxFreeAllocator.java
  core/server/worker/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java
  core/server/worker/src/main/java/alluxio/worker/block/annotator/LRUAnnotator.java
  core/server/worker/src/main/java/alluxio/worker/block/annotator/SortedBlockSet.java
  core/server/worker/src/main/java/alluxio/worker/block/evictor/EvictionDirCandidates.java
  core/server/worker/src/main/java/alluxio/worker/block/evictor/Evictor.java
  core/server/worker/src/main/java/alluxio/worker/block/io/BlockStreamTracker.java
  core/server/worker/src/main/java/alluxio/worker/block/management/BlockManagementTaskResult.java
  core/server/worker/src/main/java/alluxio/worker/block/management/ManagementTaskCoordinator.java
  core/server/worker/src/main/java/alluxio/worker/block/reviewer/ProbabilisticBufferReviewer.java
  core/server/worker/src/main/java/alluxio/worker/block/reviewer/Reviewer.java
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/DelegationWriteHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
  core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockWriteHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/WriteRequest.java
  core/server/worker/src/test/java/alluxio/worker/grpc/BlockReadHandlerTest.java
Labels: API Change

#15632 Clean up block client code
  core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
  core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
  core/client/fs/src/main/java/alluxio/client/block/policy/BlockLocationPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBaseRandomPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/DeterministicHashPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/MostAvailableFirstPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/policy/SpecificHostPolicy.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/BufferCachingGrpcDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/DataMessageClientResponseObserver.java
  core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataMessageBlockingStream.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/SharedGrpcDataReader.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/test/java/alluxio/client/block/BlockStoreClientTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBaseRandomPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/DeterministicHashPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/MostAvailableFirstPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/RoundRobinPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/policy/SpecificHostPolicyTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
  core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
  core/common/src/main/java/alluxio/grpc/DataMessageMarshallerProvider.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/server/worker/src/main/java/alluxio/worker/grpc/DelegationWriteHandler.java
  job/server/src/test/java/alluxio/job/plan/replicate/SetReplicaDefinitionReplicateTest.java
  stress/shell/src/main/java/alluxio/stress/cli/client/ClientIOWritePolicy.java
  tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java
Labels: API Change

#15659 Move static config functions to from ConfigurationUtils to Configuration
  core/common/src/main/java/alluxio/ClientContext.java
  core/common/src/main/java/alluxio/conf/Configuration.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
Labels: API Change

#15666 Fix the vulnerability caused by xstream
  pom.xml
Labels: POM Change

#15667 Fix the security vulernability caused by junit's temp folder
  pom.xml
Labels: POM Change

#15645 Support Stat command output fileid by formatted argument
  shell/src/main/java/alluxio/cli/fs/command/StatCommand.java
Labels: API Change

#15676 Port changes of [#15110] to branch-2.6
  core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/proto.lock
  docs/en/operation/Journal.md
  shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Labels: API Change

#15665 Fix the security vulnerability from jackcon databind
  core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadResult.java
  pom.xml
Labels: POM Change

#15668 Fix the vulnerbility caused by jetty-webapp
  pom.xml
Labels: POM Change

#15673 Remove ClientContext.mClusterConfHash
  core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
  core/common/src/main/java/alluxio/ClientContext.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
Labels: API Change

#15565 Support stat a file through fileId
  shell/src/main/java/alluxio/cli/fs/command/StatCommand.java
Labels: API Change

#15704 Add missing commit for formatting screen output
  core/transport/src/main/proto/grpc/job_master.proto
  job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
  job/common/src/main/java/alluxio/job/ProtoUtils.java
  job/common/src/main/java/alluxio/job/wire/CmdStatusBlock.java
  job/common/src/main/java/alluxio/job/wire/SimpleJobStatusBlock.java
  job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
  job/server/src/main/java/alluxio/master/job/tracker/CmdRunAttempt.java
  job/server/src/main/java/alluxio/master/job/tracker/DistLoadCliRunner.java
  job/server/src/main/java/alluxio/master/job/tracker/MigrateCliRunner.java
  job/server/src/test/java/alluxio/master/job/tracker/CliRunnerTest.java
  job/server/src/test/java/alluxio/master/job/tracker/CmdJobTrackerTest.java
  shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
  shell/src/main/java/alluxio/cli/fs/command/GetCmdStatusCommand.java
  shell/src/main/java/alluxio/cli/job/command/GetCmdStatusCommand.java
  shell/src/main/java/alluxio/cli/util/DistributedCommandUtil.java
  stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
  tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
  tests/src/test/java/alluxio/client/cli/job/GetCmdStatusCommandTest.java
Labels: API Change

#15712 Refactor UnderFileSystemConfiguration
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/conf/path/PrefixPathConfiguration.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystemConfiguration.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystemFactoryRegistry.java
  core/common/src/test/java/alluxio/conf/PropertyKeyTest.java
  core/common/src/test/java/alluxio/underfs/UnderFileSystemConfigurationTest.java
  core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
  core/server/master/src/test/java/alluxio/master/file/meta/LazyUfsBlockLocationCacheTest.java
  core/server/worker/src/main/java/alluxio/underfs/WorkerUfsManager.java
  integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
  job/server/src/main/java/alluxio/underfs/JobUfsManager.java
  shell/src/main/java/alluxio/cli/ValidateHdfsMount.java
  stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
  tests/src/test/java/alluxio/server/ft/journal/ufs/UfsConfigurationJournalTest.java
  tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystemFactory.java
  underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
Labels: API Change

#15648 Support specify role for a target when execute logLevel command
  shell/src/main/java/alluxio/cli/LogLevel.java
Labels: API Change

#15724 Shade aarch64 netty epoll lib
  shaded/client/pom.xml
Labels: POM Change

#15727 Bump junit version again to fix the security vulerability
  pom.xml
Labels: POM Change

#15698 Create automatic backup when shutting down Alluxio master
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
  core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
  docs/en/operation/Journal.md
  minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
  tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
Labels: API Change

#15735 Port changes of [#15698] to branch-2.6
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
  core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
  docs/en/operation/Journal.md
  minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
  tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
Labels: API Change

#15495 Add UfsIOManager to control IO throughput with UFS
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/worker/src/main/java/alluxio/worker/block/UfsIOManager.java
  core/server/worker/src/test/java/alluxio/worker/block/UfsIoManagerTest.java
Labels: API Change

#15736 Set direct_io as the default fuse mount option for JNIFuse
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  docs/en/api/POSIX-API.md
  docs/en/deploy/Running-Alluxio-On-Docker.md
  docs/en/deploy/Running-Alluxio-On-Kubernetes.md
  integration/kubernetes/helm-chart/alluxio/values.yaml
Labels: API Change

#15749 Fix documentation surrounding `backup` command
  docs/en/operation/Admin-CLI.md
  docs/en/operation/Journal.md
  shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Labels: API Change

#15753 Port changes of [#15749] to branch-2.6
  docs/en/operation/Admin-CLI.md
  docs/en/operation/Journal.md
  shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Labels: API Change

#15716 Optimize the access speed of the inAlluxioData UI page
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Labels: API Change

#15423 Add cache for CapacityBaseRandomPolicy
  core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBaseRandomPolicy.java
  core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBaseRandomPolicyTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#15503 Allow master node RocksDB to be configured using configuration files
  .gitignore
  conf/rocks-block-bloom.ini.template
  conf/rocks-block.ini.template
  conf/rocks-inode-bloom.ini.template
  conf/rocks-inode.ini.template
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/master/metastore/rocks/DataBlockIndexType.java
  core/common/src/main/java/alluxio/master/metastore/rocks/IndexType.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
  core/server/master/src/test/java/alluxio/master/metastore/BlockMetaStoreTest.java
  core/server/master/src/test/java/alluxio/master/metastore/InodeStoreTest.java
  core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksStoreTest.java
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
  docs/en/operation/Metastore.md
  pom.xml
  shell/src/test/java/alluxio/cli/bundler/command/CollectConfCommandTest.java
Labels: POM Change, API Change

#15738 Add RocksDB and inode jmh bench
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  microbench/pom.xml
  microbench/src/main/java/alluxio/inode/InodeBenchBase.java
  microbench/src/main/java/alluxio/inode/InodeBenchRead.java
  microbench/src/main/java/alluxio/inode/InodeBenchWrite.java
  microbench/src/main/java/alluxio/inode/RocksBenchBase.java
  microbench/src/main/java/alluxio/inode/RocksBenchConfig.java
  microbench/src/main/java/alluxio/inode/RocksBenchRead.java
  microbench/src/main/java/alluxio/inode/RocksBenchReadWrite.java
  microbench/src/main/java/alluxio/inode/RocksBenchWrite.java
Labels: POM Change
