Repository Alluxio/alluxio, pull requests merged in 2022-03, with the labels that each got.

#15074 Increase block-read timeout duration to 5mins
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#14920 Use the s3a as property key name prefix for s3 compatible object stores
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/test/java/alluxio/conf/CredentialConfigItemsTest.java
  core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  core/server/common/src/test/java/alluxio/RpcSensitiveConfigMaskTest.java
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/common-configuration.yml
  docs/cn/compute/Deep-Learning.md
  docs/cn/compute/Tensorflow.md
  docs/cn/core-services/Unified-Namespace.md
  docs/cn/deploy/Running-Alluxio-On-Kubernetes.md
  docs/cn/operation/User-CLI.md
  docs/cn/overview/Getting-Started.md
  docs/cn/ufs/CephObjectStorage.md
  docs/cn/ufs/Minio.md
  docs/cn/ufs/S3.md
  docs/en/compute/Tensorflow.md
  docs/en/core-services/Unified-Namespace.md
  docs/en/deploy/Running-Alluxio-On-Kubernetes.md
  docs/en/operation/User-CLI.md
  docs/en/overview/Getting-Started.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/Minio.md
  docs/en/ufs/S3.md
  integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
  integration/vagrant/ansible/roles/ufs_s3/files/config_alluxio.sh
Labels: API Change

#15075 Restore stream in/out timeouts to a sane value
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#15098 Update Hub elasticsearch field names and add dev flag for scripts
  hub/transport/src/main/proto/grpc/rest.proto
  integration/hub-elastic/README.md
  integration/hub-elastic/logstash/logstash-start.sh
  integration/hub-elastic/logstash/logstash.conf
  integration/hub-elastic/metricbeat/metricbeat-start.sh
  integration/hub-elastic/metricbeat/metricbeat.yml
Labels: area-hub

#15065 Add a configuration to set ufs fetch timeout
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
Labels: API Change

#15110 Support bypassing backup delegation via shell switch
  core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/proto.lock
  docs/en/operation/Journal.md
  shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Labels: API Change

#15128 [DOCFIX] Fix job service configuration doc
  docs/_data/table/en/env_vars.yml
  docs/cn/operation/Configuration.md
Labels: Doc Fix

#15091 Replace PowerMock with Mockito in LogLevelTest
  pom.xml
  shell/pom.xml
  shell/src/test/java/alluxio/cli/LogLevelTest.java
Labels: POM Change

#15111 Improve state-lock acquisition defaults
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  tests/src/test/java/alluxio/client/cli/fsadmin/BackupCommandStateLockingIntegrationTest.java
Labels: API Change

#15129 Remove fuse default_permission
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: API Change

#15106 Fix DistribtuedLoad CLI Output and dump failed files to local csv
  shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
  shell/src/main/java/alluxio/cli/fs/command/job/JobAttempt.java
  tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
Labels: API Change

#15136 Fix typo
  docs/en/contributor/Contributor-Getting-Started.md
Labels: Doc Fix

#15112 [DOCFIX] Update k8s doc
  docs/en/deploy/Running-Alluxio-On-Kubernetes.md
Labels: Doc Fix

#15143 Support read-write open through FUSE for specific files
  core/client/fs/src/main/java/alluxio/client/file/SeekableAlluxioFileOutStream.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
  tests/src/test/java/alluxio/client/fs/io/SeekableAlluxioFileOutStreamIntegrationTest.java
  tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
  tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
Labels: API Change

#15145 Use perl instead of sed for Hub Elastic helper scripts
  integration/hub-elastic/filebeat/filebeat-start.sh
  integration/hub-elastic/logstash/logstash-start.sh
  integration/hub-elastic/metricbeat/metricbeat-start.sh
Labels: area-hub

#15167 Fix the code example in the document of fs-api
  docs/en/api/FS-API.md
Labels: Doc Fix

#15120 Include rocksdb into shaded client jar
  shaded/client/pom.xml
Labels: POM Change

#15177 Correct CSI Driver apiVersion and rbac namespace
  integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
  integration/kubernetes/helm-chart/alluxio/Chart.yaml
  integration/kubernetes/helm-chart/alluxio/templates/csi/controller-rbac.yaml
  integration/kubernetes/helm-chart/alluxio/templates/csi/driver.yaml
Labels: area-k8s

#15127 Remove PropertyKey.Template.MASTER_JOURNAL_UFS_OPTION
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
Labels: API Change

#15201 Handle null in PropertyKey.parseValue
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#15218 Fix docGen and update config/metrics
  docs/_data/table/cluster-management-configuration.csv
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/common-configuration.yml
  docs/_data/table/en/master-configuration.yml
  docs/_data/table/en/master-metrics.yml
  docs/_data/table/en/user-configuration.yml
  docs/_data/table/master-configuration.csv
  docs/_data/table/master-metrics.csv
  docs/_data/table/security-configuration.csv
  docs/_data/table/user-configuration.csv
  docs/_data/table/worker-configuration.csv
Labels: Doc Fix

#15191 Unmount corrupted folder is case nodeserver restarted
  integration/docker/csi/alluxio/nodeserver.go
Labels: area-k8s

#15224 Fix Caching doc typo
  docs/cn/core-services/Caching.md
Labels: Doc Fix

#15184 Improve fuse umount
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  integration/docker/entrypoint.sh
  integration/fuse/bin/alluxio-fuse
  integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Labels: API Change

#15207 Allow string values when setting AlluxioConfiguration
  core/common/src/main/java/alluxio/cli/ValidationToolRegistry.java
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
  core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  core/common/src/test/java/alluxio/underfs/UnderFileSystemConfigurationTest.java
  core/server/master/src/main/java/alluxio/web/MasterWebServer.java
  core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalConfTest.java
  core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java
  integration/tools/validation/src/main/java/alluxio/cli/ClusterConfConsistencyValidationTask.java
  integration/tools/validation/src/main/java/alluxio/cli/SshValidationTask.java
  underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: API Change

#15166 Add timeout logic to local block reading/writing
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/worker/block/io/TimeBoundBlockReader.java
  core/common/src/main/java/alluxio/worker/block/io/TimeBoundBlockWriter.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
Labels: API Change
