Repository Alluxio/alluxio, pull requests merged in 2023-10, with the labels that each got.

#18193 Add user/password support for etcd
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-feature

#18233 Add membership module doc
  docs/_data/menu-en.yml
  docs/en/operation/Alluxio-Membership-Management.md
Labels: type-docs

#18219 Fail directly if sudo needs password
  dora/core/common/src/main/java/alluxio/util/EnvironmentUtils.java
Labels: type-bug

#18189 Fix FileOutStreamIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/fs/io/AbstractFileOutStreamIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/io/FileOutStreamIntegrationTest.java
Labels: type-code-quality

#18162 Add UT to DefaultPageMetaStore.commitFile
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/DefaultPageMetaStoreTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/QuotaPageMetaStoreTest.java
Labels: type-code-quality

#18245 Improve list files RESTful API providing more useful info
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/ResponseFileInfo.java
  dora/tests/integration/src/test/java/alluxio/server/worker/WorkerHttpServerIntegrationTest.java
Labels: type-feature

#18163 Fix the UfsBaseFileSystemTest
  dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
Labels: type-code-quality

#18244 Disable UFS fallback in DoraFileSystemIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
Labels: type-code-quality

#18213 Fix Integration tests framework and DoraFileSystemIntegrationTest
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  dora/minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
Labels: type-bug, type-code-quality

#18217 Fix reconnect logic of servicediscoveryrecipe
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
Labels: type-bug

#18248 Avoid creating FileSystem instance many times in HttpServerHandler
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerInitializer.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Labels: type-bug

#18247 Remove MigrateIntegrationTest and PersistIntegrationTest
  dora/tests/integration/src/test/java/alluxio/job/plan/migrate/MigrateIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/job/plan/persist/PersistIntegrationTest.java
Labels: type-code-quality

#18243 Fix FileSystemBlockLocationIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/hadoop/FileSystemBlockLocationIntegrationTest.java
Labels: type-bug, type-code-quality

#18053 Support set/get xattr
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  dora/core/common/src/main/java/alluxio/util/io/FileUtils.java
  dora/core/common/src/test/java/alluxio/underfs/MockObjectUnderFileSystem.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/ListMultipartUploadsResult.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/tests/integration/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  dora/underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
  dora/underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-feature

#18251 Remove a few deprecated integration tests
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/BackupCommandStateLockingIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/command/ReportEmbeddedJournalIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/metrics/MetricsCommandIntegrationTest.java
Labels: type-code-quality

#18246 Support StressWorkerBench using consistent hash policy
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchMode.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchParameters.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-feature

#18178 Fix FileInStreamIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/fs/io/FileInStreamIntegrationTest.java
Labels: type-code-quality

#18253 Support Mkdir/CreateFile with configured default umask in HDFS API
  core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
  tests/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java
Labels: type-bug

#18255 Add a property key to control if alluxio write the xattr to UFS
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
Labels: type-bug

#18235 Use linked hash set to keep sequence when picking multiple worker
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
Labels: type-feature

#18224 Add ser/de support for JSON or WorkerIdentity
  dora/core/common/src/main/java/alluxio/wire/WorkerIdentity.java
  dora/core/common/src/test/java/alluxio/wire/WorkerIdentityTest.java
Labels: type-feature

#18262 Get User/Group/Permission of existed objects in OSS ufs
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-bug

#18252 Refactor handling of java opts env vars in cli
  cli/src/alluxio.org/cli/cmd/cache/format.go
  cli/src/alluxio.org/cli/cmd/conf/get.go
  cli/src/alluxio.org/cli/cmd/exec/test_basic_io.go
  cli/src/alluxio.org/cli/cmd/exec/test_hdfs_mount.go
  cli/src/alluxio.org/cli/cmd/exec/test_worker.go
  cli/src/alluxio.org/cli/cmd/generate/doc_tables.go
  cli/src/alluxio.org/cli/cmd/initiate/validate.go
  cli/src/alluxio.org/cli/cmd/journal/format.go
  cli/src/alluxio.org/cli/cmd/journal/read.go
  cli/src/alluxio.org/cli/env/command.go
  cli/src/alluxio.org/cli/env/env.go
  cli/src/alluxio.org/cli/env/env_vars.go
  cli/src/alluxio.org/cli/env/process.go
  cli/src/alluxio.org/cli/processes/common.go
  cli/src/alluxio.org/cli/processes/job_master.go
  cli/src/alluxio.org/cli/processes/job_worker.go
  cli/src/alluxio.org/cli/processes/master.go
  cli/src/alluxio.org/cli/processes/proxy.go
  cli/src/alluxio.org/cli/processes/worker.go
  cli/src/alluxio.org/cli/processes/worker_test.go
Labels: type-bug

#18210 Use new worker id on worker and client
  common/transport/src/main/proto/grpc/block_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/BlockWorkerInfo.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashProviderTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/LocalWorkerPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/util/ClientTestUtils.java
  dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/WorkerServiceEntity.java
  dora/core/common/src/main/java/alluxio/wire/WorkerIdentity.java
  dora/core/common/src/main/java/alluxio/wire/WorkerInfo.java
  dora/core/common/src/main/java/alluxio/worker/DataWorker.java
  dora/core/common/src/test/java/alluxio/membership/ServiceEntityTest.java
  dora/core/common/src/test/java/alluxio/wire/WorkerIdentityTestUtils.java
  dora/core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
  dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/grpc/DoraWorkerClientServiceHandlerTest.java
  dora/job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
  dora/job/server/src/test/java/alluxio/job/plan/SelectExecutorsTest.java
  dora/job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java
  dora/job/server/src/test/java/alluxio/job/plan/persist/PersistDefinitionTest.java
  dora/shell/src/test/java/alluxio/cli/LogLevelTest.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-feature

#18222 Check cluster ufs version in getClusterConf
  core/common/src/main/java/alluxio/conf/Configuration.java
Labels: type-bug

#18238 Check load meta option at worker
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-debt

#18264 [SMALLFIX] Enable WorkerMetadataSyncIntegrationTest
  dora/tests/integration/src/test/java/alluxio/server/worker/WorkerMetadataSyncIntegrationTest.java
Labels: type-code-quality

#18272 [SMALLFIX] Enable one UT case in OutStreamTest
  dora/integration/fuse/src/test/java/alluxio/fuse/ufs/stream/OutStreamTest.java
Labels: type-code-quality

#18143 Change CosNUnderFileSystemFactory implementation UnderFileSystemFactory
  underfs/cosn/src/main/java/alluxio/underfs/cosn/CosNUnderFileSystemFactory.java
Labels: area-ufs, type-bug

#18254 Add RESTful API for distributed load
  dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UfsFileStatusIterator.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadOptions.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-feature

#18284 Revert "Add RESTful API for distributed load"
  dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UfsFileStatusIterator.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadOptions.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-bug

#18283 Remove test file
  test_file
Labels: type-bug

#18289 Load ufs path directly
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandWithVirtualBlockIntegrationTest.java
Labels: type-feature, breaks-compatibility

#18294 Create locationCommandTest and fix some IntegretionTest bugs
  dora/shell/src/main/java/alluxio/cli/fs/command/LocationCommand.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/AbstractDoraShellIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/AbstractShellIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/CatCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/ChecksumCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraFileLocationIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
Labels: type-code-quality

#18297 Fix load command ufs string
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/DoraLoadJobTest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Labels: type-bug

#18278 Fix FileSystemShellUtilsTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java
Labels: type-code-quality

#18290 [SMALLFIX] Remove OldLoadCommandIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/OldLoadCommandIntegrationTest.java
Labels: type-code-quality

#18280 [SMALLFIX] Delete JobServiceFaultToleranceShellTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/JobServiceFaultToleranceShellTest.java
Labels: type-code-quality

#18302 Add name to artifacts metadata
  dev/scripts/src/alluxio.org/build/cmd/docker.go
Labels: type-devops

#18295 Implement HDFS list status iterator
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTestBase.java
Labels: type-feature

#18291 Add RESTful API for distributed load
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadOptions.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-feature

#18307 Add multi-dimensional metrics system
  .gitignore
  dora/core/common/pom.xml
  dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
  dora/core/server/common/src/main/java/alluxio/web/WebServer.java
  dora/core/server/master/src/main/java/alluxio/master/AlluxioMaster.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  pom.xml
Labels: type-feature, area-metrics

#18182 Change UfsManager key to not rely on properties
  dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
  dora/core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-performance

#18315 Use new UfsManager.get() avoid creating conf instances every time
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
Labels: type-bug

#18292 [SMALLFIX] Remove UnsetTtlTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/UnsetTtlTest.java
Labels: type-code-quality

#18275 Remove restriction in overwriting worker info within join logic
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#18317 Improve cold read performance by prefetching data on workers
  common/transport/src/main/proto/grpc/block_worker.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/test/java/alluxio/client/file/PositionReadFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: type-feature

#18318 Add prefetch cache policy
  dora/core/client/fs/src/main/java/alluxio/client/file/AdaptivePrefetchCachePolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/BasePrefetchCachePolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/PrefetchCachePolicy.java
  dora/core/client/fs/src/test/java/alluxio/client/file/PositionReadFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-feature

#18312 Add getStatus RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/tests/integration/src/test/java/alluxio/server/worker/WorkerHttpServerIntegrationTest.java
Labels: type-feature

#18322 Fix MemoryPageStore error on commit() and clear cache on close()
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
Labels: type-bug

#18313 Bring back integration tests
  .github/workflows/java8_integration_tests.yml
  .github/workflows/java8_integration_tests_ft.yml
  .github/workflows/java8_integration_tests_webui.yml
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/CatCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraFileLocationIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/command/ReportCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraS3PathIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/FileSystemUtilsIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/io/FileInStreamIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/FuseFileSystemMetadataTest.java
  dora/tests/integration/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/rest/MultipartUploadTest.java
  dora/tests/integration/src/test/java/alluxio/client/rest/S3ObjectTest.java
  dora/tests/integration/src/test/java/alluxio/server/configuration/ConfigCheckerIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/web/WebServerIntegrationTest.java
Labels: type-bug

#17856 Fix to support update new key
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterConfigClient.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/UpdateConfIntegrationTest.java
Labels: type-feature

#18268 Remove WorkerFuseIntegrationTest
  dora/tests/integration/src/test/java/alluxio/server/worker/WorkerFuseIntegrationTest.java
Labels: type-code-quality

#18277 Delete useless UnderFileSystemAlluxioTest
  dora/integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
Labels: type-debt

#18296 Update worker api support for load multi replicas
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/grpc/file_system_master.proto
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadDataSubTask.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadMetadataSubTask.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadSubTask.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-feature

#18319 Add Rust toolchain to CI
  dev/github/Dockerfile-jdk11
  dev/github/Dockerfile-jdk17
  dev/github/Dockerfile-jdk8
  native/rust/archetype/pom.xml
Labels: area-build, type-devops

#18311 Add regx pattern file filter for distributed load
  cli/src/alluxio.org/cli/cmd/job/load.go
  common/transport/src/main/proto/grpc/file_system_master.proto
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/DatePredicate.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/FileNamePatternPredicate.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/FilePredicate.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/TimePredicate.java
  dora/core/server/master/src/main/resources/META-INF/services/alluxio.master.predicate.FilePredicateFactory
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/DoraLoadJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadOptions.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandWithVirtualBlockIntegrationTest.java
Labels: type-feature

#18325 Create DoraLsCommandIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/AbstractDoraFileSystemShellTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLsCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraMkdirCommandIntegrationTest.java
Labels: type-code-quality

#18333 [SMALLFIX] Extract create UfsBaseFileSystem for extension
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Labels: type-code-quality

#18323 Fix a buffer memory leak in NettyReadHandlerStateMachine
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyReadHandlerStateMachine.java
Labels: type-bug

#18287 [SMALLFIX] Remove LeaderCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/LeaderCommandIntegrationTest.java
Labels: type-code-quality

#18303 Fix cosn ufs cannot find class
  underfs/cosn/pom.xml
Labels: type-code-quality

#18208 Fix cacheMissPercentage metric
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSyncHelper.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/io/MetricAccountingBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedUfsBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/UfsBlockReadOptions.java
  core/server/worker/src/test/java/alluxio/worker/page/PagedBlockReaderTest.java
Labels: type-bug

#17002 Bump hadoop version to 3.3.4
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
  docs/cn/contributor/Building-Alluxio-From-Source.md
  docs/cn/ufs/HDFS.md
  docs/en/contributor/Building-Alluxio-From-Source.md
  docs/en/ufs/COSN.md
  docs/en/ufs/HDFS.md
  integration/tools/pom.xml
  pom.xml
  shaded/hadoop/pom.xml
  underfs/abfs/pom.xml
  underfs/adl/pom.xml
  underfs/hdfs/pom.xml
  underfs/wasb/pom.xml
Labels: POM Change, type-debt, API Change, dependencies

#18320 Update Load replica job
  common/transport/src/main/proto/grpc/block_worker.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadDataSubTask.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadMetadataSubTask.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadSubTask.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/RoundRobinWorkerAssignPolicy.java
  dora/core/server/master/src/main/java/alluxio/master/job/WorkerAssignPolicy.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/DoraLoadJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
Labels: type-feature

#18340 Fix the time check logic for judging stale client channels to be inac…
  dora/core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java
Labels: type-bug

#18347 Fix isAllPageCached
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug
