Repository Alluxio/alluxio, pull requests merged in 2023-09, with the labels that each got.

#18080 Fix info collect not working bug
  cli/src/alluxio.org/cli/cmd/info/collect.go
  dora/shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
  dora/shell/src/main/java/alluxio/cli/bundler/command/AbstractCollectInfoCommand.java
  dora/shell/src/test/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommandTest.java
  dora/shell/src/test/java/alluxio/cli/bundler/command/CollectConfCommandTest.java
  dora/shell/src/test/java/alluxio/cli/bundler/command/CollectEnvCommandTest.java
  dora/shell/src/test/java/alluxio/cli/bundler/command/CollectLogCommandTest.java
Labels: type-bug

#18032 Improve pom module name
  dora/tests/integration/pom.xml
  dora/tests/testcontainers/pom.xml
Labels: type-code-quality

#18089 Check UFS rename operation result and throw exception if failed
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-code-quality

#18033 Remove tiered identity
  common/transport/src/main/proto/grpc/common.proto
  common/transport/src/main/proto/proto.lock
  dora/core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/util/BlockLocationUtils.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/LocalWorkerPolicy.java
  dora/core/client/fs/src/test/java/alluxio/client/block/util/BlockLocationUtilsTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashProviderTest.java
  dora/core/client/fs/src/test/java/alluxio/client/util/ClientTestUtils.java
  dora/core/common/src/main/java/alluxio/Constants.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
  dora/core/common/src/main/java/alluxio/network/TieredIdentityFactory.java
  dora/core/common/src/main/java/alluxio/util/TieredIdentityUtils.java
  dora/core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
  dora/core/common/src/main/java/alluxio/wire/TieredIdentity.java
  dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
  dora/core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  dora/core/common/src/test/java/alluxio/conf/PropertyKeyTest.java
  dora/core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
  dora/core/common/src/test/java/alluxio/wire/TieredIdentityTest.java
  dora/core/common/src/test/java/alluxio/wire/WorkerNetAddressTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
  dora/core/server/worker/src/test/java/alluxio/worker/block/BlockMasterClientTest.java
  dora/job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/LocalFirstPolicyIntegrationTest.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-debt

#18090 Add hadoop3 jar to the artifacts
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Labels: type-ease-of-use

#18093 Fix alluxio-fuse when mounting to /tmp
  dora/integration/fuse/bin/alluxio-fuse
Labels: type-bug

#18096 Fix issue when starting master with STATIC membership type
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Labels: type-bug

#18100 Fix static shaded client version in dora example pom
  dora/examples/pom.xml
Labels: type-bug

#18105 Avoid using bash -c in checking Java version in Golang CLI
  cli/src/alluxio.org/cli/env/env.go
Labels: type-bug

#18106 [SMALLFIX] Make DoraCacheFileSystem.convertUfsPathToAlluxioPath public
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
Labels: type-ease-of-use

#18087 [DOCFIX] Remove indentation for sitemap
  docs/_includes/sitemap.html
Labels: type-docs

#18109 Fix a deadlock in FileSystemContext
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Labels: type-bug

#18104 Handle the reserved character ':' for HTTP server
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-feature

#18112 [DOCFIX] Remove zookeeper doc
  docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
Labels: type-docs

#18113 [DOCFIX] Update journal command doc
  docs/en/operation/User-CLI.md
Labels: type-docs

#18108 Return FileNotFound when a file is being create/write
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#18114 Add isReadOnly() for FuseFileStream
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReadOrOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
Labels: type-feature

#18091 Handle any version string for summarycommandtest
  shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
Labels: type-bug

#18115 Run launch-process-bash script
  integration/docker/entrypoint.sh
Labels: type-bug

#18099 Add a config to turn on/off the sdk cache fallback
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-devops

#17878 Add dora worker metrics at http requests
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-devops

#18098 Fix the array out of bound exception in presto
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Labels: type-bug

#17848 Add dora worker metadata metrics
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-devops

#18070 Change metric type of LocalCacheState from counter to gauge
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-debt

#18097 Change name of NoopMembershipManager
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/membership/MasterMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/MembershipType.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
Labels: type-ease-of-use

#17474 Provide a way to support listening only for modified PropertyKey
  core/common/src/main/java/alluxio/conf/Reconfigurable.java
  core/common/src/main/java/alluxio/conf/ReconfigurableRegistry.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatTimer.java
  core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
Labels: type-feature

#17982 Support read bytebuffer for non ByteBufferReadable input stream
  core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsInputStream.java
Labels: type-debt

#18119 Revert "Change metric type of LocalCacheState from counter to gauge"
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-bug

#17479 Refactor Netty reader handler
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/network/protocol/databuffer/DataFileChannel.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockReadRequest.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyReadHandlerStateMachine.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTask.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/ReadRequest.java
  dora/core/server/worker/src/test/java/alluxio/worker/netty/NettyReadHandlerStateMachineTest.java
Labels: type-performance

#18120 Refactor Netty read handler
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockReadRequest.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/ReadRequest.java
Labels: type-debt

#17735 Retry requiring the buffer when there is insufficient resources
  core/common/src/main/java/alluxio/network/protocol/databuffer/NioDirectBufferPool.java
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
Labels: type-code-quality

#18029 Implement per-thread cache context
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/context/CachePerThreadContext.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Labels: type-feature

#18122 [DOCFIX] Remove outdated limitation in QuickStart doc
  docs/en/deploy/Get-Started.md
Labels: type-docs

#18079 Change Benchmark's `runClass` to `exec class`
  dora/job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
Labels: type-bug

#18123 Fix cli binary name for arm
  build/cli/build-cli.sh
  dev/scripts/src/alluxio.org/build/profiles.yml
Labels: type-bug

#18121 Remove hostname from metrics key
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  dora/core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
Labels: type-debt

#18128 [DOCFIX] Update bin/alluxio usage format
  cli/src/alluxio.org/cli/launch/launch.go
  docs/en/api/REST-API.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/deploy/Get-Started.md
  docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
  docs/en/operation/Configuration.md
  docs/en/operation/Logging.md
  docs/en/reference/Troubleshooting.md
Labels: type-docs

#18129 Make fuse max reader concurrency configurable
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/integration/fuse/src/main/java/alluxio/fuse/lock/FuseReadWriteLockManager.java
Labels: type-feature

#18136 [DOCFIX] Update bin/alluxio usage in ufs/compute
  docs/en/compute/Hadoop-MapReduce.md
  docs/en/compute/Hive.md
  docs/en/compute/Presto.md
  docs/en/compute/Spark.md
  docs/en/compute/Tensorflow.md
  docs/en/compute/Trino.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/Storage-Overview.md
Labels: type-docs

#18139 Support accessing OSS with proxy
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-feature

#18142 Fix default value of proxy host
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-bug

#18140 Extract path resolution in DoraCacheFS into static utility
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyHandler.java
Labels: type-code-quality

#18138 [DOCFIX] Fix check-docs errMsg bug
  dev/scripts/src/alluxio.org/check-docs/main.go
Labels: type-docs

#18146 Move path resolution logic and fix a bug
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/common/src/main/java/alluxio/util/io/PathUtils.java
Labels: type-code-quality

#18145 Improve dora stream error handling
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
Labels: type-code-quality

#18047 Add JSON-style reports
  dora/core/common/src/main/java/alluxio/wire/MountPointInfo.java
  dora/shell/pom.xml
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceOutput.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/MetricsCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/MetricsOutput.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/SummaryOutput.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/UfsCommand.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/MetricsCommandTest.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
Labels: type-feature

#18133 Check for more results when the filtered result is empty
  core/server/master/src/main/java/alluxio/master/job/FileIterable.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/LoadJobTest.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/LoadTestUtils.java
Labels: type-bug

#18017 Write to UFS when failed to write to Alluxio Worker
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
Labels: type-code-quality

#18153 Improve distributed load
  cli/src/alluxio.org/cli/cmd/job/load.go
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/grpc/file_system_master.proto
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Labels: type-feature

#18135 Recover the ufs uri support
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/FileSystem.java
  dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/DoraS3PathIntegrationTest.java
Labels: type-debt

#18130 [DOCFIX] Update docker documentation
  docs/_data/menu-en.yml
  docs/en/Overview.md
  docs/en/deploy/Install-Alluxio-Cluster-with-Docker.md
Labels: type-docs

#18147 Add a test to monitor the distribution of vnode to physical node
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashProviderTest.java
Labels: type-code-quality

#18151 Add CLI tools for debugging and analyzing caching issues
  cli/src/alluxio.org/cli/cmd/fs/check_cached.go
  cli/src/alluxio.org/cli/cmd/fs/consistant_hash.go
  cli/src/alluxio.org/cli/cmd/fs/fs.go
  cli/src/alluxio.org/cli/cmd/fs/location.go
  dora/core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/shell/src/main/java/alluxio/cli/fs/command/CheckCachedCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/ConsistentHashCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/FileLocation.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LocationCommand.java
Labels: type-ease-of-use

#18159 Parse JSON-style reports in golang side
  cli/src/alluxio.org/cli/cmd/info/report.go
  cli/src/alluxio.org/cli/env/command.go
Labels: type-ease-of-use

#18155 Add datePredicate
  dora/core/server/master/src/main/java/alluxio/master/predicate/DatePredicate.java
  dora/core/server/master/src/main/resources/META-INF/services/alluxio.master.predicate.FilePredicateFactory
  dora/core/server/master/src/test/java/alluxio/master/predicate/DatePredicateTest.java
Labels: type-feature

#18149 Add throughput distribution and coarse datapoints for StressWorkerBench
  dora/job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchCoarseDataPoint.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchCoarseDataPointDeserializer.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPoint.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPointDeserializer.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchSummary.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchTaskResult.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-feature

#17985 Add Unit Test for OSS, OBS and GCS
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
  dora/underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSOutputStreamTest.java
  dora/underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSPositionReaderTest.java
  dora/underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemFactoryTest.java
  dora/underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemTest.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystemFactory.java
  dora/underfs/obs/src/test/java/alluxio/underfs/obs/OBSInputStreamTest.java
  dora/underfs/obs/src/test/java/alluxio/underfs/obs/OBSPositionReaderTest.java
  dora/underfs/obs/src/test/java/alluxio/underfs/obs/OBSUnderFileSystemFactoryTest.java
  dora/underfs/obs/src/test/java/alluxio/underfs/obs/OBSUnderFileSystemTest.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSInputStreamTest.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSPositionReaderTest.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemFactoryTest.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemTest.java
Labels: type-code-quality

#18167 Fix datePredicate
  dora/core/server/master/src/main/java/alluxio/master/predicate/DatePredicate.java
  dora/core/server/master/src/test/java/alluxio/master/predicate/DatePredicateTest.java
Labels: type-bug

#18144 Generate user cli doc
  cli/src/alluxio.org/cli/cmd/cache/format.go
  cli/src/alluxio.org/cli/cmd/cache/free.go
  cli/src/alluxio.org/cli/cmd/conf/get.go
  cli/src/alluxio.org/cli/cmd/conf/log.go
  cli/src/alluxio.org/cli/cmd/exec/test_basic_io.go
  cli/src/alluxio.org/cli/cmd/exec/test_ufs_io.go
  cli/src/alluxio.org/cli/cmd/fs/cat.go
  cli/src/alluxio.org/cli/cmd/fs/checksum.go
  cli/src/alluxio.org/cli/cmd/fs/chgrp.go
  cli/src/alluxio.org/cli/cmd/fs/chmod.go
  cli/src/alluxio.org/cli/cmd/fs/chown.go
  cli/src/alluxio.org/cli/cmd/fs/consistant_hash.go
  cli/src/alluxio.org/cli/cmd/fs/consistent_hash.go
  cli/src/alluxio.org/cli/cmd/fs/cp.go
  cli/src/alluxio.org/cli/cmd/fs/fs.go
  cli/src/alluxio.org/cli/cmd/fs/head.go
  cli/src/alluxio.org/cli/cmd/fs/ls.go
  cli/src/alluxio.org/cli/cmd/fs/mkdir.go
  cli/src/alluxio.org/cli/cmd/fs/mv.go
  cli/src/alluxio.org/cli/cmd/fs/rm.go
  cli/src/alluxio.org/cli/cmd/fs/stat.go
  cli/src/alluxio.org/cli/cmd/fs/tail.go
  cli/src/alluxio.org/cli/cmd/generate/doc_tables.go
  cli/src/alluxio.org/cli/cmd/generate/generate.go
  cli/src/alluxio.org/cli/cmd/generate/user_cli.go
  cli/src/alluxio.org/cli/cmd/info/collect.go
  cli/src/alluxio.org/cli/cmd/info/version.go
  cli/src/alluxio.org/cli/cmd/initiate/clear_os_cache.go
  cli/src/alluxio.org/cli/cmd/initiate/copy_dir.go
  cli/src/alluxio.org/cli/cmd/initiate/format.go
  cli/src/alluxio.org/cli/cmd/initiate/validate.go
  cli/src/alluxio.org/cli/cmd/job/load.go
  cli/src/alluxio.org/cli/cmd/journal/format.go
  cli/src/alluxio.org/cli/cmd/journal/read.go
  cli/src/alluxio.org/cli/cmd/process/process.go
  cli/src/alluxio.org/cli/env/command.go
  cli/src/alluxio.org/cli/env/process_start.go
  cli/src/alluxio.org/cli/env/process_stop.go
  cli/src/alluxio.org/cli/env/service.go
  cli/src/alluxio.org/cli/launch/launch.go
  cli/src/alluxio.org/go.mod
  docs/_data/table/chmod-permission.csv
  docs/en/operation/Logging.md
  docs/en/operation/User-CLI.md
  docs/en/reference/Troubleshooting.md
Labels: type-docs

#18150 Fix the broken PagedDoraWorkerTest
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-code-quality

#18169 Fix `NoClassDefFoundError` UnderFileSystemFactory not loaded
  dora/core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
Labels: type-bug

#18172 return an all zero fsstat
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Labels: type-bug

#18174 Add back journal checkpoint command
  cli/src/alluxio.org/cli/cmd/journal/checkpoint.go
  cli/src/alluxio.org/cli/cmd/journal/journal.go
  docs/en/operation/User-CLI.md
Labels: type-feature

#18177 [DOCFIX] Fix typo in generate docs cmd
  cli/src/alluxio.org/cli/cmd/generate/generate.go
Labels: type-docs

#18179 Enable config the virtual nodes num per node
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-feature

#18184 Fix GCSV2UnderFileSystem initialization
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
Labels: type-feature

#18190 Stop fuse web server
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: type-bug

#18187 Only stop processes belong to the current user
  cli/src/alluxio.org/cli/env/process.go
Labels: type-bug

#18191 Fix typo in ServiceDiscoveryRecipe
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
Labels: type-code-quality

#18188 Fix the bug of using a terminated executor in S3 UFS
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
Labels: type-bug

#17820 Add new worker identity
  common/transport/src/main/proto/grpc/common.proto
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/wire/InvalidVersionParsingException.java
  dora/core/common/src/main/java/alluxio/wire/MissingRequiredFieldsParsingException.java
  dora/core/common/src/main/java/alluxio/wire/ProtoParsingException.java
  dora/core/common/src/main/java/alluxio/wire/WorkerIdentity.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/WorkerIdentityProvider.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/grpc/DoraWorkerClientServiceHandlerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/modules/WorkerIdentityProviderTest.java
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Labels: type-feature

#18192 [DOCFIX] Describe how the user cli docs are generated
  cli/README.md
Labels: type-docs

#18180 Split the fuse stream close() method
  dora/core/common/src/main/java/alluxio/resource/CloseableResource.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReadOrOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
Labels: type-code-quality

#18197 Refactor the collectInfo main for future use
  cli/src/alluxio.org/cli/cmd/info/collect.go
  dora/shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
Labels: type-ease-of-use

#18000 Improve the random read behavior in StressWorkerBench
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchParameters.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-feature

#18166 Format reports on Golang CLI
  cli/src/alluxio.org/cli/cmd/info/report.go
  cli/src/alluxio.org/go.mod
  cli/src/alluxio.org/go.sum
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceOutput.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/SummaryOutput.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
Labels: type-feature

#18186 Update collectAlluxioInfo and other bin/alluxio cmd strings
  cli/src/alluxio.org/cli/cmd/initiate/validate.go
  dora/core/server/common/src/main/java/alluxio/master/journal/checkpoint/TarballCheckpointFormat.java
  dora/core/server/common/src/main/java/alluxio/master/journal/checkpoint/ZipCheckpointFormat.java
  dora/core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
  dora/integration/tools/validation/src/main/java/alluxio/cli/ClusterConfConsistencyValidationTask.java
  dora/integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
  dora/integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java
  dora/shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java
Labels: type-bug

#18195 Refactor build logic for usability
  dev/scripts/src/alluxio.org/build/cmd/assembly.go
  dev/scripts/src/alluxio.org/build/cmd/build.go
  dev/scripts/src/alluxio.org/build/cmd/docker.go
  dev/scripts/src/alluxio.org/build/cmd/flags.go
  dev/scripts/src/alluxio.org/build/cmd/module.go
  dev/scripts/src/alluxio.org/build/cmd/preset.go
  dev/scripts/src/alluxio.org/build/cmd/profile.go
  dev/scripts/src/alluxio.org/build/cmd/tarball.go
  dev/scripts/src/alluxio.org/build/cmd/ufs.go
  dev/scripts/src/alluxio.org/build/cmd/version.go
Labels: type-devops

#18200 Fix last modified time is 0 in UfsFileIterable
  dora/core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/UfsFileIterableTest.java
Labels: type-bug

#18170 Fix and re-enable UfsFileIn/OutStreamTest
  dora/core/client/fs/src/test/java/alluxio/client/file/ufs/AbstractUfsStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileInStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileOutStreamTest.java
Labels: type-code-quality

#17983 Support display all log files on web UI
  core/common/src/main/java/alluxio/Constants.java
  core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
  core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
Labels: type-ease-of-use

#17984 Support unmount and remount in one atomic operation
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
Labels: area-shell, type-feature, breaks-compatibility

#18183 Enable static consistent hash ring
  common/transport/src/main/proto/grpc/block_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/BlockMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/BlockWorkerInfo.java
  dora/core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/DefaultWorkerProvider.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/WorkerProvider.java
Labels: type-feature

#18103 Add worker rejected cache block request metrics
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
Labels: type-feature

#18160 Add Read Metrics
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataReader.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Labels: type-feature

#18154 Add Dora read fallback to UFS logics
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCachePositionReader.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/DoraCachePositionReaderTest.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-feature

#18204 Close Etcd client when process exits
  dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
Labels: type-bug

#18205 Fix read position in PagedDoraWorker
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
Labels: type-bug

#18206 Improve resource deallocation in FUSE
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: type-bug

#18207 Move json formatting in info as util SKIPCI
  cli/src/alluxio.org/cli/cmd/info/report.go
  cli/src/alluxio.org/cli/cmd/util/format.go
Labels: type-code-quality

#18209 Remove log
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
Labels: type-code-quality

#18201 Remove master host check
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java
Labels: type-code-quality

#18127 Add test for DoraMetaManager
  dora/core/server/worker/src/test/java/alluxio/worker/dora/DoraMetaManagerTest.java
Labels: type-code-quality

#18175 Modify StressWorkerBench: calculate elapsed time in nanoseconds
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPoint.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-code-quality

#18211 Add manual exit at the end of FUSE life cycle
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: area-fuse, type-bug, type-code-quality

#18164 Add project structure and template for native components
  native/pom.xml
  native/rust/README.md
  native/rust/archetype/pom.xml
  native/rust/archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
  native/rust/archetype/src/main/resources/archetype-resources/pom.xml
  native/rust/archetype/src/main/resources/archetype-resources/src/main/java/NativeAdder.java
  native/rust/archetype/src/main/resources/archetype-resources/src/main/rust/.cargo/config.toml
  native/rust/archetype/src/main/resources/archetype-resources/src/main/rust/Cargo.toml
  native/rust/archetype/src/main/resources/archetype-resources/src/main/rust/rust-toolchain.toml
  native/rust/archetype/src/main/resources/archetype-resources/src/main/rust/src/lib.rs
  native/rust/archetype/src/main/resources/archetype-resources/src/test/java/NativeAdderTest.java
  native/rust/archetype/src/test/resources/projects/test/archetype.properties
  native/rust/archetype/src/test/resources/projects/test/goal.txt
  native/rust/pom.xml
  pom.xml
Labels: area-build, POM Change, type-feature, area-native

#18215 Make copy & move return list of tasks
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
Labels: type-performance

#18148 Create a init test for cluster
  cli/src/alluxio.org/cli/cmd/exec/exec.go
  cli/src/alluxio.org/cli/cmd/exec/test_worker.go
  dora/shell/src/main/java/alluxio/cli/CheckCluster.java
Labels: type-code-quality

#18223 Fix check-cached
  cli/src/alluxio.org/cli/cmd/fs/check_cached.go
Labels: type-bug

#18124 [DOCFIX] Remove deprecated sections from journal docs
  cli/src/alluxio.org/cli/cmd/initiate/format.go
  docs/en/operation/Journal.md
  docs/en/operation/User-CLI.md
Labels: type-docs

#18218 Modify go dependencies and code to be compatible with go1.15
  build/cli/build-cli.sh
  cli/src/alluxio.org/cli/processes/common.go
  cli/src/alluxio.org/go.mod
  cli/src/alluxio.org/go.sum
  dev/scripts/src/alluxio.org/build/artifact/artifact-methods.go
  dev/scripts/src/alluxio.org/build/cmd/build.go
  dev/scripts/src/alluxio.org/go.mod
Labels: type-feature

#18185 Add worker vCPU info to fsadmin report capacity command
  core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
  core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  core/common/src/main/java/alluxio/wire/WorkerInfo.java
  core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
  core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
  core/transport/src/main/proto/grpc/block_master.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
Labels: type-feature
