Repository Alluxio/alluxio, pull requests merged in 2023-07, with the labels that each got.

#17711 Fix the bug that worker doesn't check size when writing temp pages
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/QuotaManagedPageStoreDir.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataWriter.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/worker/block/io/BlockWriter.java
  dora/core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockWriter.java
  dora/core/common/src/test/java/alluxio/worker/block/io/MockBlockWriter.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockWriter.java
  dora/core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
Labels: type-bug

#17514 Fix local cache identifier to solve the local cache consistent issue
  core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-feature

#17717 Merge master-2.x commits 2023/06/01~2023/06/30 into main
  docs/_data/table/cn/master-metrics.yml
  docs/cn/ufs/Azure-Data-Lake-Gen2.md
  docs/en/operation/User-CLI.md
  dora/core/common/src/main/java/alluxio/exception/runtime/BlockDoesNotExistRuntimeException.java
  dora/core/common/src/main/java/alluxio/heartbeat/CronExpressionIntervalSupplier.java
  dora/core/common/src/main/java/alluxio/heartbeat/FixedIntervalSupplier.java
  dora/core/common/src/main/java/alluxio/heartbeat/SleepIntervalSupplier.java
  dora/core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
  dora/core/common/src/main/java/alluxio/time/Sleeper.java
  dora/core/common/src/main/java/alluxio/time/SteppingThreadSleeper.java
  dora/core/common/src/main/java/alluxio/util/io/FileUtils.java
  dora/core/common/src/main/java/alluxio/wire/WorkerWebUILogs.java
  dora/core/common/src/test/java/alluxio/heartbeat/SleepingTimerForCronExpressionIntervalSupplierTest.java
  dora/core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
  dora/core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
  dora/core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  dora/core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-feature

#17728 Return if dst folder exists in distCp
  dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
Labels: type-bug

#17557 [SMALLFIX] Fix typo in MetricsSystem
  dora/core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Labels: type-code-quality

#17730 Fix lib jar copy dst path
  dora/integration/tools/hms/pom.xml
  dora/integration/tools/validation/pom.xml
  dora/table/server/underdb/glue/pom.xml
  dora/table/server/underdb/hive/pom.xml
  dora/underfs/abfs/pom.xml
  dora/underfs/adl/pom.xml
  dora/underfs/cephfs-hadoop/pom.xml
  dora/underfs/cephfs/pom.xml
  dora/underfs/cos/pom.xml
  dora/underfs/cosn/pom.xml
  dora/underfs/gcs/pom.xml
  dora/underfs/hdfs/pom.xml
  dora/underfs/kodo/pom.xml
  dora/underfs/local/pom.xml
  dora/underfs/obs/pom.xml
  dora/underfs/oss/pom.xml
  dora/underfs/ozone/pom.xml
  dora/underfs/s3a/pom.xml
  dora/underfs/swift/pom.xml
  dora/underfs/wasb/pom.xml
  dora/underfs/web/pom.xml
Labels: type-devops

#17725 Use a more efficient way to store content hash
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  dora/core/common/src/main/java/alluxio/wire/FileInfo.java
  dora/core/common/src/test/java/alluxio/wire/FileInfoTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-performance

#17686 Support position reader of OBS
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSPositionReader.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
Labels: type-feature

#17710 Refactor dora meta manager
  dora/core/common/pom.xml
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/ListStatusResult.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  pom.xml
Labels: type-feature

#17705 [DOCFIX] Add multipart-upload method
  docs/_data/menu-en.yml
  docs/en/ufs/COS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/S3.md
Labels: type-docs

#17716 Fix to support alluxio version other than xxx.yyy
  dora/core/common/src/main/java/alluxio/RuntimeConstants.java
Labels: type-bug

#17738 Define configurability of update checker
  dora/core/common/src/main/java-templates/alluxio/ProjectConstants.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  pom.xml
Labels: type-feature

#17742 Change to use the new way to get the ETag of the file
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
Labels: type-bug

#17724 Add recursive create/delete
  dora/core/common/src/main/java/alluxio/underfs/options/DeleteOptions.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-bug

#17740 Define default-release and default-testing tarball profiles
  dev/scripts/src/alluxio.org/build/cmd/flags.go
  dev/scripts/src/alluxio.org/build/cmd/profile.go
  dev/scripts/src/alluxio.org/build/profiles.yml
  dora/core/common/src/main/java-templates/alluxio/ProjectConstants.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  pom.xml
Labels: type-feature

#17744 [DOCFIX] Fix fuse doc picture
  docs/en/fuse-sdk/Local-Cache.md
Labels: type-bug

#17685 Support list files through RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/ResponseFileInfo.java
  dora/core/server/worker/src/test/java/alluxio/worker/http/TestHttpServerHandler.java
Labels: type-feature

#17747 [DOCFIX] Fix doc errors for Tencent Cloud EMR
  docs/cn/cloud/Tencent-Cloud-EMR.md
  docs/en/cloud/Tencent-Cloud-EMR.md
Labels: type-docs

#17749 [DOCFIX] Add Table of contents nav bar on right side of page
  docs/_includes/toc.html
  docs/_layouts/global.html
  docs/en/Overview.md
  docs/en/administration/Basic-Logging.md
  docs/en/administration/Troubleshooting.md
  docs/en/api/Java-API.md
  docs/en/api/REST-API.md
  docs/en/api/S3-API.md
  docs/en/compute/Flink.md
  docs/en/compute/Hadoop-MapReduce.md
  docs/en/compute/Hive.md
  docs/en/compute/Presto-Iceberg.md
  docs/en/compute/Presto.md
  docs/en/compute/Spark.md
  docs/en/compute/Trino.md
  docs/en/contributor/Building-Alluxio-From-Source.md
  docs/en/contributor/Code-Conventions.md
  docs/en/contributor/Contributor-Getting-Started.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/contributor/Documentation-Conventions.md
  docs/en/core-services/Caching.md
  docs/en/core-services/Metadata-Caching.md
  docs/en/deploy/Requirements.md
  docs/en/deploy/Running-Alluxio-On-a-HA-Cluster.md
  docs/en/fuse-sdk/Advanced-Tuning.md
  docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache.md
  docs/en/fuse-sdk/Local-Data-Cache.md
  docs/en/fuse-sdk/Local-Metadata-Cache.md
  docs/en/fuse-sdk/Overview-Fuse-Sdk.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
  docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
  docs/en/operation/Configuration.md
  docs/en/operation/Journal.md
  docs/en/operation/Metrics-System.md
  docs/en/operation/User-CLI.md
  docs/en/overview/Getting-Started.md
  docs/en/overview/Why-Dora.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/reference/Metrics-List.md
  docs/en/reference/Properties-List.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/HDFS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
Labels: type-docs

#17755 [SMALLFIX] Use field property for 'AbstractCmdRunner'
  job/server/src/main/java/alluxio/master/job/tracker/DistLoadCliRunner.java
  job/server/src/main/java/alluxio/master/job/tracker/MigrateCliRunner.java
Labels: area-jobservice, type-code-quality

#17751 Revert java version back to java8
  build/findbugs/findbugs-exclude.xml
  dora/core/common/src/main/java/alluxio/concurrent/ForkJoinPoolHelper.java
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/CompletableFuture.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/CompletionStage.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/CountedCompleter.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinPool.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinTask.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinWorkerThread.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/TLRandom.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/UnsafeAccess.java
  dora/core/common/src/main/java/alluxio/metrics/OperationSystemGaugeSet.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  dora/core/common/src/main/java/alluxio/util/ThreadFactoryUtils.java
  dora/core/server/common/src/main/java/alluxio/executor/ExecutorServiceBuilder.java
  dora/core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
  dora/core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataConcurrentTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/tests/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
  libexec/alluxio-config.sh
  pom.xml
Labels: type-bug

#17760 [DOCFIX] Update the style of nav list
  docs/_includes/sitemap.html
Labels: type-docs

#17732 Create UTs of putting bucket for S3 proxy with S3 mock
  dora/tests/src/test/java/alluxio/client/rest/CreateBucketTest.java
  dora/tests/src/test/java/alluxio/client/rest/ListStatusTest.java
  dora/tests/src/test/java/alluxio/client/rest/RestApiTest.java
  dora/tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: type-code-quality

#17663 Shade protobuf to prevent dependency confliction
  dora/shaded/client/pom.xml
Labels: type-bug

#17764 Add createChannel API for extension
  dora/core/common/src/main/java/alluxio/AbstractClient.java
Labels: type-feature

#17752 Handle overload in scheduler
  dora/core/common/src/main/java/alluxio/exception/runtime/AlluxioRuntimeException.java
  dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#17768 Fix Dockerfiles
  integration/docker/Dockerfile
  integration/docker/Dockerfile-dev
Labels: type-bug

#17769 [DOCFIX] Change docs width from 1200px to entire page
  docs/_layouts/global.html
  docs/css/main.css
Labels: type-docs

#17770 [DOCFIX] Reformat overview page & add glossary page
  docs/_data/menu-en.yml
  docs/en/Get-Started.md
  docs/en/Overview.md
  docs/en/compute/Hadoop-MapReduce.md
  docs/en/compute/Hive.md
  docs/en/compute/Presto-Iceberg.md
  docs/en/compute/Presto.md
  docs/en/compute/Spark.md
  docs/en/compute/Trino.md
  docs/en/contributor/Building-Alluxio-From-Source.md
  docs/en/contributor/Code-Conventions.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/core-services/Data-Caching.md
  docs/en/core-services/Metadata-Caching.md
  docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
  docs/en/deploy/Software-Requirements.md
  docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Overview-Fuse-Sdk.md
  docs/en/introduction/Glossary.md
  docs/en/introduction/Introduction.md
  docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
  docs/en/operation/Journal.md
  docs/en/overview/Why-Dora.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
Labels: type-docs

#17757 Add filter to copy jobs
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJobFactory.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
Labels: type-feature

#17758 Fix memory leaking when loading data
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
Labels: type-bug

#17765 Update local run configs
  conf/alluxio-site-properties.dora-local-minimum.template
  dev/intellij/runConfigurations/AlluxioDoraWorker_0.xml
  dev/intellij/runConfigurations/AlluxioDoraWorker_1.xml
  dev/intellij/runConfigurations/AlluxioJobMaster.xml
  dev/intellij/runConfigurations/AlluxioJobMaster_0.xml
  dev/intellij/runConfigurations/AlluxioJobMaster_1.xml
  dev/intellij/runConfigurations/AlluxioJobMaster_2.xml
  dev/intellij/runConfigurations/AlluxioJobWorker.xml
  dev/intellij/runConfigurations/AlluxioMaster_0.xml
  dev/intellij/runConfigurations/AlluxioMaster_1.xml
  dev/intellij/runConfigurations/AlluxioMaster_2.xml
  dev/intellij/runConfigurations/AlluxioWorker.xml
Labels: type-devops

#17753 Fix worker policy race condition
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/WorkerLocationPolicyTest.java
Labels: type-bug

#17616 Allow forcing open call to fallback storage in local cache read
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Labels: type-feature

#17771 [DOCFIX] Delete properties
  docs/en/administration/Basic-Logging.md
  docs/en/administration/Troubleshooting.md
  docs/en/api/Java-API.md
  docs/en/api/REST-API.md
  docs/en/api/S3-API.md
  docs/en/compute/Flink.md
  docs/en/compute/Hadoop-MapReduce.md
  docs/en/compute/Hive.md
  docs/en/compute/Presto-Iceberg.md
  docs/en/compute/Presto.md
  docs/en/compute/Spark.md
  docs/en/compute/Trino.md
  docs/en/contributor/Building-Alluxio-From-Source.md
  docs/en/contributor/Code-Conventions.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/contributor/Documentation-Conventions.md
  docs/en/core-services/Metadata-Caching.md
  docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
  docs/en/deploy/Software-Requirements.md
  docs/en/fuse-sdk/Advanced-Tuning.md
  docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache.md
  docs/en/fuse-sdk/Local-Data-Cache.md
  docs/en/fuse-sdk/Local-Metadata-Cache.md
  docs/en/fuse-sdk/Overview-Fuse-Sdk.md
  docs/en/introduction/Glossary.md
  docs/en/introduction/Introduction.md
  docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
  docs/en/operation/Configuration.md
  docs/en/operation/Journal.md
  docs/en/operation/Metrics-System.md
  docs/en/operation/User-CLI.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/reference/Metrics-List.md
  docs/en/reference/Properties-List.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/HDFS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
Labels: type-docs

#17772 Add back jdk8 to images used for PR builds
  dev/github/Dockerfile-jdk11
  dev/github/Dockerfile-jdk17
  dev/github/Dockerfile-jdk8
Labels: type-devops

#17774 Change builds to use jdk8
  .github/workflows/checkstyle.yml
  .github/workflows/java8_integration_tests.yml
  .github/workflows/java8_integration_tests_ft.yml
  .github/workflows/java8_integration_tests_webui.yml
  .github/workflows/java8_unit_tests.yml
  dev/github/run_checks.sh
  dev/github/run_docker.sh
  dev/github/run_tests.sh
Labels: type-devops

#17776 Fix recursive listing cache
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-bug

#17778 [DOCFIX] Remove install Alluxio step in integration docs
  docs/en/compute/Hive.md
  docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
Labels: type-docs

#17759 Improve HTTP RESTful API performance
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpResponseContext.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerInitializer.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
Labels: type-performance

#17243 Remove Short Circuit read/write
  common/transport/src/main/proto/grpc/block_worker.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriter.java
  dora/core/client/fs/src/test/java/alluxio/client/block/BlockStoreClientTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/common/src/main/java/alluxio/wire/MasterWebUIMetrics.java
  dora/core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockReader.java
  dora/core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockWriter.java
  dora/core/common/src/test/java/alluxio/worker/block/io/LocalFileBlockReaderTest.java
  dora/core/common/src/test/java/alluxio/worker/block/io/LocalFileBlockWriterTest.java
  dora/core/server/common/src/main/java/alluxio/cli/Format.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
  dora/core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
  dora/core/server/master/src/test/java/alluxio/master/metrics/MetricsStoreTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/package-info.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/DecommissionWorkerCommand.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/MetricsCommandTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraPositionReaderIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraReadIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/FileInStreamDecommissionIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/FileInStreamIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/FileOutStreamDecommissionIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/AbstractFuseDoraTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/readonly/AbstractFuseDoraReadOnlyTest.java
  dora/tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-debt, API Change

#17783 Fix list files RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-bug

#17781 Remove rocks page store log
  core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
Labels: type-bug

#17786 Remove dependency on com.igormaznitsa:jcp
  build/checkstyle/suppressions.xml
  dora/tests/pom.xml
  dora/underfs/hdfs/pom.xml
  pom.xml
Labels: type-debt, type-code-quality

#17722 Fix to support mount fuse do not report error on macosx
  integration/fuse/bin/alluxio-fuse
Labels: type-bug

#17773 [DOCFIX] Update Glossary Page & minor changes
  docs/_data/menu-en.yml
  docs/en/Overview.md
  docs/en/core-services/Data-Caching.md
  docs/en/introduction/Glossary.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/GCS.md
  docs/en/ufs/OBS.md
Labels: type-docs

#17787 Fix Maven warnings on plugin declaration
  pom.xml
Labels: type-debt

#17785 Close client when heartbeat executor closed
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
Labels: type-bug

#17791 Remove rocks page store log from PageStoreDir
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
Labels: type-debt

#17767 Add reference property support
  dora/core/common/src/main/java/alluxio/conf/Configuration.java
  dora/core/common/src/main/java/alluxio/conf/Source.java
  dora/core/common/src/main/java/alluxio/conf/reference/DemoProperty.java
  dora/core/common/src/main/java/alluxio/conf/reference/ReferenceProperty.java
  dora/core/common/src/main/resources/META-INF/services/alluxio.conf.reference.ReferenceProperty
  dora/core/common/src/test/java/alluxio/conf/SourceTest.java
Labels: type-feature

#17430 Upgrade maven surefire plugin to remove build warnings
  dev/github/run_tests.sh
  pom.xml
Labels: type-debt

#17794 Fix base docker image for alluxio-maven jdk17
  dev/github/Dockerfile-jdk17
Labels: type-devops

#17799 Change for extension
  dora/core/common/src/main/java/alluxio/ClientContext.java
  dora/core/common/src/main/java/alluxio/conf/Configuration.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
  dora/core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClientPool.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/shell/src/main/java/alluxio/common/RpcPortHealthCheckClient.java
Labels: type-feature

#17802 Install docker in alluxio-maven images
  dev/github/Dockerfile-jdk11
  dev/github/Dockerfile-jdk17
  dev/github/Dockerfile-jdk8
Labels: type-devops

#17805 Update alluxio-maven to 0.1.3
  dev/github/run_docker.sh
Labels: type-devops

#17807 Remove old generate-tarball code path
  .gitignore
  dev/scripts/.gitignore
  dev/scripts/build-docker.sh
  dev/scripts/generate-tarballs
  dev/scripts/src/alluxio.org/build-distribution/cmd/check-ufs-versions.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/flags.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-fuse-tarball.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/version.go
  dev/scripts/src/alluxio.org/build-distribution/main.go
Labels: type-devops

#17447 Support multipart upload of S3, OSS, COS and OBS
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/underfs/ObjectMultipartUploadOutputStream.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSMultipartUploadOutputStream.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSMultipartUploadOutputStream.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSMultipartUploadOutputStream.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AMultipartUploadOutputStream.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemMockServerTest.java
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
Labels: type-feature

#17748 Enable Dora write through worker to UFS
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/worker/dora/OpenFileHandle.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
  dora/tests/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/UnderStorageReadIntegrationTest.java
Labels: type-feature

#17810 Add a new constructor in FileSystemContextReinitializer
  dora/core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java
  dora/core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
Labels: type-feature

#17803 [DOCFIX] Fix table format issue for Properties-List page
  docs/css/main.css
Labels: type-docs

#17808 [DOCFIX] Update code blocks for consistency & added descriptions for storage integrations
  docs/en/Get-Started.md
  docs/en/administration/Basic-Logging.md
  docs/en/administration/Troubleshooting.md
  docs/en/api/REST-API.md
  docs/en/api/S3-API.md
  docs/en/compute/Flink.md
  docs/en/compute/Hadoop-MapReduce.md
  docs/en/compute/Hive.md
  docs/en/compute/Presto-Iceberg.md
  docs/en/compute/Presto.md
  docs/en/compute/Spark.md
  docs/en/compute/Trino.md
  docs/en/contributor/Building-Alluxio-From-Source.md
  docs/en/contributor/Code-Conventions.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/contributor/Documentation-Conventions.md
  docs/en/core-services/Metadata-Caching.md
  docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
  docs/en/fuse-sdk/Advanced-Tuning.md
  docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Local-Data-Cache.md
  docs/en/fuse-sdk/Local-Metadata-Cache.md
  docs/en/fuse-sdk/Overview-Fuse-Sdk.md
  docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
  docs/en/operation/Configuration.md
  docs/en/operation/Journal.md
  docs/en/operation/Metrics-System.md
  docs/en/operation/User-CLI.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/reference/Properties-List.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/HDFS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
Labels: type-docs

#17813 Add get functions in S3 underfs
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-feature

#17789 Add LocalWorkerPolicy for tests and extract interface for policy
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/LocalWorkerPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashProviderTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/LocalWorkerPolicyTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
Labels: type-code-quality

#17814 Refactor assembly jar defs in tarball gen
  dev/scripts/src/alluxio.org/build/assembly.yml
  dev/scripts/src/alluxio.org/build/cmd/assembly.go
  dev/scripts/src/alluxio.org/build/cmd/build.go
  dev/scripts/src/alluxio.org/build/cmd/flags.go
  dev/scripts/src/alluxio.org/build/cmd/tarball.go
Labels: type-devops

#17670 Solve FUSE flush issue
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Labels: type-bug

#17816 [DOCFIX] Delete mount command links, Add resources to Get Started
  docs/en/Get-Started.md
  docs/en/Overview.md
  docs/en/compute/Hadoop-MapReduce.md
  docs/en/compute/Presto.md
  docs/en/compute/Spark.md
  docs/en/compute/Trino.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/introduction/Glossary.md
  docs/en/introduction/Introduction.md
  docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
  docs/en/operation/Journal.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/HDFS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
Labels: type-docs

#17821 [DOCFIX] Merge Tencent COS & COSN Docs
  docs/_data/menu-en.yml
  docs/en/ufs/COS.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
Labels: type-docs

#17815 Fix fuse docs
  docs/en/fuse-sdk/Local-Cache.md
Labels: type-docs

#17823 Remove secondary master
  bin/alluxio-masters.sh
  bin/alluxio-start.sh
  bin/alluxio-stop.sh
  bin/launch-process
  conf/alluxio-env.sh.template
  conf/log4j.properties
  docs/_data/table/en/env_vars.yml
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/AlluxioSecondaryMaster.java
  dora/core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalReaderTest.java
  dora/minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
  dora/minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
  dora/minicluster/src/main/java/alluxio/master/MultiMasterEmbeddedJournalLocalAlluxioCluster.java
  dora/minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
  dora/tests/src/test/java/alluxio/client/cli/JournalToolTest.java
  dora/tests/src/test/java/alluxio/server/ft/journal/ufs/SecondaryMasterTest.java
  dora/tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
  libexec/alluxio-config.sh
Labels: type-debt

#17798 Remove shading for alluxio-test module
  dora/integration/tools/validation/src/main/java/alluxio/cli/S3ASpecificOperations.java
  dora/integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemCommonOperations.java
  dora/tests/pom.xml
Labels: type-debt, type-code-quality

#17796 Remove async-write fallback (UFS tier)
  common/transport/src/main/proto/grpc/block_master.proto
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/proto/dataserver/protocol.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/NettyDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/worker/block/BlockWorker.java
  dora/core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/test/java/alluxio/master/block/ConcurrentBlockMasterTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
  dora/core/server/worker/src/test/java/alluxio/worker/block/BlockMasterClientTest.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/RpcBenchPreparationUtils.java
  dora/tests/src/test/java/alluxio/client/fs/io/FileInStreamRehydrationIntegrationTest.java
Labels: type-debt

#17672 Support getFileBlockLocation in LocalCacheFileSystem
  core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Labels: type-bug

#17812 Change for future extension
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: type-feature

#17822 [DOCFIX] Remove accordion in Metrics-On-Kubernetes.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
Labels: type-docs

#17811 Clean up and optimize PR builds
  .github/workflows/checkstyle.yml
  .github/workflows/fuse_integration_tests.yml
  .github/workflows/java8_integration_tests.yml
  .github/workflows/java8_integration_tests_ft.yml
  .github/workflows/java8_integration_tests_webui.yml
  .github/workflows/java8_unit_tests.yml
  dev/github/run_checks.sh
  dev/github/run_docker.sh
  dev/github/run_tests.sh
Labels: type-devops

#17829 Add interfaces to allow using custom modules to inject in worker
  dora/core/common/src/test/java/alluxio/ConfigurationTestUtils.java
  dora/core/server/worker/src/main/java/alluxio/worker/WorkerProcess.java
Labels: type-devops

#17828 [DOCFIX] Add data & metadata cache fuse docs to local cache overview
  docs/_data/menu-en.yml
  docs/en/api/Java-API.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/fuse-sdk/FUSE-SDK-Overview.md
  docs/en/fuse-sdk/Local-Cache-Overview.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache.md
  docs/en/fuse-sdk/Local-Data-Cache.md
  docs/en/fuse-sdk/Local-Metadata-Cache.md
  docs/en/introduction/Glossary.md
  docs/en/operation/Metrics-System.md
Labels: type-docs

#17836 Remove k8s dir (again)
  integration/kubernetes/helm-chart/monitor/.helmignore
  integration/kubernetes/helm-chart/monitor/CHANGELOG.md
  integration/kubernetes/helm-chart/monitor/Chart.yaml
  integration/kubernetes/helm-chart/monitor/README.md
  integration/kubernetes/helm-chart/monitor/source/grafana/dashboard/dashboard.yaml
  integration/kubernetes/helm-chart/monitor/source/grafana/datasource.yaml
  integration/kubernetes/helm-chart/monitor/source/prometheus/prometheus.yaml
  integration/kubernetes/helm-chart/monitor/templates/_helpers.tpl
  integration/kubernetes/helm-chart/monitor/templates/config/grafana-conf.yaml
  integration/kubernetes/helm-chart/monitor/templates/config/prometheus-conf.yaml
  integration/kubernetes/helm-chart/monitor/templates/grafana/deployment.yaml
  integration/kubernetes/helm-chart/monitor/templates/prometheus/deployment.yaml
  integration/kubernetes/helm-chart/monitor/templates/prometheus/rbac.yaml
  integration/kubernetes/helm-chart/monitor/templates/prometheus/service.yaml
  integration/kubernetes/helm-chart/monitor/values.yaml
Labels: type-debt

#17833 Normalize the HTTP RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpRequestUri.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpRequestUtil.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/ResponseFileInfo.java
  dora/core/server/worker/src/test/java/alluxio/worker/http/TestHttpRequestUtil.java
  dora/core/server/worker/src/test/java/alluxio/worker/http/TestHttpServerHandler.java
Labels: type-feature

#17830 Remove BaseFileSystem
  docs/en/administration/Basic-Logging.md
  dora/core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/FileSystemTestBase.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MetadataCacheTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MetadataCachingFileSystemTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/cli/FuseShellTest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/UnmountCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/UpdateMountCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/MountCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/UpdateMountCommandTest.java
  dora/tests/src/test/java/alluxio/client/fs/MultiUfsMountIntegrationTest.java
Labels: type-code-quality

#17840 [DOCFIX] Fix relativize link in docs
  docs/en/fuse-sdk/FUSE-SDK-Overview.md
  docs/en/introduction/Glossary.md
Labels: type-docs

#17835 [DOCFIX] Update "Configuration Settings" page
  docs/_data/menu-en.yml
  docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
  docs/en/operation/Configuration.md
  docs/en/operation/User-CLI.md
  docs/en/reference/Environment-List.md
  docs/en/reference/Properties-List.md
Labels: type-docs

#17842 Fix compilation for unit tests build
  .github/workflows/java8_unit_tests.yml
Labels: type-devops

#17826 Cleanup top level POM dependencies
  dora/core/common/pom.xml
  dora/core/server/common/pom.xml
  dora/integration/tools/hms/pom.xml
  dora/tests/pom.xml
  dora/underfs/cephfs/pom.xml
  dora/underfs/cos/pom.xml
  dora/underfs/cosn/pom.xml
  dora/underfs/gcs/pom.xml
  dora/underfs/kodo/pom.xml
  dora/underfs/ozone/pom.xml
  dora/underfs/s3a/pom.xml
  dora/underfs/web/pom.xml
  pom.xml
Labels: type-code-quality

#17832 Add HDFS UFS integration test
  dora/shaded/hadoop/pom.xml
  dora/underfs/hdfs/pom.xml
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemIntegrationTest.java
Labels: type-code-quality

#17845 Rollback to use localcacheInStream for presto local cache
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Labels: type-bug

#17846 Add metrics for num of request to external storage when cache miss
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-feature

#17847 Add metrics for num of client position read fallback
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-resource

#17843 Remove 2.x SetReplica and Load jobs
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
  dora/core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java
  dora/job/client/src/main/java/alluxio/job/plan/replicate/DefaultReplicationHandler.java
  dora/job/client/src/main/java/alluxio/job/plan/replicate/ReplicationHandler.java
  dora/job/common/src/main/java/alluxio/job/cmd/load/LoadCliConfig.java
  dora/job/common/src/main/java/alluxio/job/plan/load/LoadConfig.java
  dora/job/common/src/main/java/alluxio/job/plan/replicate/SetReplicaConfig.java
  dora/job/common/src/test/java/alluxio/job/cmd/load/LoadCliConfigTest.java
  dora/job/common/src/test/java/alluxio/job/plan/load/LoadConfigTest.java
  dora/job/common/src/test/java/alluxio/job/plan/replicate/SetReplicaConfigTest.java
  dora/job/common/src/test/java/alluxio/job/workflow/composite/CompositeConfigTest.java
  dora/job/server/src/main/java/alluxio/job/plan/batch/BatchedJobDefinition.java
  dora/job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
  dora/job/server/src/main/java/alluxio/job/plan/replicate/SetReplicaDefinition.java
  dora/job/server/src/main/java/alluxio/job/plan/replicate/SetReplicaTask.java
  dora/job/server/src/main/java/alluxio/job/util/JobUtils.java
  dora/job/server/src/main/java/alluxio/master/job/metrics/DistributedCmdMetrics.java
  dora/job/server/src/main/java/alluxio/master/job/plan/PlanTracker.java
  dora/job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
  dora/job/server/src/main/java/alluxio/master/job/tracker/DistLoadCliRunner.java
  dora/job/server/src/main/resources/META-INF/services/alluxio.job.plan.PlanDefinition
  dora/job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
  dora/job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java
  dora/job/server/src/test/java/alluxio/job/plan/replicate/SetReplicaDefinitionEvictTest.java
  dora/job/server/src/test/java/alluxio/job/plan/replicate/SetReplicaDefinitionReplicateTest.java
  dora/job/server/src/test/java/alluxio/master/job/JobMasterTest.java
  dora/job/server/src/test/java/alluxio/master/job/plan/PlanTrackerTest.java
  dora/job/server/src/test/java/alluxio/master/job/tracker/CliRunnerTest.java
  dora/job/server/src/test/java/alluxio/master/job/tracker/CmdJobTrackerTest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
  dora/shell/src/main/java/alluxio/cli/fs/command/SetReplicationCommand.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchOperation.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/SetReplicationCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/DistributedCmdTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
  dora/tests/src/test/java/alluxio/job/plan/load/LoadIntegrationTest.java
  dora/tests/src/test/java/alluxio/job/plan/replicate/AdjustJobTestUtils.java
  dora/tests/src/test/java/alluxio/job/plan/replicate/SetReplicaEvictIntegrationTest.java
  dora/tests/src/test/java/alluxio/job/plan/replicate/SetReplicaReplicateIntegrationTest.java
Labels: type-code-quality

#17788 Convert AlluxioRuntimeException to IOException
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
Labels: type-bug

#17489 Support dynamic enable/disable audit log
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
  job/server/src/main/java/alluxio/master/job/JobMaster.java
Labels: type-ease-of-use

#17849 Add metrics counter for the page invalidated by TTL
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-feature

#17851 Revert "Add HDFS UFS integration test"
  dora/shaded/hadoop/pom.xml
  dora/underfs/hdfs/pom.xml
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemIntegrationTest.java
Labels: type-bug

#17777 Create object related UTs for S3 proxy with S3 mock
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  dora/tests/src/test/java/alluxio/client/rest/ListStatusTest.java
  dora/tests/src/test/java/alluxio/client/rest/RestApiTest.java
  dora/tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
  dora/tests/src/test/java/alluxio/client/rest/S3ObjectTest.java
  dora/tests/src/test/java/alluxio/client/rest/TestCase.java
Labels: type-code-quality

#17854 Skip tests for release 302
  pom.xml
Labels: type-devops

#17855 Revert "Skip tests for release 302"
  pom.xml
Labels: type-devops

#17844 Remove the dependency of meta master
  dora/core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
  dora/core/common/src/main/java/alluxio/ClientContext.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java
  dora/minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
Labels: type-feature

#17831 Remove BlockLocationPolicy and BlockIn/OutStream
  dora/core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/BlockLocationPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBaseRandomPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBasedDeterministicHashPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/DeterministicHashPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/MostAvailableFirstPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/SpecificHostPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/block/policy/options/GetWorkerOptions.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java
  dora/core/client/fs/src/test/java/alluxio/client/block/BlockStoreClientTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBaseRandomPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBasedDeterministicHashPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/DeterministicHashPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/MostAvailableFirstPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/RoundRobinPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/SpecificHostPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/policy/options/GetWorkerOptionsTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/BlockOutStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockOutStream.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/TestUnderFileSystemFileOutStream.java
  dora/core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/conf/RemovedKey.java
  dora/shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/client/ClientIOWritePolicy.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
  dora/tests/src/test/java/alluxio/client/fs/RemoteReadIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/BufferedBlockInStreamIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/FileOutStreamIntegrationTest.java
  dora/tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java
Labels: type-code-quality

#17864 Disable http keep-alive to address maven deps 'Connection Reset' errors
  dev/scripts/src/alluxio.org/build/cmd/build.go
Labels: type-devops
