Repository Alluxio/alluxio, pull requests merged in 2023-12, with the labels that each got.

#18441 Add WorkerClusterView
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/MasterMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
  dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/WorkerClusterView.java
  dora/core/common/src/test/java/alluxio/membership/WorkerClusterViewTest.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/MembershipManagerWorkerProvider.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-code-quality

#18455 Fix the shading issue for javax security
  dora/shaded/client/pom.xml
Labels: type-bug

#18459 Make proxy transfer buffer size configurable
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
Labels: type-feature

#18460 Make WorkerInfo enum (and some small refactors)
  dora/core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  dora/core/common/src/main/java/alluxio/master/WorkerState.java
  dora/core/common/src/main/java/alluxio/util/webui/NodeInfo.java
  dora/core/common/src/main/java/alluxio/wire/WorkerInfo.java
  dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
  dora/core/common/src/main/java/alluxio/wire/WorkerState.java
  dora/core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
  dora/core/common/src/test/java/alluxio/wire/WorkerNetAddressTest.java
  dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  dora/core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  dora/core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
  dora/job/common/src/main/java/alluxio/job/MasterWorkerInfo.java
Labels: type-code-quality

#18454 Fix to disable worker identity reuse for registration unless in k8s
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-bug

#18444 Parse the URI if needed when creating the signature
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/StringToSignProducer.java
Labels: type-bug

#18451 Use cluster view to replace list of workers
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/LocalWorkerPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/RemoteOnlyPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/RemoteWorkerList.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/LocalWorkerPolicyTest.java
  dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
  dora/job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
  dora/job/server/src/main/java/alluxio/job/plan/persist/PersistDefinition.java
  dora/job/server/src/main/java/alluxio/job/plan/replicate/MoveDefinition.java
  dora/job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
  dora/job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java
  dora/job/server/src/test/java/alluxio/job/plan/persist/PersistDefinitionTest.java
  dora/minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
  dora/shell/src/main/java/alluxio/cli/CheckCluster.java
  dora/shell/src/main/java/alluxio/cli/LogLevel.java
  dora/shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/DecommissionWorkerCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/WorkerAddressUtils.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/metrics/ClearCommand.java
  dora/shell/src/test/java/alluxio/cli/LogLevelTest.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
  dora/tests/integration/src/test/java/alluxio/client/fs/io/FileInStreamDecommissionIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/io/FileOutStreamDecommissionIntegrationTest.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-code-quality

#18434 Fix outdated worker address info returned by consistent hash policy
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashProviderTest.java
  dora/core/common/src/main/java/alluxio/membership/WorkerClusterView.java
Labels: type-feature

#18464 Improve rest load api response JSON
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/vo/LoadJobProgressResponseVO.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/vo/LoadJobStopResponseVO.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/vo/LoadJobSubmitResponseVO.java
Labels: type-ease-of-use

#18465 Fix alluxio-fuse script for finding fuse pid
  dora/integration/fuse/bin/alluxio-fuse
Labels: type-bug

#18474 Support get page with RESTful API by specifying offset and length
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
Labels: type-feature
