Repository Alluxio/alluxio, pull requests merged in 2023-05, with the labels that each got.

#17364 Move non-java integration folders
  integration/dataproc/.gitignore
  integration/dataproc/alluxio-dataproc.sh
  integration/dataproc/build.sh
  integration/docker/.dockerignore
  integration/docker/Dockerfile
  integration/docker/Dockerfile-dev
  integration/docker/README.md
  integration/docker/conf/alluxio-env.sh.template
  integration/docker/conf/alluxio-site.properties.template
  integration/docker/entrypoint.sh
  integration/docker/hms/Dockerfile
  integration/docker/hms/README.md
  integration/docker/hms/entrypoint.sh
  integration/docker/hms/initialize.sh
  integration/emr/.gitignore
  integration/emr/alluxio-emr.json
  integration/emr/alluxio-emr.sh
  integration/emr/build.sh
  integration/metrics/README.md
  integration/metrics/docker-compose-master.yaml
  integration/metrics/docker-compose-worker.yaml
  integration/metrics/otel-agent-config-worker.yaml
  integration/metrics/otel-agent-config.yaml
  integration/metrics/otel-collector-config.yaml
  integration/metrics/prometheus.yaml
Labels: type-devops

#17361 Add content hash to Dora
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/grpc/file_system_master.proto
  common/transport/src/main/proto/proto.lock
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataMessageBlockingStream.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/NettyDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/client/fs/src/test/java/alluxio/client/block/stream/TestDataWriter.java
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/grpc/DataMessageMarshaller.java
  dora/core/common/src/main/java/alluxio/grpc/ReadResponseMarshaller.java
  dora/core/common/src/main/java/alluxio/grpc/WriteRequestMarshaller.java
  dora/core/common/src/main/java/alluxio/underfs/AtomicFileOutputStream.java
  dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/ContentHashable.java
  dora/core/common/src/main/java/alluxio/underfs/Fingerprint.java
  dora/core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
  dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  dora/core/common/src/main/java/alluxio/underfs/options/GetFileStatusOptions.java
  dora/core/common/src/test/java/alluxio/underfs/FingerprintTest.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/UfsFileWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/WriteRequestContext.java
  dora/integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemCommonOperations.java
  dora/tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  dora/tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystem.java
  dora/underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSOutputStream.java
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSOutputStream.java
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2OutputStream.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  dora/underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSLowLevelOutputStream.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSOutputStream.java
  dora/underfs/obs/src/test/java/alluxio/underfs/obs/OBSLowLevelOutputStreamTest.java
  dora/underfs/obs/src/test/java/alluxio/underfs/obs/OBSOutputStreamTest.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSLowLevelOutputStream.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSOutputStream.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSLowLevelOutputStreamTest.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSOutputStreamTest.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3ALowLevelOutputStreamTest.java
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AOutputStreamTest.java
  dora/underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
Labels: type-feature

#17369 Fix decommissioned worker recorded twice after restart
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Labels: type-bug

#17370 Fix standby master version not shown
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/proto.lock
Labels: type-bug

#17371 Update for splitting PropertyKey
  dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/security/authentication/AuthType.java
Labels: type-feature

#17367 Update maven.version in pom.xml to match Dockerfile
  pom.xml
Labels: POM Change, type-devops

#17366 Update java.version in pom.xml to 1.11
  pom.xml
Labels: POM Change, type-devops

#17375 Create interface for security Part1
  dora/core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java
  dora/core/common/src/main/java/alluxio/util/CommonUtils.java
  dora/core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
Labels: type-feature

#17234 Fix the active rpc metrics
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Labels: type-bug

#17393 Add security apies
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  dora/core/common/src/main/java/alluxio/security/user/UserState.java
Labels: POM Change, type-feature

#17391 Add interfaces for extension
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  dora/core/common/src/main/java/alluxio/security/user/UserState.java
Labels: type-feature

#17390 Support range copy in copyObject and copyPart
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-feature

#17381 [DOCFIX] Add docs for rolling upgrade and decommission worker
  docs/en/administration/Upgrade.md
  docs/en/operation/Admin-CLI.md
Labels: type-docs, Doc Fix

#17397 Port changes of [#17381] to branch-2.10
  docs/en/administration/Upgrade.md
  docs/en/operation/Admin-CLI.md
Labels: type-docs, Doc Fix

#17398 Port changes of [#17381] to branch-2.8
  docs/en/operation/Admin-CLI.md
  docs/en/operation/Upgrade.md
  docs/img/screenshot_cdh_compute_hadoop_classpath.png
Labels: type-docs, Doc Fix

#17400 Avoid the NPE exception in copy object with x-amz-tagging-directive
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-bug

#17392 Add interfaces for extension part3
  dora/core/server/common/src/main/java/alluxio/executor/ExecutorServiceBuilder.java
  dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
Labels: type-feature

#17402 Port changes of [#17390] to branch-2.8
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-feature

#17404 Add a new function in ExtensionsClassLoader
  dora/core/common/src/main/java/alluxio/extensions/ExtensionsClassLoader.java
Labels: type-feature

#17399 Fix building warnings due to POM issues
  common/transport/pom.xml
  dora/core/client/fs/pom.xml
  dora/microbench/pom.xml
  dora/pom.xml
  pom.xml
Labels: POM Change, type-code-quality

#17409 Change interfaces for extension
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: type-feature

#17406 Remove s3 handler map in s3 proxy
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RequestServlet.java
  core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Labels: type-code-quality

#17333 Fix verbose config deprecation warning
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
Labels: type-bug, area-configuration

#17411 Fix compatibility with Java 11
  build/findbugs/findbugs-exclude.xml
  dora/core/common/src/main/java/alluxio/concurrent/ForkJoinPoolHelper.java
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/CompletableFuture.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/CompletionStage.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/CountedCompleter.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinPool.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinTask.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinWorkerThread.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/TLRandom.java
  dora/core/common/src/main/java/alluxio/concurrent/jsr/UnsafeAccess.java
  dora/core/common/src/main/java/alluxio/metrics/OperationSystemGaugeSet.java
  dora/core/common/src/main/java/alluxio/util/ThreadFactoryUtils.java
  dora/core/server/common/src/main/java/alluxio/executor/ExecutorServiceBuilder.java
  dora/core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
  dora/core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataConcurrentTest.java
  libexec/alluxio-config.sh
  pom.xml
Labels: area-build, POM Change, type-bug, java, breaks-compatibility

#17388 Update branch name in update-versions.sh
  dev/scripts/update-versions.sh
Labels: type-devops

#17417 Add command lib in golang workspace
  dev/scripts/.gitignore
  dev/scripts/src/alluxio.org/README.md
  dev/scripts/src/alluxio.org/command/command.go
  dev/scripts/src/alluxio.org/go.mod
  dev/scripts/src/alluxio.org/go.sum
Labels: type-devops

#17413 Bump grpc & netty version
  dora/core/common/pom.xml
  dora/core/common/src/main/java/alluxio/grpc/GrpcSerializationUtils.java
  pom.xml
Labels: type-debt

#17416 Add interface change for worker data server
  dora/core/server/worker/src/main/java/alluxio/worker/DataServerFactory.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
Labels: type-feature

#17420 Fix s3 force path style
  underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-bug

#17230 Refactor tarball generation script
  dev/github/run_checks.sh
  dev/scripts/.gitignore
  dev/scripts/build-artifact.sh
  dev/scripts/src/alluxio.org/build/cmd/build.go
  dev/scripts/src/alluxio.org/build/cmd/flags.go
  dev/scripts/src/alluxio.org/build/cmd/module.go
  dev/scripts/src/alluxio.org/build/cmd/profile.go
  dev/scripts/src/alluxio.org/build/cmd/repo.go
  dev/scripts/src/alluxio.org/build/cmd/tarball.go
  dev/scripts/src/alluxio.org/build/cmd/ufs.go
  dev/scripts/src/alluxio.org/build/cmd/version.go
  dev/scripts/src/alluxio.org/build/main.go
  dev/scripts/src/alluxio.org/build/modules.yml
  dev/scripts/src/alluxio.org/build/profiles.yml
  dev/scripts/src/alluxio.org/go.mod
  dev/scripts/src/alluxio.org/go.sum
Labels: type-devops

#16642 Support display config hash and timestamp in web page
  core/common/src/main/java/alluxio/conf/AlluxioProperties.java
  core/common/src/main/java/alluxio/conf/Configuration.java
  core/common/src/main/java/alluxio/conf/Hash.java
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  core/common/src/main/java/alluxio/wire/ConfigHash.java
  core/common/src/main/java/alluxio/wire/Configuration.java
  core/common/src/main/java/alluxio/wire/MasterWebUIConfiguration.java
  core/common/src/main/java/alluxio/wire/WorkerWebUIConfiguration.java
  core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/PathProperties.java
  core/server/master/src/main/java/alluxio/master/meta/PathPropertiesView.java
  core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/transport/src/main/proto/grpc/meta_master.proto
  microbench/src/main/java/alluxio/fsmaster/BenchStandaloneGrpcServer.java
Labels: type-feature, area-webui, type-ease-of-use

#17395 Support print xattr for stat command
  core/common/src/main/java/alluxio/wire/FileInfo.java
Labels: type-ease-of-use

#17191 Support config obs configuration from mount option
  underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
  underfs/obs/src/main/java/alluxio/underfs/obs/ObsClientExt.java
Labels: type-feature, type-ease-of-use

#17186 Make the client poll the master concurrently
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
  core/common/src/main/java/alluxio/network/RejectingServer.java
  core/common/src/test/java/alluxio/conf/ConfigurationBuilder.java
  core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java
Labels: API Change, type-performance

#17426 Add security metrics
  dora/core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Labels: type-feature

#17425 Port changes of [#17333] to main
  dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
Labels: type-bug, area-configuration

#17379 Refactor the logic of Netty server with state machine
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTask.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
  dora/core/server/worker/src/test/java/alluxio/worker/netty/PacketReadTaskStateMachineTest.java
Labels: type-code-quality

#17427 Fix pl path for modules
  dev/scripts/src/alluxio.org/build/modules.yml
Labels: type-devops

#17407 Fix legacy config in licence checking
  dora/integration/pom.xml
  dora/microbench/pom.xml
  pom.xml
  webui/pom.xml
Labels: POM Change, type-debt

#17433 Modify the interface of Context for extension
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/Context.java
Labels: type-feature

#17436 Modify for DoraCacheFileSystem extensibility
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
Labels: type-feature

#17357 Cache block worker metrics
  core/common/src/main/java/alluxio/worker/block/BlockWorkerMetrics.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerMetricsTest.java
Labels: type-performance, area-metrics

#17439 Use local conf to create filesystem for s3proxy
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
Labels: type-bug

#17443 Modify for grpc tls config and FileSystemContext extension
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/common/src/main/java/alluxio/AbstractClient.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannelPool.java
  dora/core/common/src/test/java/alluxio/grpc/GrpcChannelPoolTest.java
  dora/shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
  dora/shell/src/main/java/alluxio/cli/fs/FileSystemShell.java
  dora/shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/metrics/ClearCommand.java
  dora/shell/src/main/java/alluxio/cli/job/JobShell.java
  dora/shell/src/test/java/alluxio/cli/bundler/command/CollectConfCommandTest.java
Labels: type-feature

#17450 Align the rule to use whether a self signed or official ca
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannelPool.java
Labels: type-feature

#17452 Add a new function to enable the caller create sasl client
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannel.java
  dora/core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
Labels: type-feature

#17455 [DOCFIX] Remove rolling upgrade from docs
  docs/en/administration/Upgrade.md
  docs/en/operation/Admin-CLI.md
Labels: type-docs

#17422 Update copy job
  common/transport/src/main/proto/grpc/file_system_master.proto
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/underfs/AtomicFileOutputStream.java
  dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  dora/core/common/src/main/java/alluxio/underfs/options/GetStatusOptions.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTestBase.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  dora/tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystem.java
  dora/underfs/abfs/src/main/java/alluxio/underfs/abfs/AbfsUnderFileSystem.java
  dora/underfs/adl/src/main/java/alluxio/underfs/adl/AdlUnderFileSystem.java
  dora/underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  dora/underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
  dora/underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java
  dora/underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
Labels: type-bug, type-debt

#17431 Remove hardcoded VERSION in libexec/alluxio-config.sh
  .gitignore
  build/version/write_version.sh
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
  dev/scripts/src/alluxio.org/build/profiles.yml
  dev/scripts/update-versions.sh
  libexec/alluxio-config.sh
  pom.xml
Labels: type-devops

#17347 Load metadata when running Load on Dora
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#17376 Support CRC32C Checksum for GCS
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/underfs/ChecksumType.java
  dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-feature

#17460 Fix Xmx check
  bin/launch-process
Labels: type-devops

#17459 Fix Xmx check
  bin/launch-process
Labels: type-devops

#17309 Avoid unnecessary config update checks
  core/common/src/main/java/alluxio/heartbeat/CronExpressionIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/FixedIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
Labels: type-bug

#17462 Port #16849 worker register to all masters to main(dora)
  common/transport/src/main/proto/grpc/block_master.proto
  common/transport/src/main/proto/proto.lock
  common/transport/src/main/proto/proto/journal/block.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  dora/core/common/src/main/java/alluxio/AbstractMasterClient.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/common/src/main/java/alluxio/worker/block/BlockHeartbeatReport.java
  dora/core/common/src/main/java/alluxio/worker/block/BlockWorker.java
  dora/core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  dora/core/server/master/src/test/java/alluxio/master/AlwaysPrimaryPrimarySelector.java
  dora/core/server/master/src/test/java/alluxio/master/MasterTestUtils.java
  dora/core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  dora/core/server/master/src/test/java/alluxio/master/block/ConcurrentBlockMasterTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/AllMasterRegistrationBlockWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReporter.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClientPool.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockSyncMasterGroup.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerFactory.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/SpecificMasterBlockSync.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/TestSpecificMasterBlockSync.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/WorkerMasterRegistrationState.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/BlockWorkerModule.java
  dora/core/server/worker/src/test/java/alluxio/underfs/SpecificMasterBlockSyncTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/block/AllMasterRegistrationBlockWorkerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/block/BlockHeartbeatReporterTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
  dora/minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
  dora/tests/src/test/java/alluxio/server/block/BlockMasterRegisterStreamIntegrationTest.java
  dora/tests/src/test/java/alluxio/server/worker/WorkerAllMasterRegistrationTest.java
Labels: type-feature, type-sync

#17464 Merge commits depending on #16849 to main
  dora/core/client/fs/src/main/java/alluxio/client/block/AllMastersWorkerInfo.java
  dora/core/client/fs/src/main/java/alluxio/client/block/util/WorkerInfoUtil.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/common/src/main/java/alluxio/util/CommonUtils.java
  dora/core/common/src/main/java/alluxio/util/WaitForOptions.java
  dora/core/common/src/main/java/alluxio/util/proto/BlockLocationUtils.java
  dora/core/common/src/test/java/alluxio/util/proto/BlockLocationUtilsTest.java
  dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockSyncMasterGroup.java
  dora/shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
  dora/shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/RpcBenchPreparationUtils.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
Labels: type-sync

#17360 Resolve the UFS leak in copy job
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#17466 Fix CCE for metric system
  core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
Labels: type-bug

#17475 Update git ignore and add Dora worker IDE run configurations
  .gitignore
  dev/intellij/runConfigurations/AlluxioDoraWorker_0.xml
  dev/intellij/runConfigurations/AlluxioDoraWorker_1.xml
Labels: type-devops

#17175 Support changing log level at runtime for alluxio-fuse
  integration/fuse/pom.xml
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseRestServiceHandler.java
  integration/fuse/src/main/java/alluxio/fuse/FuseWebServer.java
  shell/src/main/java/alluxio/cli/LogLevel.java
Labels: POM Change, type-feature, API Change

#17480 Fix copy UFS
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#17470 Mark job as failure if there's failed files
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
Labels: type-feature

#17484 Add permission exception in dora client exception list
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
Labels: type-feature

#17419 Merge cherry-picked s3 ufs changes from 2.x branch
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/underfs/AsyncUfsClient.java
  dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UfsLoadResult.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  dora/core/common/src/main/java/alluxio/util/RateLimiter.java
  dora/core/common/src/main/java/alluxio/util/SimpleRateLimiter.java
  dora/core/common/src/test/java/alluxio/underfs/ObjectUnderFileSystemTest.java
  dora/core/common/src/test/java/alluxio/underfs/UnderFileSystemTestUtil.java
  dora/core/server/master/pom.xml
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterS3UfsTest.java
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  dora/tests/pom.xml
  dora/tests/src/test/java/alluxio/client/fs/FileSystemS3UfsIntegrationTest.java
  dora/tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  dora/underfs/local/pom.xml
  dora/underfs/local/src/test/java/alluxio/underfs/local/LocalUnderFileSystemTest.java
  dora/underfs/pom.xml
  dora/underfs/s3a/pom.xml
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemMockServerTest.java
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
  pom.xml
Labels: type-feature

#17487 Fix build path in shaded/client-hadoop3 pom
  dora/shaded/client-hadoop3/pom.xml
Labels: type-devops

#17482 Add move job
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/proto/journal/job.proto
  common/transport/src/main/proto/proto/journal/journal.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java
  dora/core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
  dora/core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/task/DeleteHandler.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-feature

#17444 Make dockerfile extendable
  integration/docker/.dockerignore
  integration/docker/Dockerfile
  integration/docker/Dockerfile-base
  integration/docker/Dockerfile-dev
  integration/docker/conf/alluxio-env.sh.template
  integration/docker/conf/alluxio-site.properties.template
Labels: type-devops

#17471 Fix FUSE mount issue
  dora/integration/fuse/bin/alluxio-fuse
Labels: type-bug

#17491 Improve monitor script printout
  bin/alluxio-monitor.sh
Labels: type-devops

#17500 Revert "Make dockerfile extendable"
  integration/docker/.dockerignore
  integration/docker/Dockerfile
  integration/docker/Dockerfile-base
  integration/docker/Dockerfile-dev
  integration/docker/conf/alluxio-env.sh.template
  integration/docker/conf/alluxio-site.properties.template
Labels: type-devops

#17499 Modify the visibility and inheritance of some dora interfaces
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockReadRequestContext.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
Labels: type-feature

#17501 Add toModeBits for extension
  dora/core/common/src/main/java/alluxio/security/authorization/AclAction.java
Labels: type-feature

#17498 Create `libexec/version.sh` for tarball dry run
  dev/scripts/src/alluxio.org/build/cmd/build.go
Labels: type-devops

#17497 Fix a bug that creates 0 byte block file mistakenly
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-bug

#17368 Update scheduler to work with copy
  common/transport/src/main/proto/grpc/block_worker.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/RoundRobinWorkerAssignPolicy.java
  dora/core/server/master/src/main/java/alluxio/master/job/WorkerAssignPolicy.java
  dora/core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Task.java
Labels: type-feature

#17469 Cleanup HADOOP1 support
  integration/tools/pom.xml
  tests/pom.xml
  tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
  underfs/hdfs/pom.xml
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-debt

#17504 Fix deadlock in LocalCacheManager
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Labels: type-bug

#17505 Add initial framework for write support in Dora
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/DoraOutStream.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraOpenFileHandleContainer.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/OpenFileHandle.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: type-feature

#17493 fixed directory deletion failure when ufs is cos
  dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
Labels: type-bug

#17507 Cleanup HADOOP1 support
  dora/integration/tools/pom.xml
  dora/tests/pom.xml
  dora/underfs/hdfs/pom.xml
Labels: type-debt

#17510 Add CreateFile/CompleteFile support in worker
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/DoraOutStream.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/common/src/main/java/alluxio/worker/dora/OpenFileHandle.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraOpenFileHandleContainer.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: type-feature

#17441 Add zero-copy feature for paged store
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCachePositionReader.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/TimeBoundPageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
  dora/core/common/src/main/java/alluxio/file/NettyBufTargetBuffer.java
  dora/core/common/src/main/java/alluxio/network/protocol/RPCMessageEncoder.java
  dora/core/common/src/main/java/alluxio/network/protocol/RPCProtoMessage.java
  dora/core/common/src/main/java/alluxio/network/protocol/databuffer/CompositeDataBuffer.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
  dora/core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraPositionReaderIntegrationTest.java
Labels: type-performance

#17512 Call needsCache in LocalCacheFileSystem
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
Labels: type-debt

#17519 Fix a bug that creates 0 byte block file mistakenly; Port [#179497] to branch-2.9
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-bug

#17508 Fix standalone fuse tarball error
  dev/scripts/src/alluxio.org/build/cmd/tarball.go
  dev/scripts/src/alluxio.org/build/profiles.yml
  dora/integration/fuse/bin/alluxio-fuse
Labels: type-devops

#17516 Add underfs interfaces
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/options/OpenOptions.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-feature

#17145 Remove unnecessary inode.isComplete() check from completeFile()
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Labels: type-bug

#17520 [DOCFIX] Update dora docs
  assembly/README.md
  docs/_config.yml
  docs/cn/kubernetes/Running-Alluxio-On-Kubernetes.md
  docs/cn/overview/Getting-Started.md
  docs/cn/overview/JobService.md
  docs/cn/ufs/Minio.md
  docs/cn/ufs/Ozone.md
  docs/en/Overview.md
  docs/en/administration/Troubleshooting.md
  docs/en/api/POSIX-API.md
  docs/en/cloud/AWS-EMR.md
  docs/en/cloud/Google-Dataproc.md
  docs/en/compute/Hive.md
  docs/en/compute/Spark.md
  docs/en/contributor/Building-Alluxio-From-Source.md
  docs/en/contributor/Contributor-Getting-Started.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/core-services/Caching.md
  docs/en/core-services/Metadata-Caching.md
  docs/en/core-services/Unified-Namespace.md
  docs/en/deploy/Deploy-Alluxio-Kubernetes.md
  docs/en/deploy/Requirements.md
  docs/en/deploy/Running-Alluxio-Locally.md
  docs/en/deploy/Running-Alluxio-On-Docker.md
  docs/en/deploy/Running-Alluxio-On-a-Cluster.md
  docs/en/dora/Deploy-Alluxio-Cluster.md
  docs/en/dora/Overview.md
  docs/en/fuse-sdk/FUSE-SDK.md
  docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
  docs/en/operation/User-CLI.md
  docs/en/overview/Architecture.md
  docs/en/overview/FAQ.md
  docs/en/overview/Getting-Started.md
  docs/en/overview/JobService.md
  docs/en/overview/Use-Cases.md
  docs/en/overview/Why-Dora.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/solutions/Deep-Learning.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COSN.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/HDFS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Swift.md
  docs/en/ufs/WEB.md
  docs/img/dora_architecture.png
  docs/img/dora_read_approaches.png
  docs/img/position_read_latency.png
  docs/img/single_worker_storage_scalability.png
  docs/img/zero_copy_network.png
Labels: type-docs

#17358 Deprecate some Raft journal RPCs
  core/transport/src/main/proto/grpc/raft_journal.proto
  core/transport/src/main/proto/proto.lock
Labels: area-master, area-rpc, type-code-quality
