Repository Alluxio/alluxio, pull requests merged in 2023-04, with the labels that each got.

#17165 Add usage info for omit-mount-info
  docs/en/operation/User-CLI.md
  shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Labels: API Change

#17187 [DOCFIX]Fix some bugs related to Caching.md
  docs/cn/core-services/Caching.md
  docs/en/core-services/Caching.md
Labels: Doc Fix

#17176 [DOCFIX] Update deploy dora on k8s doc
  docs/en/dora/Deploy-Alluxio-Cluster.md
  docs/en/dora/Deploy-Alluxio-Kubernetes.md
Labels: Doc Fix

#17208 Use java11 for builds
  .github/workflows/fuse_integration_tests.yml
  .github/workflows/java11_integration_tests.yml
  .github/workflows/java11_integration_tests_ft.yml
  .github/workflows/java11_integration_tests_webui.yml
  .github/workflows/java11_unit_tests.yml
  dev/github/run_checks.sh
  dev/github/run_docker.sh
  dev/github/run_tests.sh
Labels: type-devops

#17177 Show master versions in fsadmin report command
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
Labels: type-ease-of-use

#17164 Fix CopyObject writetype and unclosed outstream in InitiateMPUpload
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: type-bug

#17210 Fix dependencies conflicts thrown by trino and prestodb
  shaded/client/pom.xml
Labels: POM Change, type-bug

#17219 Remove Logserver module
  assembly/server/pom.xml
  bin/alluxio-start.sh
  bin/alluxio-stop.sh
  bin/launch-process
  conf/alluxio-env.sh.template
  conf/log4j.properties
  core/common/src/main/java/alluxio/AlluxioRemoteLogFilter.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  docs/_data/table/en/env_vars.yml
  docs/cn/deploy/Requirements.md
  docs/cn/operation/Configuration.md
  docs/cn/operation/Server-Logging.md
  docs/en/administration/Basic-Logging.md
  docs/en/administration/Remote-Logging.md
  docs/en/deploy/Requirements.md
  docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
  libexec/alluxio-config.sh
  logserver/pom.xml
  logserver/src/main/java/alluxio/logserver/AlluxioLog4jSocketNode.java
  logserver/src/main/java/alluxio/logserver/AlluxioLogServer.java
  logserver/src/main/java/alluxio/logserver/AlluxioLogServerProcess.java
  logserver/src/test/java/alluxio/logserver/AlluxioLog4jSocketNodeTest.java
  pom.xml
Labels: POM Change, type-debt, API Change

#17167 Skip ssh for localhost
  bin/alluxio-common.sh
  bin/alluxio-masters.sh
  bin/alluxio-workers.sh
Labels: area-shell, type-ease-of-use

#17232 [SMALLFIX] Remove unrelated property key
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-bug, API Change

#17231 Port changes of [#17164] to branch-2.8
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: type-bug

#17163 Update dockerfile
  integration/docker/Dockerfile
  integration/docker/Dockerfile-dev
  integration/docker/entrypoint.sh
Labels: type-feature

#17236 Improve the logic of dependency injection
  core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/dora/DoraWorkerFactory.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/modules/BlockWorkerModule.java
  core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Labels: type-feature

#17239 Fix ufs root issue when HDFS is used as UFS
  core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
Labels: type-bug

#17213 Add positioned data reader for Dora
  core/client/fs/pom.xml
  core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/dora/DoraDataReader.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/DebugLoggingTracer.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataReader.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataReaderStateMachine.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/PartialReadException.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/CancelledResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/ChannelErrorResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/DataResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/EofResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/ResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/ResponseEventContext.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/ResponseEventFactory.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/ServerErrorResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/dora/netty/event/UfsReadHeartBeatResponseEvent.java
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
  core/client/fs/src/test/java/alluxio/client/file/dora/netty/NettyDataReaderTest.java
  core/common/src/main/java/alluxio/util/io/ChannelAdapters.java
  pom.xml
Labels: POM Change, type-feature

#17241 Fix the bug that PagedDoraWorker is created twice
  core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Labels: type-bug

#17249 Prevent unrelated property keys from generating in docGen
  shell/src/main/java/alluxio/cli/docgen/ConfigurationDocGenerator.java
Labels: type-devops

#16900 Support cron timer to arrange the period heartbeat executor invoke time
  core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java
  core/common/src/main/java/alluxio/heartbeat/CronExpressionIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/FixedIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatExecutor.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatTimer.java
  core/common/src/main/java/alluxio/heartbeat/ScheduledTimer.java
  core/common/src/main/java/alluxio/heartbeat/SleepIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
  core/common/src/test/java/alluxio/heartbeat/HeartbeatContextTest.java
  core/common/src/test/java/alluxio/heartbeat/HeartbeatThreadTest.java
  core/common/src/test/java/alluxio/heartbeat/SleepingTimerForCronExpressionIntervalSupplierTest.java
  core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  core/server/master/src/main/java/alluxio/master/file/BlockIntegrityChecker.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
  core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java
  core/server/master/src/main/java/alluxio/master/file/UfsCleaner.java
  core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
  core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncer.java
  core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/JournalSpaceMonitor.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
  core/server/master/src/main/java/alluxio/master/meta/UpdateChecker.java
  core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
  core/server/master/src/main/java/alluxio/master/throttle/DefaultThrottleMaster.java
  core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java
  core/server/master/src/test/java/alluxio/master/meta/JournalSpaceMonitorTest.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockSyncMasterGroup.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/PinListSync.java
  core/server/worker/src/main/java/alluxio/worker/block/SpecificMasterBlockSync.java
  core/server/worker/src/test/java/alluxio/worker/block/PinListSyncTest.java
  core/server/worker/src/test/java/alluxio/worker/block/SpecificMasterBlockSyncTest.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  integration/fuse/src/main/java/alluxio/fuse/meta/UpdateChecker.java
  job/server/src/main/java/alluxio/master/job/JobMaster.java
  job/server/src/main/java/alluxio/worker/JobWorker.java
  job/server/src/main/java/alluxio/worker/job/command/CommandHandlingExecutor.java
  job/server/src/test/java/alluxio/job/command/CommandHandlingExecutorTest.java
  table/server/master/src/main/java/alluxio/master/table/transform/TransformManager.java
  tests/src/test/java/alluxio/client/fs/BlockMasterDeleteLostWorkerIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
  tests/src/test/java/alluxio/server/block/BlockMasterRegisterStreamIntegrationTest.java
  tests/src/test/java/alluxio/server/block/BlockWorkerRegisterStreamIntegrationTest.java
Labels: type-feature, area-master

#17185 Show the invalid default value and key name
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-bug, API Change, type-ease-of-use

#17254 Use thread context class loader instead to avoid presto exception
  core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
Labels: type-bug

#17244 Improve the performance of MountTable.getMountPoint
  core/common/src/main/java/alluxio/util/io/PathUtils.java
  core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
  core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
Labels: area-master, type-performance

#17264 Add relocation for guice avoiding dependency conflict with Presto
  shaded/client/pom.xml
Labels: POM Change, type-bug

#17022 Enable bucket cache in v2 s3 proxy
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
Labels: type-feature, API Change

#17266 Add a metric for the number of running scheduler job commands
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Labels: type-feature

#17274 Remove k8s from build tarball script in Dora
  dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-fuse-tarball.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Labels: area-build, type-devops

#17194 Fix of updating and invalidating metadata cache
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
  core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
  core/transport/src/main/proto/proto/meta/dora_meta.proto
Labels: type-bug

#17257 Fix path for URIStatus from UFSStatus
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: type-bug

#17278 Use position reader based local cache file in stream
  core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsPositionReader.java
  core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Labels: type-feature

#17205 Invalidate Cached File
  core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#17281 Disable backwards-compatibility-check on proto
  core/transport/pom.xml
Labels: POM Change, type-devops

#17277 Remove YARN related integration
  build/findbugs/findbugs-exclude.xml
  core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  integration/pom.xml
  pom.xml
  tests/src/test/java/alluxio/client/cli/fs/ConfigurationDocGeneratorTest.java
Labels: POM Change, type-debt, API Change

#17171 Fix Rocksdb thread safety using refcount(no lock)
  core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  core/common/src/main/java/alluxio/master/metastore/rocks/RocksExclusiveLockHandle.java
  core/common/src/main/java/alluxio/master/metastore/rocks/RocksSharedLockHandle.java
  core/common/src/main/java/alluxio/master/metastore/rocks/RocksUtils.java
  core/common/src/main/java/alluxio/resource/CloseableIterator.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksCheckpointed.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
  core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksBlockMetaStoreTest.java
  core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksInodeStoreTest.java
  core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksStoreTest.java
  core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksStoreTestUtils.java
  microbench/src/main/java/alluxio/inode/RocksBenchBase.java
Labels: type-bug, API Change

#17283 [DOCFIX] Update generated tables with docGen
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/common-configuration.yml
  docs/_data/table/en/master-configuration.yml
  docs/_data/table/en/master-metrics.yml
  docs/_data/table/master-configuration.csv
  docs/_data/table/master-metrics.csv
Labels: type-docs, Doc Fix

#17063 Fix the aggregate result problem in UfsIOBench
  stress/common/src/main/java/alluxio/stress/worker/IOTaskSummary.java
  stress/common/src/test/java/alluxio/stress/worker/IOTaskSummaryTest.java
Labels: type-bug

#17287 Fix relative path if mounted like s3://<BUCKET>/<DIR>
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#17285 [SMALLFIX] Remove unintended trace
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
  tests/src/test/java/alluxio/server/worker/WorkerAllMasterRegistrationTest.java
Labels: type-bug

#17280 Handle FileNotFound exception and retry getStatus() instead
  core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#17218 Use SlidingTimeWindow Moving Average for meter computation
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/worker/src/main/java/alluxio/worker/block/UfsIOManager.java
Labels: type-bug

#17284 Skip unrelated property keys from generating in docGen pt2
  shell/src/main/java/alluxio/cli/docgen/ConfigurationDocGenerator.java
Labels: type-devops

#16980 Integrate ratis-shell to the alluxio tarball
  dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
  integration/tools/ratis-shell/README.md
  integration/tools/ratis-shell/install-ratis-shell.sh
Labels: type-feature

#17294 [DOCFIX] Add newline at EOF
  integration/tools/ratis-shell/README.md
Labels: type-docs

#17292 [DOCFIX] Fix k8s doc in Dora
  docs/en/dora/Deploy-Alluxio-Kubernetes.md
Labels: type-docs, Doc Fix

#17251 Fix FileSystemMergeJournalContext related
  core/server/master/src/main/java/alluxio/master/file/FileSystemJournalEntryMerger.java
  core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemJournalEntryMergerTest.java
  core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java
Labels: type-bug

#17248 Implement Load api in Dora
  core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  core/server/common/src/main/java/alluxio/RpcUtils.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  core/transport/src/main/proto/grpc/block_worker.proto
  core/transport/src/main/proto/proto.lock
Labels: type-feature

#17182 Do not pass sync interval by default
  core/client/fs/src/main/java/alluxio/util/FileSystemOptionsUtils.java
Labels: type-bug, breaks-compatibility

#17304 Set Metadata cache TTL to 48 hours
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-feature, API Change

#17225 Add proxy register and admin command
  core/client/fs/src/main/java/alluxio/client/meta/MetaMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterClient.java
  core/common/src/main/java/alluxio/Constants.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterProxyServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/ProxyInfo.java
  core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxyProcess.java
  core/server/proxy/src/main/java/alluxio/proxy/ProxyMasterSync.java
  core/server/proxy/src/main/java/alluxio/proxy/RetryHandlingMetaMasterProxyClient.java
  core/transport/src/main/proto/grpc/block_master.proto
  core/transport/src/main/proto/grpc/common.proto
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/grpc/version.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/report/ProxyCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/ProxyCommandTest.java
Labels: type-feature, API Change, breaks-compatibility

#17302 [DOCFIX] Add Docs for dora metadata invalidation
  docs/en/dora/Metadata.md
Labels: type-docs, Doc Fix

#17311 Fix infinite recursion with RefCountedNioByteBuf.setBytes
  core/common/src/main/java/alluxio/network/protocol/databuffer/RefCountedNioByteBuf.java
  core/common/src/test/java/alluxio/network/protocol/databuffer/RefCountedNioByteBufTest.java
Labels: type-bug

#17306 Use dynamic buffering for sequential read in PositionReadFileInStream
  core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
  core/client/fs/src/test/java/alluxio/client/file/PositionReadFileInStreamTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/test/java/alluxio/ByteArrayPositionReader.java
Labels: API Change, type-performance

#17314 Improve report jobservice command
  core/common/src/main/java/alluxio/Constants.java
  core/common/src/main/java/alluxio/RuntimeConstants.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
  core/server/master/src/main/java/alluxio/master/AlluxioSimpleMasterProcess.java
  core/transport/src/main/proto/grpc/job_master.proto
  core/transport/src/main/proto/grpc/version.proto
  core/transport/src/main/proto/proto.lock
  job/client/src/main/java/alluxio/client/job/JobMasterClient.java
  job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
  job/common/src/main/java/alluxio/job/MasterWorkerInfo.java
  job/common/src/main/java/alluxio/job/wire/JobWorkerHealth.java
  job/server/src/main/java/alluxio/master/job/JobMaster.java
  job/server/src/main/java/alluxio/master/job/JobMasterClientServiceHandler.java
  job/server/src/main/java/alluxio/master/job/JobMasterWorkerServiceHandler.java
  job/server/src/main/java/alluxio/master/meta/JobMasterInfo.java
  job/server/src/main/java/alluxio/master/meta/JobMasterMasterServiceHandler.java
  job/server/src/main/java/alluxio/master/meta/JobMasterSync.java
  job/server/src/main/java/alluxio/master/meta/RetryHandlingJobMasterMasterClient.java
  job/server/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
  shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
Labels: area-shell, type-feature, API Change, area-jobservice, breaks-compatibility

#17321 Remove csi and logserver from entrypoint.sh
  integration/docker/entrypoint.sh
Labels: type-debt

#17330 Port changes of [#17225] to branch-2.8
  core/client/fs/src/main/java/alluxio/client/meta/MetaMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterClient.java
  core/common/src/main/java/alluxio/Constants.java
  core/common/src/main/java/alluxio/RuntimeConstants.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
  core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterProxyServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/ProxyInfo.java
  core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxyProcess.java
  core/server/proxy/src/main/java/alluxio/proxy/ProxyMasterSync.java
  core/server/proxy/src/main/java/alluxio/proxy/RetryHandlingMetaMasterProxyClient.java
  core/transport/src/main/proto/grpc/common.proto
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/grpc/version.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/report/ProxyCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/ProxyCommandTest.java
Labels: type-feature, API Change

#17335 Port changes of [#16521] to branch-2.8
  core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
  core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  core/common/src/main/java/alluxio/util/webui/NodeInfo.java
  core/common/src/main/java/alluxio/wire/WorkerInfo.java
  core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
  core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
  core/transport/src/main/proto/grpc/block_master.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
  webui/master/src/constants/types/INodeInfo.tsx
  webui/master/src/containers/pages/Workers/Workers.tsx
  webui/master/src/containers/pages/Workers/__snapshots__/Workers.test.tsx.snap
Labels: type-feature

#17336 Port changes of [#16618] to branch-2.8
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
Labels: type-bug

#17338 Port changes of [#17170] to branch-2.8
  core/client/fs/src/main/java/alluxio/client/block/policy/SpecificHostPolicy.java
  core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java
  core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/BasicNonByteBufferOperations.java
  shell/src/main/java/alluxio/cli/BasicOperations.java
  shell/src/main/java/alluxio/cli/TestRunner.java
Labels: type-feature, API Change

#17207 Support getting real content hash from hdfs when using getFileStatus
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  core/common/src/main/java/alluxio/underfs/options/GetFileStatusOptions.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystem.java
  underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
  underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
Labels: type-feature, API Change

#17269 Add new scheduler
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
  core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  core/server/master/src/main/java/alluxio/master/job/WorkerAssignPolicy.java
  core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  job/common/src/main/java/alluxio/scheduler/job/Job.java
  job/common/src/main/java/alluxio/scheduler/job/Task.java
  shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  tests/src/test/java/alluxio/client/cli/fs/command/LoadCommandIntegrationTest.java
Labels: type-feature, API Change

#17326 Avoid null when using BlockMasterClientPool
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Labels: type-bug

#17340 Fix listStatus from ufs
  core/common/src/main/java/alluxio/job/CopyJobRequest.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
  core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
  core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
  core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
  core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
  core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  core/transport/src/main/proto/grpc/block_worker.proto
  core/transport/src/main/proto/proto/journal/job.proto
Labels: type-bug, API Change

#17310 Improve worker decommission feature
  core/client/fs/src/main/java/alluxio/client/block/BlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/wire/WorkerWebUIOperations.java
  core/server/common/src/main/java/alluxio/executor/ExecutorServiceBuilder.java
  core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
  core/server/master/pom.xml
  core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
  core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
  core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
  core/transport/src/main/proto/grpc/block_master.proto
  core/transport/src/main/proto/grpc/common.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fs/command/DecommissionWorkerCommand.java
  shell/src/main/java/alluxio/cli/fs/command/FreeWorkerCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/command/DecommissionWorkerCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/command/EnableWorkerCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/command/WorkerAddressUtils.java
  tests/src/test/java/alluxio/client/fs/io/FileInStreamDecommissionIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/io/FileOutStreamDecommissionIntegrationTest.java
Labels: POM Change, type-feature, type-devops

#17325 Make capacity command show worker state
  core/common/src/main/java/alluxio/master/WorkerState.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
  shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
Labels: type-feature

#17346 Port change [#17310] to branch-2.8
  core/client/fs/src/main/java/alluxio/client/block/BlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/wire/WorkerWebUIOperations.java
  core/server/common/src/main/java/alluxio/executor/ExecutorServiceBuilder.java
  core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
  core/server/master/pom.xml
  core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  core/server/master/src/main/java/alluxio/master/block/meta/WorkerState.java
  core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
  core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
  core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
  core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
  core/transport/src/main/proto/grpc/block_master.proto
  core/transport/src/main/proto/grpc/common.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fsadmin/command/DecommissionWorkerCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/command/EnableWorkerCommand.java
  shell/src/main/java/alluxio/cli/fsadmin/command/WorkerAddressUtils.java
  tests/src/test/java/alluxio/client/fs/io/FileInStreamDecommissionIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/io/FileOutStreamDecommissionIntegrationTest.java
Labels: POM Change, type-feature

#17349 Port changes of [#17325] to branch-2.8
  core/common/src/main/java/alluxio/master/WorkerState.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
  core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
  shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
  shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
Labels: type-feature

#17353 Revert "Improve the performance of MountTable.getMountPoint"
  core/common/src/main/java/alluxio/util/io/PathUtils.java
  core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
  core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
Labels: type-performance

#17356 Reduce redundant calls in getObject of S3 API
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
Labels: type-feature

#17351 Fix the Eof error when parse the Complete MPU
  core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: type-bug
