Repository Alluxio/alluxio, pull requests merged in 2023-11, with the labels that each got.

#18350 Change the metrics registry and some metrics
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
Labels: type-feature

#18352 Move job related operations to DoraCacheFileSystem
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
Labels: type-bug

#18181 Refactor PagedDoraWorker by injecting MetaManager and UfsManager
  dora/core/common/src/main/java/alluxio/underfs/UfsManager.java
  dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/DataServerFactory.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/DoraMetaManagerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/grpc/DoraWorkerClientServiceHandlerTest.java
Labels: type-code-quality

#18359 Fix the bug that command line doesn't support regx file filter
  cli/src/alluxio.org/cli/cmd/job/load.go
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-bug

#17780 Support dynamic unset value
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  shell/src/main/java/alluxio/cli/fsadmin/command/UnsetConfCommand.java
  tests/src/test/java/alluxio/client/cli/fsadmin/command/UpdateConfIntegrationTest.java
Labels: type-feature

#18358 Fix file mtime display when ufs mtime is not null
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: area-ufs, type-bug

#18371 Use correct audit log configuration in proxy
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-bug

#18339 Disable xatter in PagedDoraWorker test
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-debt, type-code-quality

#18334 Fix getConf bugs when it comes across warning
  bin/alluxio-masters.sh
  bin/alluxio-monitor.sh
Labels: type-bug

#18168 Fix UT readMultipleFiles in LocalCacheFileInStreamTest
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Labels: type-bug, type-code-quality

#18362 Improve distributed load
  .gitignore
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
  dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadSubTask.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/MembershipManagerWorkerProvider.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
Labels: type-feature

#18374 [SMALLFIX] Allow extension on `UfsManager.tryUfsFileSystem()`
  dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
Labels: type-code-quality

#18326 Add direct access option to avoid caching certain paths
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/common/src/main/java/alluxio/conf/ConfigurationBuilder.java
  core/common/src/main/java/alluxio/conf/OverlayConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  tests/src/test/java/alluxio/client/fs/DirectAccessIntegrationTest.java
Labels: type-feature

#18383 Fix COS/OSS/OBS iterative listing
  dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-feature

#18267 Print warning messages for stale open handle instead of removing it
  dora/core/common/src/main/java/alluxio/worker/dora/OpenFileHandle.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraOpenFileHandleContainer.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#18336 Fix cosn ufs cannot find class
  dora/underfs/cosn/pom.xml
Labels: type-bug

#18203 Change logging level in NettyChannelPool
  dora/core/common/src/main/java/alluxio/network/netty/NettyChannelPool.java
Labels: type-code-quality

#18387 Add a configurable DLQ capacity of avoid OOM
  dora/core/client/fs/src/main/java/alluxio/client/file/AdaptivePrefetchCachePolicy.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
Labels: type-feature

#18388 Fix the issue to get a tag of a non-existed in OSS/COS
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/AlluxioCosException.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
  dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSUnderFileSystemTest.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-bug

#18391 Fix NPE
  dora/core/server/master/src/main/java/alluxio/master/job/LoadSubTask.java
Labels: type-bug

#18386 Fix chaotic chinese characters with golang cli commands
  cli/src/alluxio.org/cli/env/command.go
Labels: type-bug

#18380 [SMALLFIX] Remove unused objects initialize
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyBucketTask.java
Labels: type-code-quality

#18101 Improve UpdateChecker
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/util/CommonUtils.java
  dora/core/common/src/main/java/alluxio/util/UpdateCheckUtils.java
  dora/core/common/src/test/java/alluxio/check/UpdateCheckTest.java
  dora/core/common/src/test/java/alluxio/util/UpdateCheckUtilsTest.java
  dora/core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  dora/core/server/master/src/main/java/alluxio/master/meta/MasterUpdateChecker.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/integration/fuse/src/main/java/alluxio/fuse/meta/FuseUpdateChecker.java
  dora/integration/fuse/src/main/java/alluxio/fuse/meta/UpdateChecker.java
  dora/integration/fuse/src/main/java/alluxio/fuse/options/FuseCliOptions.java
  dora/integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
  dora/integration/fuse/src/test/java/alluxio/fuse/meta/FuseUpdateCheckerTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/options/FuseCliOptionsTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractFuseFileSystemTest.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/AbstractFuseFileSystemTest.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/FuseEndToEndTest.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/readonly/AbstractFuseFileSystemTest.java
Labels: type-feature

#18377 Fix StressWorkerBench with remote worker policy
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/RemoteWorkerList.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-bug

#18392 Fix integration tests again
  .github/workflows/java8_integration_tests.yml
  .github/workflows/java8_integration_tests_ft.yml
  .github/workflows/java8_integration_tests_webui.yml
  dev/github/run_tests.sh
Labels: type-devops

#18376 [SMALLFIX] Fix broken ChmodCommandIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/ChmodCommandIntegrationTest.java
Labels: type-code-quality

#18398 Use generic Exception to catch all exceptions in getStatus()
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: type-bug

#18397 Merge master-2.x commits 2023/07/01~2023/11/08 into main
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsInputStream.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
  dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/tests/integration/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-sync

#18403 Fix the NPE in COSUnderFileSystem
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
Labels: type-bug

#18385 Fix empty block location
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
Labels: type-bug

#18401 Remove malformed empty page files on access
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
Labels: type-bug

#18408 Replace the FOLDER_SUFFIX from "_$folder$" to "/" in OSS UFS
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
  dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemTest.java
Labels: type-debt

#18407 Fix stress worker bench remote only policy not working
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-bug

#18337 Change file exist exception to runtime exception in PagedDoraWorker
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraMkdirCommandIntegrationTest.java
Labels: type-bug

#18176 Translate Introduction
  docs/cn/introduction/introduction.md
Labels: type-docs

#18389 Improve page loading performance
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-performance

#18263 Allow rename() to overwrite, fix an uncaught ex and reenable UT
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/tests/integration/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
Labels: type-bug

#18349 [SMALLFIX] Remove invalid Property WORKER_FUSE_ENABLED
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-code-quality

#18351 Add call points of the new metrics
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCachePositionReader.java
  dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyReadHandlerStateMachine.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/WriteRequestContext.java
Labels: type-feature

#18310 Update README.md
  README.md
Labels: type-docs

#18241 Clean up fuse unmount workflow
  dora/integration/fuse/bin/alluxio-fuse
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
  dora/integration/fuse/src/main/java/alluxio/fuse/FuseSignalHandler.java
  dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
  dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/FuseFileSystem.java
  dora/integration/jnifuse/native/src/main/native/libjnifuse/jnifuse_fs.cc
  dora/integration/jnifuse/native/src/main/native/libjnifuse/jnifuse_fs.h
  dora/integration/jnifuse/native/src/main/native/libjnifuse/jnifuse_helper.cc
  dora/integration/jnifuse/native/src/main/native/libjnifuse/jnifuse_impls.cc
  dora/integration/jnifuse/native/src/main/native/libjnifuse/jnifuse_impls.h
  dora/integration/jnifuse/native/src/main/native/libjnifuse/operation.cc
  dora/integration/jnifuse/native/src/main/native/libjnifuse/operation.h
  dora/integration/jnifuse/native/src/main/resources/libjnifuse.dylib
  dora/integration/jnifuse/native/src/main/resources/libjnifuse.so
  dora/integration/jnifuse/native/src/main/resources/libjnifuse3.so
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/hdfs3/FuseHdfsIntegrationTest.java
Labels: type-ease-of-use

#18399 Add direct access option to avoid caching certain paths
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/common/src/main/java/alluxio/conf/ConfigurationBuilder.java
  core/common/src/main/java/alluxio/conf/OverlayConfiguration.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  tests/src/test/java/alluxio/client/fs/DirectAccessIntegrationTest.java
Labels: type-feature

#18412 Fix the issue when mount an empty oss bucket
  dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Labels: type-bug

#18416 Respond with unsupported message when GetBucketLocation
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-bug

#18425 Fix the bug that HdfsUfsStatusIterator returns wrong path
  dora/core/server/master/src/main/java/alluxio/master/job/UfsStatusIterable.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
Labels: type-bug

#18424 Fix the bug that HdfsUfsStatusIterator returns wrong path
  dora/core/server/master/src/main/java/alluxio/master/job/UfsStatusIterable.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
Labels: type-bug

#18415 Fix standby master don't remove syncPoint correctly issue
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
Labels: type-bug

#18429 Fix the bug that HDFS iterator doesn't work
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
Labels: type-bug

#18430 Fix the bug that HDFS iterator doesn't work
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
Labels: type-bug

#18420 Fix the issue in COSUnderFileSystem
  underfs/cos/src/main/java/alluxio/underfs/cos/AlluxioCosException.java
  underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
Labels: type-bug

#18422 Fix COS and OSS UFS
  underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
  underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
  underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemTest.java
Labels: type-bug

#18437 Fix consistent hash policy returns stale worker addresses
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLsCommandIntegrationTest.java
Labels: type-bug

#18440 Load content hash as the etag of the object when the UFS is S3
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/common/src/main/java/alluxio/Constants.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/main/java/alluxio/master/file/mdsync/DefaultSyncProcess.java
Labels: type-feature

#18446 Load content hash as the etag of the object when the UFS is S3
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/common/src/main/java/alluxio/Constants.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/main/java/alluxio/master/file/mdsync/DefaultSyncProcess.java
Labels: type-feature

#18435 [Security] Fix log4j 1.x CVE-2019-17571 critical vulnerability
  core/common/pom.xml
  core/common/src/main/java/alluxio/util/LogUtils.java
  core/server/master/src/test/java/alluxio/master/metastore/InodeStoreBench.java
  integration/tools/hms/pom.xml
  logserver/pom.xml
  pom.xml
  table/server/underdb/glue/pom.xml
  table/server/underdb/hive/pom.xml
  underfs/cephfs-hadoop/pom.xml
Labels: type-code-quality

#18450 Fix duplicated class and resources in presto mvn build
  dora/shaded/client/pom.xml
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLsCommandIntegrationTest.java
Labels: type-bug
