Repository Alluxio/alluxio, pull requests merged in 2023-06, with the labels that each got.

#17524 Fix async submit task
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Labels: type-bug

#17515 Fix job update in journal
  dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/LoadJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
Labels: type-bug

#17535 [SMALLFIX] Fix proto format
  common/transport/src/main/proto/proto/journal/job.proto
Labels: type-code-quality

#17527 Extensible Dockerfile
  integration/docker/.dockerignore
  integration/docker/Dockerfile
  integration/docker/Dockerfile-base
  integration/docker/Dockerfile-dev
  integration/docker/conf/alluxio-env.sh.template
  integration/docker/conf/alluxio-site.properties.template
Labels: type-devops

#17523 Migrate policy related proto to dora
  common/transport/src/main/proto/grpc/policy_master.proto
  common/transport/src/main/proto/proto/journal/journal.proto
  common/transport/src/main/proto/proto/journal/policy.proto
  dora/core/common/src/main/java/alluxio/Constants.java
  dora/core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java
  dora/core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
Labels: type-feature

#17521 Fix copy progress
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
Labels: type-debt

#17531 Update configuration and property key
  docs/_data/table/client-metrics.csv
  docs/_data/table/cluster-management-configuration.csv
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/client-metrics.yml
  docs/_data/table/en/cluster-management-configuration.yml
  docs/_data/table/en/common-configuration.yml
  docs/_data/table/en/master-configuration.yml
  docs/_data/table/en/master-metrics.yml
  docs/_data/table/en/process-metrics.yml
  docs/_data/table/en/user-configuration.yml
  docs/_data/table/en/worker-configuration.yml
  docs/_data/table/en/worker-metrics.yml
  docs/_data/table/master-configuration.csv
  docs/_data/table/master-metrics.csv
  docs/_data/table/process-metrics.csv
  docs/_data/table/user-configuration.csv
  docs/_data/table/worker-configuration.csv
  docs/_data/table/worker-metrics.csv
  docs/cn/reference/Properties-List.md
  docs/en/reference/Properties-List.md
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-bug

#17528 [DOCFIX] Update overview doc and download links
  docs/en/Overview.md
  docs/en/overview/Getting-Started.md
Labels: type-docs

#17542 Fix policy service version
  dora/core/common/src/main/java/alluxio/Constants.java
  dora/core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
Labels: type-bug

#17537 Add get functions in S3 underfs
  dora/core/common/src/main/java/alluxio/underfs/options/CreateOptions.java
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-feature

#17540 Port [#17358] to main
  common/transport/src/main/proto/grpc/raft_journal.proto
  common/transport/src/main/proto/proto.lock
Labels: type-code-quality

#17539 [DOCFIX] Update k8s doc
  docs/en/cloud/Alibaba-Cloud-ACK.md
  docs/en/deploy/Deploy-Alluxio-Kubernetes.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
  docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
  docs/en/kubernetes/Spark-On-Kubernetes.md
Labels: type-docs

#17532 Add CLI as a golang project
  bin/cli.sh
  build/cli/build-cli.sh
  cli/src/alluxio.org/cli/bin/.gitignore
  cli/src/alluxio.org/cli/cmd/conf/conf.go
  cli/src/alluxio.org/cli/cmd/conf/get.go
  cli/src/alluxio.org/cli/cmd/conf/log.go
  cli/src/alluxio.org/cli/env/command.go
  cli/src/alluxio.org/cli/env/env.go
  cli/src/alluxio.org/cli/env/env_vars.go
  cli/src/alluxio.org/cli/env/props.go
  cli/src/alluxio.org/cli/env/service.go
  cli/src/alluxio.org/cli/launch/launch.go
  cli/src/alluxio.org/cli/main.go
  cli/src/alluxio.org/go.mod
  cli/src/alluxio.org/go.sum
  cli/src/alluxio.org/log/log.go
  pom.xml
Labels: type-ease-of-use

#17541 Add command to build docker images
  dev/scripts/src/alluxio.org/build/artifact/artifact.go
  dev/scripts/src/alluxio.org/build/cmd/docker.go
  dev/scripts/src/alluxio.org/build/cmd/flags.go
  dev/scripts/src/alluxio.org/build/docker.yml
  dev/scripts/src/alluxio.org/build/main.go
Labels: type-devops

#17530 [DOCFIX] Define CLI conventions in README
  cli/README.md
Labels: type-docs

#17552 Fix LocalPageStore NPE
  core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
Labels: type-bug

#17544 Remove some noisy expected page not find log
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/PartialReadException.java
Labels: type-bug

#17458 Refactor dora worker metastore and remove on-heap cache
  dora/core/common/src/main/java/alluxio/AlluxioURI.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/common/src/main/java/alluxio/rocks/RocksStore.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/microbench/src/main/java/alluxio/dora/meta/DoraMetaBench.java
  dora/microbench/src/main/java/alluxio/dora/meta/DoraMetaBenchBase.java
Labels: type-performance

#17525 Add FilePredicates for jobs
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/FilePredicate.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/FilePredicateFactory.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/TimePredicate.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/interval/Interval.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/interval/IntervalSet.java
  dora/core/server/master/src/main/java/alluxio/master/predicate/interval/IntervalUtils.java
  dora/core/server/master/src/main/resources/META-INF/services/alluxio.master.predicate.FilePredicateFactory
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/predicate/TimePredicateTest.java
  dora/core/server/master/src/test/java/alluxio/master/predicate/interval/IntervalSetTest.java
  dora/core/server/master/src/test/java/alluxio/master/predicate/interval/IntervalTest.java
  dora/core/server/master/src/test/java/alluxio/master/predicate/interval/IntervalUtilsTest.java
Labels: type-feature

#17562 Fix the bug that blocked when writing an empty file
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataWriter.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraReadIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/AbstractStreamTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/OutStreamTest.java
  dora/tests/src/test/java/alluxio/client/hadoop/FileSystemUriIntegrationTest.java
  dora/tests/src/test/java/alluxio/server/worker/PagedBlockStoreIntegrationTest.java
Labels: type-bug

#17565 Add mount table support for move
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
  dora/tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
Labels: type-feature

#17556 Fix LocalPageStore NPE
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
Labels: type-bug

#17569 Add journal commands to CLI
  cli/src/alluxio.org/cli/cmd/journal/backup.go
  cli/src/alluxio.org/cli/cmd/journal/checkpoint.go
  cli/src/alluxio.org/cli/cmd/journal/format.go
  cli/src/alluxio.org/cli/cmd/journal/journal.go
  cli/src/alluxio.org/cli/cmd/journal/read.go
  cli/src/alluxio.org/cli/env/command.go
Labels: area-shell, type-feature

#17570 Add quorum commands to CLI
  cli/src/alluxio.org/cli/cmd/quorum/elect.go
  cli/src/alluxio.org/cli/cmd/quorum/info.go
  cli/src/alluxio.org/cli/cmd/quorum/quorum.go
  cli/src/alluxio.org/cli/cmd/quorum/remove.go
  cli/src/alluxio.org/cli/main.go
Labels: area-shell, type-feature

#17011 [DOCFIX]Update cn version of docs/_data/table/cn/master-metrics.yml
  docs/_data/table/cn/master-metrics.yml
Labels: type-docs, Doc Fix, stale

#16932 [DOCFIX] Update cn version of OSS doc
  docs/cn/ufs/OSS.md
Labels: type-docs, Doc Fix, stale

#16929 [DOCFIX] Update cn version of Azure-Data-Lake-Gen2 doc
  docs/cn/ufs/Azure-Data-Lake-Gen2.md
  docs/cn/ufs/Azure-Data-Lake.md
Labels: type-docs, Doc Fix, stale

#16920 [DOCFIX] Update cn version of Deep-Leaning doc
  docs/cn/solutions/Deep-Learning.md
Labels: type-docs, Doc Fix, stale

#17545 Add delete/rename/createDirectory RPC
  common/transport/src/main/proto/grpc/block_worker.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/AbstractFuseDoraTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/FuseFileSystemMetadataTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/InOrOutStreamOutTest.java
Labels: type-feature

#17529 [DOCFIX] Update FUSE SDK docs
  docs/cn/compute/Tensorflow.md
  docs/cn/kubernetes/Running-Alluxio-On-Kubernetes.md
  docs/en/administration/StressBench.md
  docs/en/api/Java-API.md
  docs/en/api/POSIX-API-local-cache.md
  docs/en/api/POSIX-API.md
  docs/en/compute/Tensorflow.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/fuse-sdk/Advanced-Tuning.md
  docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
  docs/en/fuse-sdk/FUSE-SDK.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache.md
  docs/en/fuse-sdk/Local-Data-Cache.md
  docs/en/fuse-sdk/Local-Metadata-Cache.md
  docs/en/fuse-sdk/Overview.md
  docs/en/operation/Metrics-System.md
  docs/en/solutions/Deep-Learning.md
Labels: type-docs

#17052 Fix some incorrect code in WorkerWebUILogs
  core/common/src/main/java/alluxio/wire/WorkerWebUILogs.java
Labels: type-bug

#17204 Add some logs when the standby master send a heartbeat request
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
Labels: type-code-quality

#17202 [DOCFIX]Improve annotations in DefaultMetaMaster add some @links
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
Labels: type-docs

#17578 Adjust the details of the dora writing process for extension
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataWriter.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/DoraOutStream.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteRequestContext.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/WriteRequest.java
Labels: type-feature

#17394 Bump ratis version to 2.5.1
  core/server/common/pom.xml
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalUtils.java
  core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
  core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
  tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
Labels: POM Change, type-debt, type-code-quality

#17581 [DOCFIX] Remove table operations from user CLI docs
  docs/en/operation/User-CLI.md
Labels: type-docs

#17586 Modify interface for extension
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-feature

#17587 Port [#17251] to branch-2.10
  core/server/master/src/main/java/alluxio/master/file/FileSystemJournalEntryMerger.java
  core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemJournalEntryMergerTest.java
  core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java
Labels: type-bug

#17538 Improve dora load job
  common/transport/src/main/proto/grpc/block_worker.proto
  common/transport/src/main/proto/grpc/file_system_master.proto
  common/transport/src/main/proto/proto/journal/job.proto
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/underfs/UfsStatus.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/common/src/test/java/alluxio/ConfigurationTestUtils.java
  dora/core/common/src/test/java/alluxio/underfs/UfsFileStatusTest.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Task.java
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/AbstractDoraFileSystemShellTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/AbstractDoraShellIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraPositionReaderIntegrationTest.java
Labels: type-feature, type-performance

#17564 Fix corrupted block causing reads to fail
  core/common/src/main/java/alluxio/exception/runtime/BlockDoesNotExistRuntimeException.java
  core/common/src/main/java/alluxio/util/io/FileUtils.java
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
  tests/src/test/java/alluxio/server/tieredstore/TieredStoreBlockCorruptionIntegrationTest.java
Labels: type-bug, area-worker

#17596 Fix a bug that creates 0 byte block file mistakenly
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-bug, area-worker

#17595 Fix corrupted block causing reads to fail; Port [#17564] to branch-2.9
  core/common/src/main/java/alluxio/exception/runtime/BlockDoesNotExistRuntimeException.java
  core/common/src/main/java/alluxio/util/io/FileUtils.java
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
  tests/src/test/java/alluxio/server/tieredstore/TieredStoreBlockCorruptionIntegrationTest.java
Labels: type-bug, area-worker

#17590 Modify interface for extension
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/InOrOutStreamOutTest.java
Labels: type-feature

#17568 Update shell of mount ramdisk
  bin/alluxio-common.sh
Labels: type-bug

#17600 Improve build-artifact to print mvn error to stderr
  dev/scripts/src/alluxio.org/build/cmd/build.go
Labels: type-devops

#17580 Add fs subcommand to CLI
  cli/src/alluxio.org/cli/cmd/fs/cat.go
  cli/src/alluxio.org/cli/cmd/fs/checksum.go
  cli/src/alluxio.org/cli/cmd/fs/count.go
  cli/src/alluxio.org/cli/cmd/fs/cp.go
  cli/src/alluxio.org/cli/cmd/fs/du.go
  cli/src/alluxio.org/cli/cmd/fs/fs.go
  cli/src/alluxio.org/cli/cmd/fs/head.go
  cli/src/alluxio.org/cli/cmd/fs/location.go
  cli/src/alluxio.org/cli/cmd/fs/ls.go
  cli/src/alluxio.org/cli/cmd/fs/mkdir.go
  cli/src/alluxio.org/cli/cmd/fs/mv.go
  cli/src/alluxio.org/cli/cmd/fs/rm.go
  cli/src/alluxio.org/cli/cmd/fs/stat.go
  cli/src/alluxio.org/cli/cmd/fs/tail.go
  cli/src/alluxio.org/cli/cmd/fs/test.go
  cli/src/alluxio.org/cli/cmd/fs/touch.go
  cli/src/alluxio.org/cli/env/command.go
  cli/src/alluxio.org/cli/launch/launch.go
  cli/src/alluxio.org/cli/main.go
Labels: area-shell, type-feature

#17606 Make mount command work in dora
  dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
Labels: type-feature

#17604 Fix move job picking workers
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
Labels: type-bug

#17608 Update job tasks
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#17602 Fix a test bug & Add no-cache cases
  dora/tests/src/test/java/alluxio/client/fs/UnderStorageReadIntegrationTest.java
Labels: type-code-quality

#17536 [DOCFIX] Improve desc on write type THROUGH
  docs/en/overview/Architecture.md
Labels: type-docs

#17613 Modify for GroupMappingService extension
  dora/core/common/src/main/java/alluxio/security/group/GroupMappingService.java
Labels: type-feature

#17614 [DOCFIX] Generate doc tables and remove unused file
  docs/_data/table/client-metrics.csv
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/client-metrics.yml
  docs/_data/table/en/common-configuration.yml
  docs/_data/table/en/user-configuration.yml
  docs/_data/table/user-configuration.csv
  docs/_data/table/worker-configuration.csv
  dora/shell/src/main/java/alluxio/cli/docgen/ConfigurationDocGenerator.java
Labels: type-docs

#17582 Invalidate cached pages from PagingStore by fileId
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageMetaStore.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockMetaStore.java
  dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
  dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreDir.java
  dora/core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
Labels: type-feature

#17603 Remove mount check when starting alluxio if users do not intend to mount
  bin/alluxio-start.sh
Labels: type-ease-of-use

#17620 Hookup permission check for scheduler jobs
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#17579 Implement HTTP server for providing the get page RESTful API
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  dora/core/common/src/main/java/alluxio/file/NettyBufTargetBuffer.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerInitializer.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/BlockWorkerModule.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Labels: type-feature

#17618 Add getOpenFileHandleContainer method
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#17624 Remove the doc check in pr build
  dev/scripts/src/alluxio.org/check-docs/main.go
Labels: type-devops

#17625 Add get mount id to worker master rpc
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
Labels: type-feature

#17626 Expose get job state to scheduler
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Labels: type-feature

#17215 [DOCFIX] Fix some descriptions related to the FileSystemMaster module
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
  core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Labels: type-code-quality

#17298 Support SteppingThreadSleeper
  core/common/src/main/java/alluxio/heartbeat/CronExpressionIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/FixedIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/SleepIntervalSupplier.java
  core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
  core/common/src/main/java/alluxio/time/Sleeper.java
  core/common/src/main/java/alluxio/time/SteppingThreadSleeper.java
  core/common/src/test/java/alluxio/heartbeat/SleepingTimerForCronExpressionIntervalSupplierTest.java
  core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java
Labels: type-feature

#17593 Delete unrecginized page file and handle empty result from getPageInfo()
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageInfo.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreDir.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
  dora/tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
Labels: type-feature

#17598 Simplify `elect` command
  dora/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  dora/core/server/master/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
  dora/core/server/master/src/main/java/alluxio/master/journal/JournalMaster.java
  dora/core/server/master/src/main/java/alluxio/master/journal/JournalMasterClientServiceHandler.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumElectCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/QuorumCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestTransferLeadership.java
Labels: type-debt, type-code-quality

#15748 Fix S3 UFS executor service thread leak
  underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-bug

#17630 Enable tiered category hierarchy/dropdowns for docs
  docs/_config.yml
  docs/_data/menu-en.yml
  docs/_includes/sitemap.html
  docs/_layouts/global.html
Labels: type-docs

#17631 Fix move job process response
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
Labels: type-bug

#17632 Throw exception when there's error deleting file
  dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Labels: type-bug

#17634 [DOCFIX] Fix EN docs menu
  docs/_data/menu-en.yml
Labels: type-docs

#17635 [DOCFIX] Update menu-en for docs
  docs/_data/menu-en.yml
Labels: type-docs

#17585 Fix copyFromLocal while dest path is endsWith a `/`
  dora/core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  dora/core/common/src/test/java/alluxio/AlluxioURITest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/CpCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java
Labels: type-bug

#17633 Add script to selectively copy jars to lib/
  build/extjar/copy_jars.sh
  dora/.gitignore
  dora/underfs/pom.xml
  pom.xml
Labels: type-devops

#17558 Fix fuse position read bug
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
Labels: type-bug

#17643 Revert "Add script to selectively copy jars to lib/"
  build/extjar/copy_jars.sh
  dora/.gitignore
  dora/underfs/pom.xml
  pom.xml
Labels: type-devops

#17640 Add support of loading a single file in DoraLoadCommand
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
Labels: type-feature

#17648 Improve .gitignore
  .gitignore
Labels: type-code-quality

#17654 [DOCFIX] Fix link problem in the docs
  docs/_includes/sitemap.html
  docs/en/api/S3-API.md
Labels: type-docs

#17653 Set dora ufs root to local underFSStorage directory
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-ease-of-use, area-configuration

#17656 Set page store dir and empty UFS before tests
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Labels: type-bug

#17657 Modify hdfs ufs interface for extension
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-feature

#17622 Add switch for client UFS fallback
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
  dora/core/client/fs/src/test/java/alluxio/client/file/ufs/AbstractUfsStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
  dora/integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractFuseFileSystemTest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
  dora/tests/src/test/java/alluxio/client/cli/job/CancelCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/LeaderCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/StatCommandTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/AbstractFuseFileSystemTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/FuseEndToEndTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/readonly/AbstractFuseFileSystemTest.java
Labels: type-feature, area-configuration

#17662 Fix the bug that dora worker is blocked by http server
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServer.java
Labels: type-bug

#17655 Add check url with actual path functionality to check-docs
  dev/scripts/src/alluxio.org/check-docs/main.go
Labels: type-devops

#17669 Refactor docGen for extension
  dora/shell/src/main/java/alluxio/cli/DocGenerator.java
Labels: type-feature

#17665 Fix concurrent submit job
  dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Labels: type-bug

#17664 Include job id into progress report
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
Labels: type-bug

#17666 Fix local cache metrics in log
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Labels: type-debt

#17680 Add extra explicit loaded class for filesystem
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-feature

#17683 Fix the bug that most commands fail after disable UFS fall back
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
  dora/tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/JobServiceFaultToleranceShellTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/HelpCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/TestCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/GetCmdStatusCommandTest.java
Labels: type-bug

#17651 Rename the switch for dora
  dora/core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCachePositionReader.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/WorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerFactory.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  dora/minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/AbstractDoraShellIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraPositionReaderIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/io/DoraReadIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/AbstractFuseDoraTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/readonly/AbstractFuseDoraReadOnlyTest.java
  dora/tests/src/test/java/alluxio/server/worker/PagedBlockStoreIntegrationTest.java
Labels: type-code-quality

#17678 Remove the switch flag for dora write
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
  dora/core/common/src/main/java/alluxio/Constants.java
Labels: type-bug

#17690 Fix load command
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Labels: type-bug

#17691 Fix getInStream worker net address
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
Labels: type-bug

#17671 Clean up scheduler job informations when stop
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
Labels: type-bug

#17693 [DOCFIX] Move generated docs to separate dir
  docs/_data/generated/client-metrics.csv
  docs/_data/generated/cluster-management-configuration.csv
  docs/_data/generated/cluster-metrics.csv
  docs/_data/generated/common-configuration.csv
  docs/_data/generated/en/client-metrics.yml
  docs/_data/generated/en/cluster-metrics.yml
  docs/_data/generated/en/common-configuration.yml
  docs/_data/generated/en/fuse-metrics.yml
  docs/_data/generated/en/master-configuration.yml
  docs/_data/generated/en/master-metrics.yml
  docs/_data/generated/en/process-metrics.yml
  docs/_data/generated/en/proxy-metrics.yml
  docs/_data/generated/en/security-configuration.yml
  docs/_data/generated/en/server-metrics.yml
  docs/_data/generated/en/user-configuration.yml
  docs/_data/generated/en/worker-configuration.yml
  docs/_data/generated/en/worker-metrics.yml
  docs/_data/generated/fuse-metrics.csv
  docs/_data/generated/master-configuration.csv
  docs/_data/generated/master-metrics.csv
  docs/_data/generated/process-metrics.csv
  docs/_data/generated/proxy-metrics.csv
  docs/_data/generated/security-configuration.csv
  docs/_data/generated/server-metrics.csv
  docs/_data/generated/user-configuration.csv
  docs/_data/generated/worker-configuration.csv
  docs/_data/generated/worker-metrics.csv
  docs/en/reference/Metrics-List.md
  docs/en/reference/Properties-List.md
  dora/shell/src/main/java/alluxio/cli/docgen/ConfigurationDocGenerator.java
  dora/shell/src/main/java/alluxio/cli/docgen/MetricsDocGenerator.java
Labels: type-docs

#17677 Show stacktrace on maven error
  pom.xml
Labels: type-ease-of-use

#17695 Throw exception if overwrite
  dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
Labels: type-feature

#17697 Fix MountCommand
  dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
Labels: type-bug

#17682 Add the exists and setAttribute client-worker RPCs
  common/transport/src/main/proto/grpc/block_worker.proto
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: type-feature

#17698 Add client jar customization to generate tarball script
  dev/scripts/src/alluxio.org/build/cmd/build.go
  dev/scripts/src/alluxio.org/build/cmd/profile.go
  dev/scripts/src/alluxio.org/build/cmd/tarball.go
  dev/scripts/src/alluxio.org/build/profiles.yml
Labels: type-feature

#17701 Refactor repo and command pkgs in go scripts
  dev/scripts/src/alluxio.org/build/artifact/artifact-methods.go
  dev/scripts/src/alluxio.org/build/cmd/build.go
  dev/scripts/src/alluxio.org/build/cmd/docker.go
  dev/scripts/src/alluxio.org/build/cmd/flags.go
  dev/scripts/src/alluxio.org/build/cmd/tarball.go
  dev/scripts/src/alluxio.org/build/cmd/ufs.go
  dev/scripts/src/alluxio.org/build/cmd/version.go
  dev/scripts/src/alluxio.org/common/command/command.go
  dev/scripts/src/alluxio.org/common/repo/repo.go
Labels: type-devops

#17702 Update docker artifact names
  dev/scripts/src/alluxio.org/build/cmd/docker.go
  dev/scripts/src/alluxio.org/build/docker.yml
Labels: type-devops

#17658 Store file metadata on file completion & setAttributes
  dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
  dora/tests/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
Labels: type-feature

#17707 Make UpdateMountCommand and UnmountCommand behave like MountCommand
  dora/shell/src/main/java/alluxio/cli/fs/command/UnmountCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/UpdateMountCommand.java
Labels: type-bug, type-code-quality

#17646 Fix the issue of not being able to display third level files
  dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
Labels: type-bug

#17704 Apply RocksDB thread safety changes to Dora
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  dora/core/common/src/main/java/alluxio/master/metastore/rocks/RocksExclusiveLockHandle.java
  dora/core/common/src/main/java/alluxio/master/metastore/rocks/RocksSharedLockHandle.java
  dora/core/common/src/main/java/alluxio/master/metastore/rocks/RocksUtils.java
  dora/core/common/src/main/java/alluxio/resource/CloseableIterator.java
  dora/core/server/common/src/main/java/alluxio/rocks/RocksCheckpointed.java
  dora/core/server/common/src/main/java/alluxio/rocks/RocksStore.java
  dora/core/server/common/src/test/java/alluxio/rocks/RocksStoreTest.java
  dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
  dora/core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  dora/core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksBlockMetaStoreTest.java
  dora/core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksInodeStoreTest.java
  dora/core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksStoreTestUtils.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
  dora/microbench/src/main/java/alluxio/inode/RocksBenchBase.java
  dora/tests/src/test/java/alluxio/server/worker/WorkerAllMasterRegistrationTest.java
Labels: type-feature

#17709 Update pom to selectively copy lib jars
  build/lib/copy_jars.sh
  dora/integration/tools/hms/pom.xml
  dora/integration/tools/validation/pom.xml
  dora/table/server/underdb/glue/pom.xml
  dora/table/server/underdb/hive/pom.xml
  dora/table/server/underdb/pom.xml
  dora/underfs/abfs/pom.xml
  dora/underfs/adl/pom.xml
  dora/underfs/cephfs-hadoop/pom.xml
  dora/underfs/cephfs/pom.xml
  dora/underfs/cos/pom.xml
  dora/underfs/cosn/pom.xml
  dora/underfs/gcs/pom.xml
  dora/underfs/hdfs/pom.xml
  dora/underfs/kodo/pom.xml
  dora/underfs/local/pom.xml
  dora/underfs/obs/pom.xml
  dora/underfs/oss/pom.xml
  dora/underfs/ozone/pom.xml
  dora/underfs/pom.xml
  dora/underfs/s3a/pom.xml
  dora/underfs/swift/pom.xml
  dora/underfs/wasb/pom.xml
  dora/underfs/web/pom.xml
  lib/README
Labels: type-devops

#17713 Fix job log
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
Labels: type-bug

#17714 [DOCFIX] Fix Language dropdown bug in new layout in os and add pr check
  dev/scripts/src/alluxio.org/check-docs/main.go
  docs/_data/menu-en.yml
  docs/en/api/Java-API.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/fuse-sdk/Overview-Fuse-Sdk.md
  docs/en/operation/Metrics-System.md
Labels: type-docs

#17700 Create UTs to listing objects of S3 proxy
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  dora/tests/src/test/java/alluxio/client/rest/ListStatusTest.java
  dora/tests/src/test/java/alluxio/client/rest/TestCase.java
Labels: type-code-quality

#17628 Fix deadlock issue when master process exit
  core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
Labels: type-bug

#17719 Use ufs iterable for copy and move
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJobFactory.java
  dora/core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
  dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
Labels: type-feature
