Repository Alluxio/alluxio, pull requests merged in 2023-03, with the labels that each got.

#16981 Add a property to disable file access time
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Labels: API Change

#16985 [DOCFIX] Correct docs about Ratis
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  docs/cn/deploy/Running-Alluxio-On-a-HA-Cluster.md
  docs/en/deploy/Running-Alluxio-On-a-HA-Cluster.md
Labels: Doc Fix

#16964 Update ci version
  .github/workflows/checkstyle.yml
  .github/workflows/fuse_integration_tests.yml
  .github/workflows/java8_integration_tests.yml
  .github/workflows/java8_integration_tests_ft.yml
  .github/workflows/java8_integration_tests_webui.yml
  .github/workflows/java8_unit_tests.yml
  .github/workflows/stale.yaml
Labels: area-build

#16984 Improve state lock tracking and report on error
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/StateLockManager.java
  core/server/common/src/test/java/alluxio/master/StateLockManagerTest.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
Labels: API Change

#16965 Add configurable TTL for Dora Worker RocksDBMetaStore
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
  core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
Labels: API Change

#16999 [DOCFIX] Add docs for fs loadMetadata cmd
  docs/en/operation/User-CLI.md
Labels: Doc Fix

#17001 Fix jsoup CVE-2021-37714
  underfs/web/pom.xml
Labels: POM Change, dependencies

#16994 Update operator for README.md
  integration/kubernetes/operator/alluxio/README.md
Labels: Doc Fix

#16950 [DOCFIX] Fix some errors occurred when formatting alluxio
  docs/cn/overview/Getting-Started.md
  docs/en/overview/Getting-Started.md
Labels: Doc Fix

#17003 [DOCFIX] Add OpenSSF Scorecard for README.md
  README.md
Labels: dependencies

#16806 Reduce time cost of checking bucket path in S3 API
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/exception/ExceptionMessage.java
  core/common/src/main/java/alluxio/util/io/PathUtils.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: API Change

#16995 Bump go from 1.13 to 1.18
  integration/kubernetes/operator/alluxio/Dockerfile
  integration/kubernetes/operator/alluxio/examples/demo-1/docker/Dockerfile
  integration/kubernetes/operator/alluxio/go.mod
Labels: dependencies

#16989 Add doc about Presto SDK for Dora
  docs/en/dora/PRESTO-SDK.md
Labels: Doc Fix

#16937 Enable v2 s3 proxy by default
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
Labels: API Change

#17000 Fix jackson CVE-2022-42003
  pom.xml
Labels: POM Change, dependencies

#17024 Remove HdfsUnderFileSystemFactory from service loading in COSN UFS jar
  underfs/cosn/pom.xml
Labels: POM Change

#17030 [DOCFIX] Update tensorflow script link
  docs/en/compute/Tensorflow.md
  docs/resources/mnist_classification.py
Labels: Doc Fix

#17039 Set ttlaction back to free
  core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
  tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
Labels: API Change

#17006 Support getBlockInfo excluding mount-related info
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Labels: area-rpc

#16982 Refactor LoadManager to Scheduler
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  core/common/src/main/java/alluxio/job/JobDescription.java
  core/common/src/main/java/alluxio/job/JobRequest.java
  core/common/src/main/java/alluxio/job/LoadJobRequest.java
  core/server/common/src/main/java/alluxio/master/journal/checkpoint/CheckpointName.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadManager.java
  core/server/master/src/main/java/alluxio/master/job/FileIterable.java
  core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
  core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  core/server/master/src/main/java/alluxio/master/scheduler/DefaultWorkerProvider.java
  core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/FileIterableTest.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/LoadJobTest.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/LoadTestUtils.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
  integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
  job/common/pom.xml
  job/common/src/main/java/alluxio/scheduler/job/Job.java
  job/common/src/main/java/alluxio/scheduler/job/JobFactory.java
  job/common/src/main/java/alluxio/scheduler/job/JobMetaStore.java
  job/common/src/main/java/alluxio/scheduler/job/JobState.java
  job/common/src/main/java/alluxio/scheduler/job/Task.java
  job/common/src/main/java/alluxio/scheduler/job/WorkerProvider.java
  microbench/src/main/java/alluxio/fsmaster/FileSystemMasterBase.java
  shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  tests/src/test/java/alluxio/client/cli/fs/command/LoadCommandIntegrationTest.java
Labels: API Change, breaks-compatibility

#17051 Merge scheduler to dora
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  core/common/src/main/java/alluxio/job/JobDescription.java
  core/common/src/main/java/alluxio/job/JobRequest.java
  core/common/src/main/java/alluxio/job/LoadJobRequest.java
  core/server/common/src/main/java/alluxio/master/journal/checkpoint/CheckpointName.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadManager.java
  core/server/master/src/main/java/alluxio/master/job/FileIterable.java
  core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
  core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
  core/server/master/src/main/java/alluxio/master/job/LoadJob.java
  core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
  core/server/master/src/main/java/alluxio/master/scheduler/DefaultWorkerProvider.java
  core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
  core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/FileIterableTest.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/LoadJobTest.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/LoadTestUtils.java
  core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
  integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
  job/common/pom.xml
  job/common/src/main/java/alluxio/scheduler/job/Job.java
  job/common/src/main/java/alluxio/scheduler/job/JobFactory.java
  job/common/src/main/java/alluxio/scheduler/job/JobMetaStore.java
  job/common/src/main/java/alluxio/scheduler/job/JobState.java
  job/common/src/main/java/alluxio/scheduler/job/Task.java
  job/common/src/main/java/alluxio/scheduler/job/WorkerProvider.java
  microbench/src/main/java/alluxio/fsmaster/FileSystemMasterBase.java
  shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  tests/src/test/java/alluxio/client/cli/fs/command/LoadCommandIntegrationTest.java
Labels: API Change

#16933 Fix setTtl workflow and ttlbucket bugs
  core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
  core/server/master/src/main/java/alluxio/master/file/meta/TtlBucket.java
  core/server/master/src/main/java/alluxio/master/file/meta/TtlBucketList.java
  core/server/master/src/test/java/alluxio/master/file/meta/TtlBucketListTest.java
  core/server/master/src/test/java/alluxio/master/file/meta/TtlBucketTest.java
  shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java
  tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
  tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemMasterSetTtlIntegrationTest.java
Labels: API Change

#17073 Fix snapshot from follower thread leak
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
  core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
  core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
  core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
  core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
  core/transport/src/main/proto/grpc/raft_journal.proto
  core/transport/src/main/proto/proto.lock
Labels: API Change

#17047 [DOCFIX] Add dora deployment on k8s doc
  docs/en/dora/Deploy-Alluxio-Cluster.md
Labels: Doc Fix

#17096 Change default value for checkpoint compression level
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#17058 Implement Dora list status cache
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Labels: API Change

#17106 [SMALLFIX]Update job service batch size default value
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#17109 Fix property identity typo error
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#17112 Eliminate race condition in completempupload and support overwrite
  core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Labels: API Change

#17114 Fix metadata sync behavior when descendant type is NONE
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
  tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
Labels: API Change

#17081 Dump metrics + stacks on failover/crash
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/util/ThreadUtils.java
  core/server/common/src/main/java/alluxio/ProcessUtils.java
  core/server/common/src/main/java/alluxio/master/StateLockManager.java
  core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
  core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
Labels: API Change

#17116 Port changes of [#17081] to branch-2.9
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/util/ThreadUtils.java
  core/server/common/src/main/java/alluxio/ProcessUtils.java
  core/server/common/src/main/java/alluxio/master/StateLockManager.java
  core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
  core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
Labels: API Change

#17120 Fix nullpointerException in distributed cmd
  shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
Labels: API Change

#17123 [DOCFIX] Fix Azure Data Lake Gen2 doc broken link
  docs/en/ufs/Azure-Data-Lake-Gen2.md
Labels: Doc Fix

#17102 Introduce S3 mock server to enhance unit testing
  core/server/master/pom.xml
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterS3UfsTest.java
  minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  pom.xml
  tests/pom.xml
  tests/src/test/java/alluxio/client/fs/FileSystemS3UfsIntegrationTest.java
  underfs/pom.xml
  underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemMockServerTest.java
Labels: POM Change

#17082 Make light and heavy thread pool configurable for s3 proxy v2
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Labels: API Change

#17129 Fix dependencies conflicts thrown by trino
  shaded/client/pom.xml
Labels: POM Change

#17133 [DOCFIX] Update generated tables with docGen
  docs/_data/table/common-configuration.csv
  docs/_data/table/en/common-configuration.yml
  docs/_data/table/en/master-configuration.yml
  docs/_data/table/en/master-metrics.yml
  docs/_data/table/en/user-configuration.yml
  docs/_data/table/master-configuration.csv
  docs/_data/table/master-metrics.csv
  docs/_data/table/user-configuration.csv
Labels: Doc Fix

#17108 Fix Dora UT by setting different Worker MetaStore dir
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
Labels: API Change

#17152 Port changes of [#17081] to branch-2.8
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/util/ThreadUtils.java
  core/server/common/src/main/java/alluxio/ProcessUtils.java
  core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
  core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
  shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
Labels: API Change

#17166 Port changes of [#17081] to branch-2.7
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/util/ThreadUtils.java
  core/server/common/src/main/java/alluxio/ProcessUtils.java
  core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
  core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
  shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
Labels: API Change

#17168 Port changes of [#17081] to branch-2.6
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/util/ThreadUtils.java
  core/server/common/src/main/java/alluxio/ProcessUtils.java
  core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
  core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
  shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
Labels: API Change
