Repository Alluxio/alluxio, pull requests merged in 2023-02, with the labels that each got.

#16834 [DOCFIX] Fix links to java file examples in Java-API.md
  docs/en/api/Java-API.md
Labels: Doc Fix

#16799 [DOCFIX] Fix some cn client-metric table wording
  docs/_data/table/cn/client-metrics.yml
Labels: Doc Fix

#16843 Add cache TTL enforcement
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerOptions.java
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#16735 Add RocksDB metadata store for Dora
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/rocks/RocksStore.java
  core/server/common/src/test/java/alluxio/rocks/RocksStoreTest.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
  core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaStore.java
  core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
  core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
  core/transport/src/main/proto/proto.lock
  core/transport/src/main/proto/proto/meta/dora_meta.proto
Labels: API Change

#16785 Fix bug that paged block store can neither write nor cache after reading
  core/client/fs/pom.xml
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/PageMetaStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/QuotaManagedPageStoreDir.java
  core/common/src/main/java/alluxio/worker/block/BlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/netty/BlockReadHandler.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockMetaStore.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreDir.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockWriter.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedTempBlockMeta.java
  tests/src/test/java/alluxio/server/worker/PagedBlockStoreIntegrationTest.java
Labels: POM Change

#16859 Add load to Dora
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java
  core/server/common/src/main/java/alluxio/master/journal/checkpoint/CheckpointName.java
  core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
  core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadJob.java
  core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadJobState.java
  core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadManager.java
  core/server/master/src/test/java/alluxio/master/file/loadmanager/LoadJobTest.java
  core/server/master/src/test/java/alluxio/master/file/loadmanager/LoadManagerTest.java
  core/server/master/src/test/java/alluxio/master/file/loadmanager/LoadTestUtils.java
  core/server/worker/src/main/java/alluxio/underfs/UfsIOManager.java
  core/transport/src/main/proto/grpc/block_worker.proto
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  core/transport/src/main/proto/proto/journal/job.proto
  core/transport/src/main/proto/proto/journal/journal.proto
  integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
  integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
  microbench/src/main/java/alluxio/fsmaster/FileSystemMasterBase.java
  shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  tests/src/test/java/alluxio/client/cli/fs/command/LoadCommandIntegrationTest.java
  tests/src/test/java/alluxio/client/cli/fs/command/OldLoadCommandIntegrationTest.java
Labels: API Change

#15647 Support rm directory and reset DirectChildrenLoadedState
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
  tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java
  tests/src/test/java/alluxio/client/cli/fs/command/RmCommandIntegrationTest.java
Labels: priority-high, API Change

#16654 Introduce a rearchitectured S3 proxy service
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/common/src/main/java/alluxio/web/WebServer.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/RangeFileInStream.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3BaseTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RequestServlet.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/signature/AwsSignatureProcessor.java
  core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Labels: API Change

#16881 Support Maven reproducible builds
  pom.xml
Labels: POM Change

#16844 Remove hardcoded version dependency in examples module
  examples/pom.xml
Labels: POM Change

#16840 [DOCFIX] Update cn version of Upgrade doc
  docs/cn/administration/Upgrade.md
Labels: Doc Fix

#16784 Fix Worker.ActiveClients is negative when load from ufs
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
Labels: area-metrics

#16597 Fix file fingerprint to use atomic get content hash of uploaded file
  core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataMessageBlockingStream.java
  core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriter.java
  core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
  core/client/fs/src/test/java/alluxio/client/block/stream/TestDataWriter.java
  core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  core/common/src/main/java/alluxio/grpc/DataMessageMarshaller.java
  core/common/src/main/java/alluxio/grpc/ReadResponseMarshaller.java
  core/common/src/main/java/alluxio/grpc/WriteRequestMarshaller.java
  core/common/src/main/java/alluxio/underfs/AtomicFileOutputStream.java
  core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
  core/common/src/main/java/alluxio/underfs/ContentHashable.java
  core/common/src/main/java/alluxio/underfs/Fingerprint.java
  core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  core/common/src/test/java/alluxio/underfs/FingerprintTest.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
  core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/UfsFileWriteHandler.java
  core/server/worker/src/main/java/alluxio/worker/grpc/WriteRequestContext.java
  core/transport/src/main/proto/grpc/block_worker.proto
  core/transport/src/main/proto/grpc/file_system_master.proto
  core/transport/src/main/proto/proto.lock
  integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemCommonOperations.java
  tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  underfs/cos/src/main/java/alluxio/underfs/cos/COSOutputStream.java
  underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSOutputStream.java
  underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2OutputStream.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java
  underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
  underfs/obs/src/main/java/alluxio/underfs/obs/OBSLowLevelOutputStream.java
  underfs/obs/src/main/java/alluxio/underfs/obs/OBSOutputStream.java
  underfs/obs/src/test/java/alluxio/underfs/obs/OBSLowLevelOutputStreamTest.java
  underfs/obs/src/test/java/alluxio/underfs/obs/OBSOutputStreamTest.java
  underfs/oss/src/main/java/alluxio/underfs/oss/OSSLowLevelOutputStream.java
  underfs/oss/src/main/java/alluxio/underfs/oss/OSSOutputStream.java
  underfs/oss/src/test/java/alluxio/underfs/oss/OSSLowLevelOutputStreamTest.java
  underfs/oss/src/test/java/alluxio/underfs/oss/OSSOutputStreamTest.java
  underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
  underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java
  underfs/s3a/src/test/java/alluxio/underfs/s3a/S3ALowLevelOutputStreamTest.java
  underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AOutputStreamTest.java
Labels: API Change

#16887 Update retry policy for object stores
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/retry/SleepingRetry.java
  core/common/src/test/java/alluxio/underfs/ObjectUnderFileSystemTest.java
Labels: API Change

#16891 [SMALLFIX] Add a missing javadoc param
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
Labels: API Change

#16849 Make workers register to all masters
  core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  core/common/src/main/java/alluxio/AbstractMasterClient.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/worker/block/BlockHeartbeatReport.java
  core/common/src/main/java/alluxio/worker/block/BlockWorker.java
  core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
  core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
  core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  core/server/master/src/test/java/alluxio/master/AlwaysPrimaryPrimarySelector.java
  core/server/master/src/test/java/alluxio/master/MasterTestUtils.java
  core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  core/server/master/src/test/java/alluxio/master/block/ConcurrentBlockMasterTest.java
  core/server/worker/src/main/java/alluxio/worker/block/AllMasterRegistrationBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReporter.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClientPool.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockSyncMasterGroup.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerFactory.java
  core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
  core/server/worker/src/main/java/alluxio/worker/block/SpecificMasterBlockSync.java
  core/server/worker/src/main/java/alluxio/worker/block/TestSpecificMasterBlockSync.java
  core/server/worker/src/main/java/alluxio/worker/block/WorkerMasterRegistrationState.java
  core/server/worker/src/test/java/alluxio/worker/block/AllMasterRegistrationBlockWorkerTest.java
  core/server/worker/src/test/java/alluxio/worker/block/BlockHeartbeatReporterTest.java
  core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
  core/server/worker/src/test/java/alluxio/worker/block/SpecificMasterBlockSyncTest.java
  core/transport/src/main/proto/grpc/block_master.proto
  core/transport/src/main/proto/proto.lock
  core/transport/src/main/proto/proto/journal/block.proto
  minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
  tests/src/test/java/alluxio/server/block/BlockMasterRegisterStreamIntegrationTest.java
  tests/src/test/java/alluxio/server/worker/WorkerAllMasterRegistrationTest.java
Labels: API Change

#16855 [DOCFIX] Update cn version of Spark on Kubernetes doc
  docs/cn/kubernetes/Spark-On-Kubernetes.md
Labels: type-docs, Doc Fix, area-k8s

#16870 Fix the bug that frequent refreshing of worker info reduces throughput
  core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
  core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
Labels: API Change

#16911 Fix client side cache sequence
  core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Labels: API Change

#16917 [SMALLFIX] Fix a few typos in comment
  core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
Labels: type-code-quality

#16871 [SMALLFIX] Fix Alluxio/new-contributor-tasks#624
  core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
Labels: needs-response

#16751 Fix typo in S3Exception
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-code-quality

#16507 Add WorkerInfoField test in CapacityCommandTest
  core/client/fs/src/test/java/alluxio/client/block/options/GetWorkerReportOptionsTest.java
Labels: area-build

#16804 Add local read benchmarks for PagedBlockStore
  microbench/src/main/java/alluxio/worker/BlockStoreBase.java
  microbench/src/main/java/alluxio/worker/BlockStoreRandomReadBench.java
  microbench/src/main/java/alluxio/worker/BlockStoreSequentialReadBench.java
Labels: area-benchmark, area-worker

#16866 Add rate limit for s3 proxy
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/RateLimitInputStream.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
  core/server/proxy/src/test/java/alluxio/proxy/s3/RateLimitInputStreamTest.java
Labels: API Change, needs-response, area-s3-rest-api, type-performance, type-resource

#16458 Fix free worker command bugs
  core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
  shell/src/main/java/alluxio/cli/fs/command/FreeWorkerCommand.java
Labels: area-shell, area-worker

#16928 Fix head and tail commands read less than expected
  shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java
  shell/src/main/java/alluxio/cli/fs/command/TailCommand.java
Labels: area-shell, type-bug, API Change

#16908 Make standby master keep MountTable up-to-date
  core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
Labels: type-feature, area-master

#16237 Add CapacityBasedDeterministicHashPolicy
  core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBasedDeterministicHashPolicy.java
  core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBasedDeterministicHashPolicyTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  docs/en/api/Java-API.md
Labels: API Change

#16935 Fix metadata sync behavior when descendant type is NONE
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
  core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
  tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
Labels: API Change

#16895 Support remove blocks on worker for pagestore when free/delete file
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreDir.java
Labels: type-feature, area-worker

#16925 [DOCFIX] Fix the wrong option in stress bench doc
  docs/en/administration/StressBench.md
Labels: Doc Fix

#16893 Improve LS by allowing to omit UFS and mount info
  core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/transport/src/main/proto/grpc/file_system_master.proto
  shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Labels: API Change

#16959 Change the netty default value for better performance
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: API Change

#16957 [DOCFIX] Add dora doc structure
  docs/_config.yml
  docs/en/dora/Deploy-Alluxio-Cluster.md
  docs/en/dora/FUSE-SDK.md
  docs/en/dora/Overview.md
  docs/en/dora/PRESTO-SDK.md
Labels: Doc Fix

#16636 Display more information in WebUI Masters
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/util/webui/UIMasterInfo.java
  core/common/src/main/java/alluxio/wire/MasterInfo.java
  core/common/src/main/java/alluxio/wire/MasterWebUIMasters.java
  core/common/src/test/java/alluxio/wire/MasterInfoTest.java
  core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  core/server/master/src/main/java/alluxio/master/MasterProcess.java
  core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MasterInfo.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMaster.java
  core/server/master/src/main/java/alluxio/master/meta/MetaMasterMasterServiceHandler.java
  core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
  core/transport/src/main/proto/grpc/meta_master.proto
  core/transport/src/main/proto/proto.lock
  webui/master/src/constants/types/IMasterInfo.tsx
  webui/master/src/containers/pages/Masters/Masters.tsx
  webui/master/src/containers/pages/Masters/__snapshots__/Masters.test.tsx.snap
  webui/master/src/store/masters/reducer.tsx
  webui/master/src/store/masters/types.tsx
Labels: area-webui
