Repository Alluxio/alluxio, pull requests merged in 2023-08, with the labels that each got.

#17865 Set min replicate to 0 and unpin file if we fail to replicate a file
  job/server/src/main/java/alluxio/job/plan/replicate/SetReplicaDefinition.java
Labels: type-bug

#17858 Bump grpc & netty version
  core/common/pom.xml
  core/common/src/main/java/alluxio/grpc/GrpcSerializationUtils.java
  pom.xml
Labels: type-debt, dependencies

#17868 [DOCFIX] Fix load doc
  docs/en/operation/User-CLI.md
Labels: type-docs

#17862 Add multipart upload interface & hdfs minicluster test
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/ByteBufferResourcePool.java
  dora/core/common/src/main/java/alluxio/underfs/MultipartUploader.java
  dora/core/common/src/main/java/alluxio/underfs/options/CreateOptions.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
  dora/underfs/hdfs/pom.xml
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
  dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTestBase.java
Labels: type-feature, type-code-quality

#17872 Generate test-jar for HDFS UFS
  dora/underfs/hdfs/pom.xml
Labels: type-devops

#17853 [DOCFIX] Reformat Storage Integrations
  docs/_data/menu-en.yml
  docs/en/reference/Environment-List.md
  docs/en/ufs/Aliyun-OSS.md
  docs/en/ufs/Azure-Blob-Store.md
  docs/en/ufs/Azure-Data-Lake-Gen2.md
  docs/en/ufs/Azure-Data-Lake.md
  docs/en/ufs/COS.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/GCS.md
  docs/en/ufs/HDFS.md
  docs/en/ufs/Huawei-OBS.md
  docs/en/ufs/Minio.md
  docs/en/ufs/NFS.md
  docs/en/ufs/OBS.md
  docs/en/ufs/OSS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/S3.md
  docs/en/ufs/Storage-Overview.md
  docs/en/ufs/Swift.md
  docs/en/ufs/Tencent-COS.md
Labels: type-docs

#17860 Set FromUFSFallBack flag in URIStatus to reduce client fall back time
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/common/src/main/java/alluxio/client/file/URIStatus.java
Labels: type-bug

#17857 Process the mount point from user input
  dora/integration/fuse/bin/alluxio-fuse
Labels: type-bug

#17877 Improve debug logging
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  dora/core/server/common/src/main/java/alluxio/master/journal/MergeJournalContext.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
Labels: type-bug

#17873 [DOCFIX] Update List of Metrics table formatting
  docs/en/reference/Metrics-List.md
Labels: type-docs

#17875 Remove the dependency to the master during the registration
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#17876 Dora Fuse HDFS integration test
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  dora/tests/pom.xml
  dora/tests/src/test/java/alluxio/client/fuse/dora/FuseEndToEndTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/FuseUtils.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/FuseHdfsIntegrationTest.java
Labels: type-feature, type-code-quality

#17879 [DOCFIX] Remove embedded videos
  docs/en/Overview.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/core-services/Data-Caching.md
  docs/en/introduction/Introduction.md
  docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
Labels: type-docs

#17882 Support ETCD worker management for scheduler
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/DefaultWorkerProvider.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/MembershipManagerWorkerProvider.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
  dora/core/server/master/src/main/java/alluxio/master/scheduler/WorkerProvider.java
  dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Labels: type-feature

#17883 [DOCFIX] Add release notes 2.9.3
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17884 [DOCFIX] Add release notes 2.9.2
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17885 [DOCFIX] Add release notes 2.9.1
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17891 Remove runHmsTests
  bin/alluxio
  dora/shell/src/main/java/alluxio/cli/HmsTests.java
Labels: type-debt

#17898 Remove the getBlockInfoCommand
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/GetBlockInfoCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/GetBlockInfoCommandIntegrationTest.java
Labels: type-debt

#17902 [DOCFIX] Update Release Notes 2.9.0
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17903 [DOCFIX] Update Release Notes 2.9.1
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17904 [DOCFIX] Update Release Notes 2.9.2
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17892 Remove run journal crash test
  bin/alluxio
  dora/shell/src/main/java/alluxio/cli/JournalCrashTest.java
Labels: type-debt

#17905 [DOCFIX] Add Release Notes 2.8.1
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17908 [DOCFIX] Add Release Notes 2.8.0
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17906 [DOCFIX] Add Release Notes 2.7.4
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17907 [DOCFIX] Add Release Notes 2.7.3
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17909 [DOCFIX] Add Release Notes 2.7.2
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17912 Bump enforcer version to 3.3.0
  pom.xml
Labels: area-build, POM Change, dependencies, type-devops

#17900 Update fuse hdfs integration tests
  dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/FuseHdfsIntegrationTest.java
Labels: type-code-quality

#17896 Fail builds if duplicate dependencies in pom
  pom.xml
Labels: area-build, POM Change, type-devops

#17914 [SMALLFIX] Remove the table command
  bin/alluxio
Labels: type-debt

#17923 [DOCFIX] Update Overview
  docs/en/Overview.md
Labels: type-docs

#17920 Remove the distributedCp/Mv commands
  dora/shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCancelTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCommandTest.java
Labels: type-debt

#17890 Revise AlluxioEtcdClient connect logic
  dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#17921 Remove the unused job commands
  bin/alluxio
  dora/shell/src/main/java/alluxio/cli/job/JobShell.java
  dora/shell/src/main/java/alluxio/cli/job/command/CancelCommand.java
  dora/shell/src/main/java/alluxio/cli/job/command/GetCmdStatusCommand.java
  dora/shell/src/main/java/alluxio/cli/job/command/LeaderCommand.java
  dora/shell/src/main/java/alluxio/cli/job/command/ListCommand.java
  dora/shell/src/main/java/alluxio/cli/job/command/StatCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/CancelCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/DistributedCmdTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/GetCmdStatusCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/JobShellTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/LeaderCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/ListCommandTest.java
  dora/tests/src/test/java/alluxio/client/cli/job/StatCommandTest.java
Labels: type-debt

#17929 [DOCFIX] Update Overview Page
  docs/en/Get-Started.md
  docs/en/Overview.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/core-services/Data-Caching.md
  docs/en/introduction/Introduction.md
Labels: type-docs

#17924 [DOCFIX] Release Notes 2.7.1
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17927 [DOCFIX] Release Notes 2.6.1
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17928 [DOCFIX] Release Notes 2.6.0
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17925 [DOCFIX] Release Notes 2.7.0
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17926 [DOCFIX] Release Notes 2.6.2
  docs/en/overview/Release-Notes.md
Labels: type-docs

#17919 Skip sortpom when running tests and during build
  dev/github/run_tests.sh
  pom.xml
Labels: type-devops

#17887 Add process subcommands for multiple nodes
  cli/src/alluxio.org/cli/env/env.go
  cli/src/alluxio.org/cli/env/process_start.go
  cli/src/alluxio.org/cli/env/process_stop.go
  cli/src/alluxio.org/cli/main.go
  cli/src/alluxio.org/cli/processes/all.go
  cli/src/alluxio.org/cli/processes/common.go
  cli/src/alluxio.org/cli/processes/job_masters.go
  cli/src/alluxio.org/cli/processes/job_workers.go
  cli/src/alluxio.org/cli/processes/local.go
  cli/src/alluxio.org/cli/processes/masters.go
  cli/src/alluxio.org/cli/processes/proxies.go
  cli/src/alluxio.org/cli/processes/workers.go
  cli/src/alluxio.org/go.mod
  cli/src/alluxio.org/go.sum
Labels: type-feature

#17933 [SMALLFIX] Remove the several redundant run commands
  bin/alluxio
  bin/alluxio-start.sh
  bin/launch-process
Labels: type-debt

#17941 Remove the StateLockHoldersCommand
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/StateLockHoldersCommand.java
Labels: type-debt

#17940 Remove throttle master
  dora/core/common/src/main/java/alluxio/Constants.java
  dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
  dora/core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/throttle/DefaultThrottleMaster.java
  dora/core/server/master/src/main/java/alluxio/master/throttle/FileSystemIndicator.java
  dora/core/server/master/src/main/java/alluxio/master/throttle/MetricsMonitorUtils.java
  dora/core/server/master/src/main/java/alluxio/master/throttle/ServerIndicator.java
  dora/core/server/master/src/main/java/alluxio/master/throttle/SystemMonitor.java
  dora/core/server/master/src/main/java/alluxio/master/throttle/ThrottleMasterFactory.java
  dora/core/server/master/src/main/resources/META-INF/services/alluxio.master.MasterFactory
  dora/core/server/master/src/test/java/alluxio/master/throttle/IndicatorsTests.java
Labels: type-code-quality

#17938 Remove the getCapacityAndUsedBytes commands
  dora/shell/src/main/java/alluxio/cli/fs/command/GetCapacityBytesCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/GetUsedBytesCommand.java
Labels: type-debt

#17930 [SMALLFIX] Remove the upgradeJournal commands
  bin/alluxio
  dora/core/server/common/src/main/java/alluxio/master/journal/JournalUpgrader.java
Labels: type-debt

#17942 [DOCFIX] Move Basic Logging to Operations
  docs/_data/menu-en.yml
  docs/en/Troubleshooting.md
  docs/en/api/Java-API.md
  docs/en/api/S3-API.md
  docs/en/contributor/Code-Conventions.md
  docs/en/operation/Basic-Logging.md
  docs/en/operation/User-CLI.md
Labels: type-docs

#17917 Remove path config command
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/PathConfCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/pathconf/AddCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/pathconf/ListCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/pathconf/RemoveCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/pathconf/ShowCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/PathConfCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/pathconf/AddCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/pathconf/ListCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/pathconf/RemoveCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/pathconf/ShowCommandIntegrationTest.java
Labels: type-debt

#17944 [SMALLFIX] Remove the bootstrap config and killAll
  bin/alluxio
Labels: type-debt

#17946 Fix version parsing in build script
  dev/scripts/src/alluxio.org/build/cmd/version.go
Labels: type-bug

#17945 Remove AccessTimeUpdater
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/master/src/main/java/alluxio/master/file/AccessTimeUpdater.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/test/java/alluxio/master/file/AccessTimeUpdaterTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/LsCommandSecurityIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemMasterRestartIntegrationTest.java
  dora/tests/src/test/java/alluxio/job/JobIntegrationTest.java
  dora/tests/src/test/java/alluxio/server/ft/journal/ufs/UfsJournalIntegrationTest.java
Labels: type-code-quality

#17951 Remove check to the master if etcd membership
  dora/shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
Labels: type-feature

#17952 Turn off client side metrics sink since the master will be removed
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-feature

#17922 Revise membership command in fsadmin shell
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/NodesCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/nodes/WorkerStatusCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/report/NodeStatusCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/NodesCommandIntegrationTest.java
Labels: type-ease-of-use

#17958 Add back killAll command
  bin/alluxio
Labels: type-bug

#17936 Remove the MasterInfo/Leader commands
  dora/shell/src/main/java/alluxio/cli/fs/command/LeaderCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/MasterInfoCommand.java
Labels: type-debt

#17957 Fix the duplicated metrics counting
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Labels: type-bug

#17950 Remove BlockIntegrityChecker
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
  dora/core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/BlockIntegrityChecker.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
  dora/tests/src/test/java/alluxio/server/health/BlockMasterIntegrityIntegrationTest.java
Labels: type-code-quality

#17899 Refactor FUSE related codes for decoupling
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseStreamFactory.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/SimpleFuseStreamFactory.java
  dora/integration/fuse/src/test/java/alluxio/fuse/ufs/stream/AbstractStreamTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/ufs/stream/OutStreamTest.java
  dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
  dora/tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/FuseFileSystemDataTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/readonly/stream/AbstractStreamTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/AbstractStreamTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/InStreamTest.java
  dora/tests/src/test/java/alluxio/client/fuse/dora/stream/OutStreamTest.java
  dora/tests/src/test/java/alluxio/client/fuse/file/AbstractFuseFileStreamIntegrationTest.java
Labels: type-code-quality

#17965 Fix the membership check in fsadmin
  dora/shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
Labels: type-bug

#17893 Remove active sync related commands
  dora/shell/src/main/java/alluxio/cli/fs/command/GetSyncPathListCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/StartSyncCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/StopSyncCommand.java
Labels: type-debt

#17934 [SMALLFIX] Remove the check consistency command
  dora/shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/CheckConsistencyCommandIntegrationTest.java
Labels: type-debt

#17969 Remove duCommand
  dora/shell/src/main/java/alluxio/cli/fs/command/DuCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/DuCommandIntegrationTest.java
Labels: type-debt

#17960 Rename existing bash scripts with -bash suffix
  bin/alluxio
  bin/alluxio-bash
  bin/alluxio-common-bash.sh
  bin/alluxio-masters-bash.sh
  bin/alluxio-monitor-bash.sh
  bin/alluxio-mount-bash.sh
  bin/alluxio-mount.sh
  bin/alluxio-start-bash.sh
  bin/alluxio-start.sh
  bin/alluxio-stop-bash.sh
  bin/alluxio-stop.sh
  bin/alluxio-workers-bash.sh
  bin/launch-process-bash
Labels: type-debt

#17935 Remove RocksPageStore
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreDirTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
  dora/core/common/src/main/java/alluxio/client/file/cache/store/PageStoreType.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
Labels: type-code-quality

#17932 Remove unused thread pools and rename netty/grpc pools
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/conf/RemovedKey.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/FileReadHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyExecutors.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
  dora/core/server/worker/src/test/java/alluxio/worker/grpc/GrpcExecutorsTest.java
Labels: type-code-quality

#17964 Remove active sync on the master side
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemCache.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/SyncInfo.java
  dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
  dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  dora/core/common/src/main/java/alluxio/wire/SyncPointInfo.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
  dora/core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
  dora/core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncer.java
  dora/integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
  dora/tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
  dora/underfs/hdfs/pom.xml
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsActiveSyncProvider.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/NoopHdfsActiveSyncProvider.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/activesync/SupportedHdfsActiveSyncProvider.java
Labels: type-code-quality

#17948 Remove unused Propertykey and some unit test
  dora/core/client/fs/src/test/java/alluxio/client/util/ClientTestUtils.java
  dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
  dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/util/webui/UIFileBlockInfo.java
  dora/core/common/src/test/java/alluxio/ConfigurationTestUtils.java
  dora/core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
  dora/core/common/src/test/java/alluxio/conf/PropertyKeyTest.java
  dora/core/server/common/src/test/java/alluxio/cli/FormatTest.java
  dora/core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTestBase.java
  dora/core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
  dora/integration/tools/validation/src/main/java/alluxio/cli/RamDiskMountPrivilegeValidationTask.java
  dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/LoadCommandIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/PinCommandMultipleMediaIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/RemoteReadIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/UnderStorageReadIntegrationTest.java
Labels: type-debt

#17976 Update list of tarball copied bin scripts
  dev/scripts/src/alluxio.org/build/profiles.yml
Labels: type-devops

#17961 Fix the duplicated class issues when compile presto with alluxio
  dora/shaded/client/pom.xml
Labels: type-devops

#17966 [DOCFIX] Update sitemap logic and relate checks
  dev/scripts/src/alluxio.org/check-docs/main.go
  docs/_includes/sitemap.html
Labels: type-docs

#17978 Require Java version 1.8
  pom.xml
Labels: type-code-quality

#17971 Remove ufsCommand and updateConfigCommand
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/UfsCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/UpdateConfIntegrationTest.java
Labels: type-debt

#17973 Remove path conf
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/MetadataCachingFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MetadataCachingFileSystemTest.java
  dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
  dora/core/common/src/main/java/alluxio/ClientContext.java
  dora/core/common/src/main/java/alluxio/conf/Configuration.java
  dora/core/common/src/main/java/alluxio/conf/path/PathConfiguration.java
  dora/core/common/src/main/java/alluxio/conf/path/PathMatcher.java
  dora/core/common/src/main/java/alluxio/conf/path/PrefixPathConfiguration.java
  dora/core/common/src/main/java/alluxio/conf/path/PrefixPathMatcher.java
  dora/core/common/src/main/java/alluxio/conf/path/SpecificPathConfiguration.java
  dora/core/common/src/main/java/alluxio/conf/path/TrieNode.java
  dora/core/common/src/test/java/alluxio/conf/path/PrefixPathMatcherTest.java
  dora/core/common/src/test/java/alluxio/conf/path/TrieNodeTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/cli/FuseShellTest.java
  dora/job/server/src/main/java/alluxio/master/job/tracker/MigrateCliRunner.java
  dora/job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
  dora/job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionRunTaskTest.java
  dora/job/server/src/test/java/alluxio/master/job/tracker/CliRunnerTest.java
  dora/shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemReadonlyIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/PathConfigurationIntegrationTest.java
Labels: type-debt

#17970 Remove freeWorker command
  dora/shell/src/main/java/alluxio/cli/fs/command/FreeWorkerCommand.java
Labels: type-debt

#17824 Improve filter exclusion setting for shade plugin
  dora/shaded/client/pom.xml
  dora/underfs/abfs/pom.xml
  dora/underfs/adl/pom.xml
  dora/underfs/cephfs-hadoop/pom.xml
  dora/underfs/cosn/pom.xml
  dora/underfs/ozone/pom.xml
  dora/underfs/pom.xml
  dora/underfs/wasb/pom.xml
Labels: type-code-quality

#17981 Remove unused stressbench
  dora/core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
  dora/stress/common/src/main/java/alluxio/stress/CachingBlockMasterClient.java
  dora/stress/common/src/main/java/alluxio/stress/client/CompactionParameters.java
  dora/stress/common/src/main/java/alluxio/stress/client/CompactionTaskResult.java
  dora/stress/common/src/main/java/alluxio/stress/client/CompactionTaskResultStatistics.java
  dora/stress/common/src/main/java/alluxio/stress/common/AbstractMaxThroughputSummary.java
  dora/stress/common/src/main/java/alluxio/stress/common/SummaryStatistics.java
  dora/stress/common/src/main/java/alluxio/stress/fuse/FuseIOOperation.java
  dora/stress/common/src/main/java/alluxio/stress/fuse/FuseIOParameters.java
  dora/stress/common/src/main/java/alluxio/stress/fuse/FuseIOSummary.java
  dora/stress/common/src/main/java/alluxio/stress/fuse/FuseIOTaskResult.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchOperation.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchSummary.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchTaskResult.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchTaskResultStatistics.java
  dora/stress/common/src/main/java/alluxio/stress/jobservice/JobServiceMaxThroughputSummary.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBatchTaskParameters.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBenchBaseParameters.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBenchSummary.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResult.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResultBase.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResultStatistics.java
  dora/stress/common/src/main/java/alluxio/stress/master/MasterMaxThroughputSummary.java
  dora/stress/common/src/main/java/alluxio/stress/master/MaxThroughputSummary.java
  dora/stress/common/src/main/java/alluxio/stress/master/MultiOperationMasterBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/master/MultiOperationMasterBenchSummary.java
  dora/stress/common/src/main/java/alluxio/stress/master/MultiOperationMasterBenchTaskResult.java
  dora/stress/common/src/main/java/alluxio/stress/master/Operation.java
  dora/stress/common/src/main/java/alluxio/stress/rpc/BlockMasterBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/rpc/GetPinnedFileIdsParameters.java
  dora/stress/common/src/main/java/alluxio/stress/rpc/RpcBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/rpc/RpcTaskResult.java
  dora/stress/common/src/main/java/alluxio/stress/rpc/RpcTaskSummary.java
  dora/stress/common/src/main/java/alluxio/stress/rpc/TierAlias.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/BatchTask.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/BatchTaskRunner.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/GetPinnedFileIdsBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/MasterBatchTask.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/MaxFileBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/MultiOperationStressMasterBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/RpcBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/StressMasterBenchBase.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/client/CompactionBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/suite/AbstractMaxThroughput.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/suite/JobServiceMaxThroughput.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/suite/MasterMaxThroughput.java
  dora/tests/src/test/java/alluxio/stress/BatchTaskRunnerIntegrationTest.java
  dora/tests/src/test/java/alluxio/stress/StressMasterBenchIntegrationTest.java
Labels: type-debt

#17975 Remove deprecated JNR-based FuseFileSystem
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJnrFuseFileSystem.java
  dora/integration/fuse/src/main/java/alluxio/fuse/FuseSignalHandler.java
  dora/integration/fuse/src/main/java/alluxio/fuse/FuseUmountable.java
  dora/integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
  dora/integration/fuse/src/test/java/alluxio/fuse/AlluxioJnrFuseFileSystemTest.java
  dora/tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fuse/JNRFuseIntegrationTest.java
Labels: type-debt

#17897 Remove the countCommand
  dora/shell/src/main/java/alluxio/cli/fs/command/CountCommand.java
  dora/tests/src/test/java/alluxio/client/cli/fs/command/CountCommandTest.java
Labels: type-debt

#17954 Remove ufs cleaner
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
  dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  dora/core/server/master/src/main/java/alluxio/master/file/UfsCleaner.java
Labels: type-code-quality

#17734 Rewrite StressWorkerBench
  dora/job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
  dora/stress/common/src/main/java/alluxio/stress/BaseParameters.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPoint.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPointDeserializer.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchParameters.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchSummary.java
  dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchTaskResult.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
  dora/tests/src/test/java/alluxio/stress/StressWorkerBenchIntegrationTest.java
Labels: type-feature

#17988 Fix non-existent tiered store property preventing worker from starting
  dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
Labels: type-bug

#17990 Remove unused parameters pathConf
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
  dora/core/common/src/main/java/alluxio/ClientContext.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/FileSystemReadonlyIntegrationTest.java
  dora/tests/src/test/java/alluxio/client/fs/PathConfigurationIntegrationTest.java
Labels: type-code-quality

#17869 Add UfsUrl design and implementation
  common/transport/src/main/proto/grpc/common.proto
  common/transport/src/main/proto/grpc/file_system_master.proto
  dora/core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemCache.java
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/MetadataCachingFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
  dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MetadataCachingFileSystemTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/common/src/main/java/alluxio/exception/FileDoesNotExistException.java
  dora/core/common/src/main/java/alluxio/uri/UfsUrl.java
  dora/core/common/src/main/java/alluxio/util/io/PathUtils.java
  dora/core/common/src/test/java/alluxio/UfsUrlTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
  dora/integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
  dora/integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
  dora/shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java
  dora/shell/src/main/java/alluxio/cli/fs/command/AbstractFileSystemCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Labels: type-feature

#17995 [DOCFIX] Update checkstyle pr build check
  dev/scripts/src/alluxio.org/check-docs/main.go
Labels: type-docs

#17998 Avoid using associative arrays in bin/alluxio script
  build/cli/build-cli.sh
Labels: type-bug

#17996 Add golang cli compilation to github check
  dev/github/run_checks.sh
Labels: type-devops

#17994 Remove journal backup flag from start master
  cli/src/alluxio.org/cli/processes/master.go
Labels: type-debt

#18004 Build all golang cli executables for tarball dry run
  dev/github/run_checks.sh
  dev/scripts/src/alluxio.org/build/cmd/build.go
Labels: type-devops

#18003 Remove copyTo/FromLocal commands
  dora/shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/CopyToLocalCommand.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/CopyToLocalCommandIntegrationTest.java
Labels: type-debt

#17782 Implement the COS Unit Test and improve cloud storage's UT coverage
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
  dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystemFactory.java
  dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSInputStreamTest.java
  dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSOutputStreamTest.java
  dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSPositionReaderTest.java
  dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSUnderFileSystemFactoryTest.java
  dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSUnderFileSystemTest.java
  dora/underfs/cos/src/test/resources/log4j.properties
Labels: type-devops

#18011 [DOCFIX] Add Doc of running Alluxio with Tensorflow
  docs/_data/menu-en.yml
  docs/en/compute/Tensorflow.md
Labels: type-docs

#18013 Fix cp command to avoid copyToLocal and copyFromLocal
  cli/src/alluxio.org/cli/cmd/fs/cp.go
Labels: type-bug

#18012 Remove MetaMasterConfigClient initialization in the client
  dora/shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShell.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/AbstractFsAdminCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/Context.java
  dora/tests/integration/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/client/fs/PathConfigurationIntegrationTest.java
Labels: type-debt

#17986 [DOCFIX] Update menu to 3 tiers
  docs/_data/menu-en.yml
  docs/en/Glossary.md
  docs/en/Overview.md
  docs/en/Troubleshooting.md
  docs/en/contributor/Code-Conventions.md
  docs/en/contributor/Contribution-Guide.md
  docs/en/contributor/Contributor-Tools.md
  docs/en/deploy/Get-Started.md
  docs/en/deploy/Software-Requirements.md
  docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
  docs/en/kubernetes/Metrics-On-Kubernetes.md
  docs/en/operation/Logging.md
  docs/en/operation/User-CLI.md
Labels: type-docs

#17959 Make workerinfo stored as json
  dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
  dora/core/common/src/main/java/alluxio/membership/DefaultServiceEntity.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
  dora/core/common/src/main/java/alluxio/membership/WorkerServiceEntity.java
  dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
  dora/core/common/src/test/java/alluxio/membership/ServiceEntityTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-ease-of-use

#17993 Disable starting proxy/job processes in all/local
  bin/alluxio-monitor-bash.sh
  bin/alluxio-start-bash.sh
  cli/src/alluxio.org/cli/env/process_start.go
  cli/src/alluxio.org/cli/env/process_stop.go
  cli/src/alluxio.org/cli/processes/all.go
  cli/src/alluxio.org/cli/processes/local.go
Labels: type-devops

#18024 Refactor Fuse interfaces
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileEntry.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReadOrOutStream.java
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
Labels: type-feature

#18027 Fix broken UT by remove TieredIdentity in
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-bug

#18020 Remove loadMetadataCommand
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadMetadataCommand.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/LoadMetadataCommandIntegrationTest.java
Labels: type-debt

#18030 Remove bin/alluxio metadata load in favor of load job cmd
  cli/src/alluxio.org/cli/cmd/metadata/load.go
  cli/src/alluxio.org/cli/cmd/metadata/metadata.go
  cli/src/alluxio.org/cli/main.go
Labels: type-debt

#18028 [DOCFIX] Update headers in right menu to redirect to section
  docs/en/api/S3-API.md
Labels: type-docs

#18018 Disable stopping proxy/job processes in all/local
  bin/alluxio-start-bash.sh
  bin/alluxio-stop-bash.sh
Labels: type-devops

#18031 Check env preconditions before building go cli
  build/cli/build-cli.sh
  docs/en/contributor/Building-Alluxio-From-Source.md
Labels: type-ease-of-use

#18035 Add metrics for the ages of the pages in page cache store
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Labels: type-devops

#18009 [SMALLFIX] Fix DataPercentageinAlluxio always shows 0%
  dora/shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Labels: type-bug, type-devops

#18010 Change the interface of etcd-related class
  dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
  dora/core/common/src/main/java/alluxio/membership/DefaultServiceEntity.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
  dora/core/common/src/main/java/alluxio/membership/WorkerServiceEntity.java
  dora/core/common/src/test/java/alluxio/membership/ServiceEntityTest.java
Labels: type-feature

#18040 Add init/format, copyDir subcommands to CLI
  cli/src/alluxio.org/cli/cmd/initiate/copy_dir.go
  cli/src/alluxio.org/cli/cmd/initiate/format.go
  cli/src/alluxio.org/cli/cmd/initiate/initiate.go
  cli/src/alluxio.org/cli/env/env.go
  cli/src/alluxio.org/cli/env/env_vars.go
  cli/src/alluxio.org/cli/processes/common.go
  cli/src/alluxio.org/cli/processes/multi.go
Labels: type-feature

#18046 Fix S3 multipart upload and add related UTs
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadRequest.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/ListMultipartUploadsResult.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
  dora/tests/integration/src/test/java/alluxio/client/rest/MultipartUploadTest.java
  dora/tests/integration/src/test/java/alluxio/client/rest/RestApiTest.java
  dora/tests/integration/src/test/java/alluxio/client/rest/TestCase.java
Labels: type-debt

#18026 Fix multiple mount options not recognized
  dora/integration/fuse/bin/alluxio-fuse
Labels: type-bug

#18014 Return relative path in listStatus results
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
  dora/core/client/fs/src/main/java/alluxio/client/file/options/UfsFileSystemOptions.java
  dora/core/common/src/main/java/alluxio/client/file/ListStatusPartialResult.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-feature

#18045 Fix load cli command
  cli/src/alluxio.org/cli/cmd/job/cancel.go
  cli/src/alluxio.org/cli/cmd/job/cmd_status.go
  cli/src/alluxio.org/cli/cmd/job/job.go
  cli/src/alluxio.org/cli/cmd/job/job_status.go
  cli/src/alluxio.org/cli/cmd/job/leader.go
  cli/src/alluxio.org/cli/cmd/job/list.go
  cli/src/alluxio.org/cli/cmd/job/load.go
  cli/src/alluxio.org/cli/cmd/names/names.go
  dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Labels: type-bug

#18048 Add S3 list-parts UTs
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  dora/tests/integration/src/test/java/alluxio/client/rest/MultipartUploadTest.java
Labels: type-feature

#18050 Update PagedDoraWorkerTest.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Labels: type-code-quality

#18051 Remove web ufs
  dora/underfs/pom.xml
  dora/underfs/web/pom.xml
  dora/underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
  dora/underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystemFactory.java
  dora/underfs/web/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory
  dora/underfs/web/src/test/java/alluxio/underfs/web/WebUnderFileSystemFactoryTest.java
  dora/underfs/web/src/test/java/alluxio/underfs/web/WebUnderFileSystemTest.java
  dora/underfs/web/src/test/resources/log4j.properties
Labels: type-debt

#18054 Add a new Run interface in CLI for future use
  cli/src/alluxio.org/cli/env/command.go
Labels: type-devops

#18055 Remove info master cmd
  cli/src/alluxio.org/cli/cmd/info/info.go
  cli/src/alluxio.org/cli/cmd/info/master.go
Labels: type-bug

#18041 Change bucket visibility to all users
  dora/core/server/common/src/main/java/alluxio/s3/ListAllMyBucketsResult.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyBucketTask.java
  dora/tests/integration/src/test/java/alluxio/client/rest/ListStatusTest.java
Labels: type-bug

#18036 Support HDFS UFS trash
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Labels: type-feature

#18039 Fix bug of classnotfound at Fuse runtime
  dora/integration/jnifuse/fs/pom.xml
  dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
Labels: type-bug

#18058 Remove web ufs
  build/lib/copy_jars.sh
  dev/scripts/src/alluxio.org/build/modules.yml
Labels: type-bug

#17894 Support decode aws-chunked PUT object request
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/common/src/main/java/alluxio/s3/DeleteObjectsRequest.java
  dora/core/server/common/src/main/java/alluxio/s3/DeleteObjectsResult.java
  dora/core/server/common/src/main/java/alluxio/s3/MultiChunkEncodingInputStream.java
  dora/core/server/common/src/main/java/alluxio/s3/NettyRestUtils.java
  dora/core/server/common/src/main/java/alluxio/s3/signature/AwsSignatureProcessor.java
  dora/core/server/common/src/main/java/alluxio/s3/signature/StringToSignProducer.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/core/server/proxy/src/test/java/alluxio/proxy/s3/S3RestServiceHandlerTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/DataServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/WorkerProcess.java
  dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyDataServer.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3HttpHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3HttpPipelineHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyBaseTask.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyBucketTask.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyObjectTask.java
  dora/tests/integration/src/test/java/alluxio/client/rest/CreateBucketTest.java
  dora/tests/integration/src/test/java/alluxio/client/rest/ListStatusTest.java
  dora/tests/integration/src/test/java/alluxio/client/rest/S3ObjectTest.java
Labels: type-feature

#18061 Fix copy ufs manager creation
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
  dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
  dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Labels: type-bug

#18060 Add format function in CLI
  cli/src/alluxio.org/cli/env/command.go
Labels: type-ease-of-use

#18063 Choose preferred worker from worker list
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
Labels: type-feature

#18062 Enable dora meta store WAL
  dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
Labels: type-bug

#18064 [SMALLFIX] Allow FileSystem to have FSContext by inheritance
  dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
Labels: type-ease-of-use

#18066 Remove swift ufs
  build/lib/copy_jars.sh
  conf/core-site.xml.template
  dev/scripts/src/alluxio.org/build/modules.yml
  docs/_data/generated/common-configuration.csv
  docs/_data/generated/en/common-configuration.yml
  docs/_data/menu-en.yml
  docs/_data/table/cn/common-configuration.yml
  docs/en/api/Java-API.md
  docs/en/contributor/Documentation-Conventions.md
  docs/en/introduction/Introduction.md
  docs/en/ufs/CephObjectStorage.md
  docs/en/ufs/Storage-Overview.md
  docs/en/ufs/Swift.md
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  dora/core/client/hdfs/src/main/java/alluxio/hadoop/HadoopUtils.java
  dora/core/common/src/main/java/alluxio/Constants.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/conf/RemovedKey.java
  dora/core/common/src/main/java/alluxio/util/UnderFileSystemUtils.java
  dora/core/common/src/test/java/alluxio/util/UnderFileSystemUtilsTest.java
  dora/tests/integration/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java
  dora/tests/integration/src/test/java/alluxio/testutils/underfs/UnderFileSystemTestUtils.java
  dora/underfs/pom.xml
  dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
  dora/underfs/swift/pom.xml
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/KeystoneV3Access.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/KeystoneV3AccessProvider.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/MidPartLongRange.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/SwiftMockOutputStream.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/SwiftOutputStream.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java
  dora/underfs/swift/src/main/java/alluxio/underfs/swift/http/SwiftDirectClient.java
  dora/underfs/swift/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory
  dora/underfs/swift/src/test/java/alluxio/underfs/swift/SwiftOutputStreamTest.java
  dora/underfs/swift/src/test/java/alluxio/underfs/swift/SwiftUnderFileSystemFactoryTest.java
  dora/underfs/swift/src/test/resources/log4j.properties
Labels: type-feature

#18069 Refactor Fuse
  dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileEntry.java
  dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
  dora/tests/integration/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
Labels: type-code-quality

#18067 Remove kodo ufs
  build/lib/copy_jars.sh
  docs/_data/generated/common-configuration.csv
  docs/_data/generated/en/common-configuration.yml
  docs/_data/menu-en.yml
  docs/en/ufs/Qiniu-KODO.md
  docs/en/ufs/Storage-Overview.md
  dora/core/common/src/main/java/alluxio/Constants.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/underfs/kodo/pom.xml
  dora/underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoClient.java
  dora/underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java
  dora/underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoOutputStream.java
  dora/underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystem.java
  dora/underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystemFactory.java
  dora/underfs/kodo/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory
  dora/underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoOutputStreamTest.java
  dora/underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoUnderFileSystemFactoryTest.java
  dora/underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoUnderFileSystemTest.java
  dora/underfs/pom.xml
Labels: type-feature

#18072 Fix delta copy error report
  dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
Labels: type-bug

#18071 [DOCFIX] Reorder "Get Started" section of main nav menu
  docs/_data/menu-en.yml
  docs/en/Overview.md
  docs/en/compute/Flink.md
  docs/en/deploy/Get-Started.md
  docs/en/ufs/CephObjectStorage.md
Labels: type-docs

#18078 [DOCFIX] Label UFS contributed by community
  docs/en/ufs/Aliyun-OSS.md
  docs/en/ufs/CephFS.md
  docs/en/ufs/Huawei-OBS.md
  docs/en/ufs/Ozone.md
  docs/en/ufs/Storage-Overview.md
  docs/en/ufs/Tencent-COS.md
Labels: type-docs

#18083 [DOCFIX] Update Tensorflow Doc
  docs/en/compute/Tensorflow.md
Labels: type-docs

#17915 [DOCFIX] Update param String in RetryHandlingFileSystemMasterClient
  dora/core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
Labels: type-docs

#18068 Reduce CPU overhead by replacing while loop with await
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
Labels: type-performance

#18084 [DOCFIX] Rearrange Nav Menu
  docs/_data/menu-en.yml
  docs/en/api/Java-API.md
  docs/en/api/S3-API.md
  docs/en/fuse-sdk/FUSE-SDK-Overview.md
  docs/en/fuse-sdk/Local-Cache-Quick-Start.md
  docs/en/fuse-sdk/Local-Cache-Tuning.md
  docs/en/operation/User-CLI.md
  docs/en/presto-sdk/presto-sdk.md
  docs/en/reference/Glossary.md
  docs/en/reference/Troubleshooting.md
Labels: type-docs
