Repository Alluxio/alluxio, pull requests merged in 2024-06, with the labels that each got.

#18626 Update metric system with cherry-pick `Remove hostname from metrics key`
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
Labels: type-sync

#18627 Support MultiPartUpload in Tos
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
  underfs/tos/src/main/java/alluxio/underfs/tos/TOSLowLevelOutputStream.java
  underfs/tos/src/main/java/alluxio/underfs/tos/TOSUnderFileSystem.java
Labels: type-feature

#18628 Support more configuration in TOS
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  underfs/tos/src/main/java/alluxio/underfs/tos/TOSUnderFileSystem.java
Labels: type-feature

#18634 Allow running on early access and beta JDKs
  core/common/src/main/java/alluxio/util/CommonUtils.java
  core/common/src/test/java/alluxio/util/CommonUtilsTest.java
Labels: type-feature

#18637 Support Tos doc for Alluxio
  docs/cn/ufs/TOS.md
  docs/en/ufs/TOS.md
Labels: type-docs

#18638 Downgrade AWS SDK to 2.15.79
  pom.xml
Labels: type-bug

#18640 Disable invalidation time
  core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java
  core/server/master/src/test/java/alluxio/master/file/meta/InvalidationSyncCacheTest.java
Labels: type-bug
