Repository Alluxio/alluxio, pull requests merged in 2024-07, with the labels that each got.

#18642 Add back shaded netty within grpc
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
  pom.xml
Labels: type-feature, type-debt

#18648 Update Dockerfile to use Rocky8 as base image
  integration/docker/Dockerfile
Labels: type-devops

#18639 Fix job-master leak memory when submitting distributed jobs
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  job/common/src/main/java/alluxio/job/wire/Status.java
  job/server/src/main/java/alluxio/master/job/JobMaster.java
  job/server/src/main/java/alluxio/master/job/plan/PlanTracker.java
  job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
  job/server/src/test/java/alluxio/master/job/plan/PlanTrackerTest.java
  job/server/src/test/java/alluxio/master/job/tracker/CmdJobTrackerTest.java
Labels: type-bug

#18646 Support Unit Tests for TOS
  underfs/tos/src/test/java/alluxio/underfs/tos/TOSInputStreamTest.java
  underfs/tos/src/test/java/alluxio/underfs/tos/TOSLowLevelOutputStreamTest.java
  underfs/tos/src/test/java/alluxio/underfs/tos/TOSOutputStreamTest.java
  underfs/tos/src/test/java/alluxio/underfs/tos/TOSUnderFileSystemFactoryTest.java
  underfs/tos/src/test/java/alluxio/underfs/tos/TOSUnderFileSystemTest.java
Labels: type-feature

#18663 Install ucx on dockerfile jdk8
  dev/github/Dockerfile-jdk11
  dev/github/Dockerfile-jdk17
  dev/github/Dockerfile-jdk8
Labels: type-feature
