Repository Alluxio/alluxio, pull requests merged in 2024-02, with the labels that each got.

#18504 Fix DoraLoadCommandIntegrationTest
  dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
Labels: type-bug

#18506 Support nullable offset and length in get page RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpRequestUri.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
  dora/core/server/worker/src/test/java/alluxio/worker/http/TestHttpRequestUtil.java
Labels: type-bug

#18508 Add Regex support to direct access
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  tests/src/test/java/alluxio/client/fs/DirectAccessIntegrationTest.java
Labels: type-feature

#18516 Change default value of virtual node count per worker
  dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-performance

#18519 [DOCFIX] Fix link in Presto-Iceberg
  docs/en/compute/Presto-Iceberg.md
Labels: type-docs

#18498 Improve the local cache fallback behavior for corrupted pages
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/MemoryPageStoreTest.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
  dora/core/common/src/main/java/alluxio/exception/PageCorruptedException.java
Labels: type-code-quality

#18503 Fix runtime stats when cache hit
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Labels: type-code-quality

#18530 Add decommission capability and removenode cmd
  cli/src/alluxio.org/cli/cmd/process/process.go
  cli/src/alluxio.org/cli/cmd/process/remove_worker.go
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/wire/WorkerIdentity.java
  dora/core/common/src/test/java/alluxio/wire/WorkerIdentityTest.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/command/NodesCommand.java
  dora/shell/src/main/java/alluxio/cli/fsadmin/nodes/RemoveWorkerCommand.java
  dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/command/NodesCommandIntegrationTest.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-feature
