Repository Alluxio/alluxio, pull requests merged in 2024-03, with the labels that each got.

#18532 Fix code injection admin
  core/common/src/main/java/alluxio/util/CommonUtils.java
  core/common/src/main/java/alluxio/util/ShellUtils.java
  core/common/src/test/java/alluxio/util/CommonUtilsTest.java
  core/common/src/test/java/alluxio/util/ShellUtilsTest.java
Labels: type-bug

#18536 Fix code injection admin
  dora/core/common/src/main/java/alluxio/util/CommonUtils.java
  dora/core/common/src/main/java/alluxio/util/ShellUtils.java
  dora/core/common/src/test/java/alluxio/util/CommonUtilsTest.java
  dora/core/common/src/test/java/alluxio/util/ShellUtilsTest.java
Labels: type-bug

#18537 Fix libjnifuse.so build
  dora/integration/jnifuse/native/src/main/resources/libjnifuse.so
Labels: type-bug

#18480 Fix AlluxioFileSystem memory leak
  core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
  core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioFileSystem.java
Labels: type-bug

#18525 Fix data corrupted issue when loading from UFS
  core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
  core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
  tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
Labels: type-bug

#18546 Fix data corruption, Port [#18525] to branch-2.10
  core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
  core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
  core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
  tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
Labels: type-sync

#18549 Add global ratelimiter and make async timeout configurable in Proxy V2
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RequestServlet.java
  core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Labels: type-bug

#18555 [DOCFIX] Update Requirements.md
  docs/en/deploy/Requirements.md
Labels: type-docs

#18553 Support running on early-access JDK
  dora/core/common/src/main/java/alluxio/util/CommonUtils.java
Labels: type-bug

#18561 Remove distributedMv
  docs/cn/overview/JobService.md
  docs/en/operation/User-CLI.md
  docs/en/overview/JobService.md
  shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
Labels: type-bug

#18554 Fix etcd calls exception handling and adjust failure detection timeout
  dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
  dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
  dora/core/common/src/main/java/alluxio/membership/ServiceRegistryMembershipManager.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-bug
