Repository Alluxio/alluxio, pull requests merged in 2024-05, with the labels that each got.

#18598 Install netcat in Dockerfile
  integration/docker/Dockerfile-base
Labels: type-bug

#18596 Add http server health check
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-feature

#18602 Return 404 when head the file end with slash
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-bug

#18604 Add health check RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpRequestUri.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Labels: type-feature

#18606 Add UfsUrl and its UT
  common/transport/src/main/proto/grpc/common.proto
  dora/core/common/src/main/java/alluxio/uri/UfsUrl.java
  dora/core/common/src/test/java/alluxio/UfsUrlTest.java
Labels: type-feature

#18608 [DOCFIX] Add warning for distributedCp limitations
  docs/en/operation/User-CLI.md
Labels: type-docs

#18613 Fix read exception when the range size is smaller than Block size
  core/common/src/main/java/alluxio/retry/CountingRetry.java
  core/common/src/main/java/alluxio/retry/ExponentialBackoffRetry.java
  core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/RetryPolicy.java
  core/common/src/main/java/alluxio/retry/SleepingRetry.java
  core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/TimeoutRetry.java
  underfs/cos/src/main/java/alluxio/underfs/cos/COSInputStream.java
  underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java
  underfs/obs/src/main/java/alluxio/underfs/obs/OBSInputStream.java
  underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java
  underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
Labels: type-bug
