Repository Alluxio/alluxio, pull requests merged in 2024-04, with the labels that each got.

#18569 Remove distributedLoad
  docs/cn/overview/JobService.md
  docs/en/operation/User-CLI.md
  docs/en/overview/JobService.md
  shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
  stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchOperation.java
  stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
  tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
  tests/src/test/java/alluxio/client/cli/job/GetCmdStatusCommandTest.java
Labels: type-debt

#18568 Fix local cache ttl
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Labels: type-bug

#18573 Name threads used by LocalCacheManager
  dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Labels: type-code-quality

#18578 Add position read supports for s3 proxy
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Labels: type-performance

#18587 Fix the active rpc metrics; Port [#17234] to branch-2.10
  core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Labels: type-bug

#18580 Remove noisy logging in InstanceMetadataServiceResourceFetcher
  conf/log4j.properties
Labels: type-ease-of-use

#18582 Update the logic of Alluxio clearing expired metadata
  dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
  dora/core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
Labels: type-bug

#18589 Fix cacheMissPercentage metric; Port [#18208] to branch-2.10
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
  core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
  core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSyncHelper.java
  core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/block/io/MetricAccountingBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedUfsBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/UfsBlockReadOptions.java
  core/server/worker/src/test/java/alluxio/worker/page/PagedBlockReaderTest.java
Labels: type-bug

#18590 Allow MetricAccountingBlockReader to accept any BlockReader
  core/server/worker/src/main/java/alluxio/worker/block/io/MetricAccountingBlockReader.java
Labels: type-debt

#18574 Update local cache to catch 3.x
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheStatus.java
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheUsage.java
  core/client/fs/src/main/java/alluxio/client/file/cache/CacheUsageView.java
  core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
  core/client/fs/src/main/java/alluxio/client/file/cache/PageInfo.java
  core/client/fs/src/main/java/alluxio/client/file/cache/PageMetaStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/QuotaPageMetaStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/TimeBoundPageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/context/CachePerThreadContext.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreDir.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStoreDir.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/QuotaManagedPageStoreDir.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
  core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
  core/client/fs/src/test/java/alluxio/client/file/MockFileInStream.java
  core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/HangingPageStore.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/TimeBoundPageStoreTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/store/MemoryPageStoreTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreDirTest.java
  core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
  core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
  core/common/pom.xml
  core/common/src/main/java/alluxio/conf/PropertyKey.java
  core/common/src/main/java/alluxio/exception/PageCorruptedException.java
  core/common/src/main/java/alluxio/file/ByteArrayTargetBuffer.java
  core/common/src/main/java/alluxio/file/ByteBufferTargetBuffer.java
  core/common/src/main/java/alluxio/file/NettyBufTargetBuffer.java
  core/common/src/main/java/alluxio/file/ReadTargetBuffer.java
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
  core/common/src/main/java/alluxio/network/protocol/databuffer/DataFileChannel.java
  core/common/src/main/java/alluxio/util/io/ChannelAdapters.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockMetaStore.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
  core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreDir.java
  core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
  core/server/worker/src/test/java/alluxio/worker/page/PagedBlockWriterTest.java
  pom.xml
  tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
Labels: type-sync

#18594 Add http getPage cache hit ratio
  dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
Labels: type-feature
