Repository Alluxio/alluxio, pull requests merged in 2024-01, with the labels that each got.

#18481 Support write page with RESTful API
  dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
  dora/core/server/worker/src/main/java/alluxio/worker/http/vo/WritePageResponseVO.java
Labels: type-feature

#18482 Add fake numbers for statfs
  dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Labels: type-feature

#18485 Add the metrics to record the direct memory used by Netty
  core/common/src/main/java/alluxio/metrics/MetricKey.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/server/master/src/main/java/alluxio/master/throttle/MetricsMonitorUtils.java
  core/server/master/src/main/java/alluxio/master/throttle/ServerIndicator.java
  core/server/master/src/main/java/alluxio/master/throttle/SystemMonitor.java
  core/server/master/src/test/java/alluxio/master/throttle/IndicatorsTests.java
  docs/_data/table/cn/process-metrics.yml
  docs/_data/table/en/process-metrics.yml
Labels: type-code-quality

#18487 [DOCFIX] Update kerberos configuration 'alluxio.hadoop.kerberos.keytab.login.autorenewal' in HDFS docs
  docs/en/ufs/HDFS.md
Labels: type-docs

#18462 Create metadata directory in initiateMultipartUpload method
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
  dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
Labels: type-performance

#18417 Avoid get block info when positioned read for first retry
  core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
  core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
  core/common/src/main/java/alluxio/conf/PropertyKey.java
Labels: type-performance

#18490 Fix entrypoint
  integration/docker/entrypoint.sh
Labels: type-bug

#18484 Fix the issue of S3 range read
  dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyObjectTask.java
Labels: type-bug

#18492 Fix negative size if specified filesize over Integer.MAX_VALUE for stressWorkerBench
  dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Labels: type-bug

#18495 Add ServiceRegistry membership manager which only include active workers
  dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/MembershipType.java
  dora/core/common/src/main/java/alluxio/membership/ServiceRegistryMembershipManager.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-feature

#18496 Set min replication when TTL expires to free a file
  core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
Labels: type-bug

#18499 Add http server port in the worker net address
  dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
  dora/core/common/src/main/java/alluxio/membership/WorkerServiceEntity.java
  dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
  dora/core/common/src/test/java/alluxio/membership/ServiceEntityTest.java
  dora/core/common/src/test/java/alluxio/wire/WorkerNetAddressTest.java
  dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
  dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Labels: type-feature, workload-machine-learning, area-worker, area-s3-rest-api
